/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AnalysisResponse from '../model/AnalysisResponse';
import ErrorResponse from '../model/ErrorResponse';
import ForecastRequest from '../model/ForecastRequest';
import ValidationErrorResponse from '../model/ValidationErrorResponse';

/**
* Analysis service.
* @module ForecastAPI/api/AnalysisApi
* @version 2.0.0
*/
export default class AnalysisApi {

    /**
    * Constructs a new AnalysisApi. 
    * @alias module:ForecastAPI/api/AnalysisApi
    * @class
    * @param {module:ForecastAPI/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ForecastAPI/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the v2AnalyzePost operation.
     * @callback module:ForecastAPI/api/AnalysisApi~v2AnalyzePostCallback
     * @param {String} error Error message, if any.
     * @param {module:ForecastAPI/model/AnalysisResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Analyze time series data without generating forecast
     * @param {module:ForecastAPI/model/ForecastRequest} forecastRequest 
     * @param {module:ForecastAPI/api/AnalysisApi~v2AnalyzePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:ForecastAPI/model/AnalysisResponse}
     */
    v2AnalyzePost(forecastRequest, callback) {
      let postBody = forecastRequest;
      // verify the required parameter 'forecastRequest' is set
      if (forecastRequest === undefined || forecastRequest === null) {
        throw new Error("Missing the required parameter 'forecastRequest' when calling v2AnalyzePost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = AnalysisResponse;
      return this.apiClient.callApi(
        '/v2/analyze', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
