/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/forecastapi/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/forecastapi/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ForecastApi);
  }
}(this, function(expect, ForecastApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ForecastApi.InventoryPlanningResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InventoryPlanningResponse', function() {
    it('should create an instance of InventoryPlanningResponse', function() {
      // uncomment below and update the code to test InventoryPlanningResponse
      //var instance = new ForecastApi.InventoryPlanningResponse();
      //expect(instance).to.be.a(ForecastApi.InventoryPlanningResponse);
    });

    it('should have the property result (base name: "result")', function() {
      // uncomment below and update the code to test the property result
      //var instance = new ForecastApi.InventoryPlanningResponse();
      //expect(instance).to.be();
    });

    it('should have the property meta (base name: "meta")', function() {
      // uncomment below and update the code to test the property meta
      //var instance = new ForecastApi.InventoryPlanningResponse();
      //expect(instance).to.be();
    });

  });

}));
