/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/ForecastAPI\ForecastSDK/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/ForecastAPI\ForecastSDK/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ForecastApi);
  }
}(this, function(expect, ForecastApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ForecastApi.InventoryPlanningResponseResultSuppliersInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InventoryPlanningResponseResultSuppliersInner', function() {
    it('should create an instance of InventoryPlanningResponseResultSuppliersInner', function() {
      // uncomment below and update the code to test InventoryPlanningResponseResultSuppliersInner
      //var instance = new ForecastApi.InventoryPlanningResponseResultSuppliersInner();
      //expect(instance).to.be.a(ForecastApi.InventoryPlanningResponseResultSuppliersInner);
    });

    it('should have the property supplier (base name: "supplier")', function() {
      // uncomment below and update the code to test the property supplier
      //var instance = new ForecastApi.InventoryPlanningResponseResultSuppliersInner();
      //expect(instance).to.be();
    });

    it('should have the property orderQuantity (base name: "order_quantity")', function() {
      // uncomment below and update the code to test the property orderQuantity
      //var instance = new ForecastApi.InventoryPlanningResponseResultSuppliersInner();
      //expect(instance).to.be();
    });

    it('should have the property totalCost (base name: "total_cost")', function() {
      // uncomment below and update the code to test the property totalCost
      //var instance = new ForecastApi.InventoryPlanningResponseResultSuppliersInner();
      //expect(instance).to.be();
    });

    it('should have the property costPerUnit (base name: "cost_per_unit")', function() {
      // uncomment below and update the code to test the property costPerUnit
      //var instance = new ForecastApi.InventoryPlanningResponseResultSuppliersInner();
      //expect(instance).to.be();
    });

    it('should have the property expectedDelivery (base name: "expected_delivery")', function() {
      // uncomment below and update the code to test the property expectedDelivery
      //var instance = new ForecastApi.InventoryPlanningResponseResultSuppliersInner();
      //expect(instance).to.be();
    });

    it('should have the property leadTimeDays (base name: "lead_time_days")', function() {
      // uncomment below and update the code to test the property leadTimeDays
      //var instance = new ForecastApi.InventoryPlanningResponseResultSuppliersInner();
      //expect(instance).to.be();
    });

    it('should have the property minimumOrderQuantity (base name: "minimum_order_quantity")', function() {
      // uncomment below and update the code to test the property minimumOrderQuantity
      //var instance = new ForecastApi.InventoryPlanningResponseResultSuppliersInner();
      //expect(instance).to.be();
    });

    it('should have the property reliabilityScore (base name: "reliability_score")', function() {
      // uncomment below and update the code to test the property reliabilityScore
      //var instance = new ForecastApi.InventoryPlanningResponseResultSuppliersInner();
      //expect(instance).to.be();
    });

    it('should have the property leadTimeDemand (base name: "lead_time_demand")', function() {
      // uncomment below and update the code to test the property leadTimeDemand
      //var instance = new ForecastApi.InventoryPlanningResponseResultSuppliersInner();
      //expect(instance).to.be();
    });

    it('should have the property safetyStock (base name: "safety_stock")', function() {
      // uncomment below and update the code to test the property safetyStock
      //var instance = new ForecastApi.InventoryPlanningResponseResultSuppliersInner();
      //expect(instance).to.be();
    });

    it('should have the property reorderPoint (base name: "reorder_point")', function() {
      // uncomment below and update the code to test the property reorderPoint
      //var instance = new ForecastApi.InventoryPlanningResponseResultSuppliersInner();
      //expect(instance).to.be();
    });

    it('should have the property reason (base name: "reason")', function() {
      // uncomment below and update the code to test the property reason
      //var instance = new ForecastApi.InventoryPlanningResponseResultSuppliersInner();
      //expect(instance).to.be();
    });

  });

}));
