/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/ForecastAPI\ForecastSDK/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/ForecastAPI\ForecastSDK/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ForecastApi);
  }
}(this, function(expect, ForecastApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ForecastApi.TrafficForecastingResponseResultCostOptimizationRecommendationsInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TrafficForecastingResponseResultCostOptimizationRecommendationsInner', function() {
    it('should create an instance of TrafficForecastingResponseResultCostOptimizationRecommendationsInner', function() {
      // uncomment below and update the code to test TrafficForecastingResponseResultCostOptimizationRecommendationsInner
      //var instance = new ForecastApi.TrafficForecastingResponseResultCostOptimizationRecommendationsInner();
      //expect(instance).to.be.a(ForecastApi.TrafficForecastingResponseResultCostOptimizationRecommendationsInner);
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new ForecastApi.TrafficForecastingResponseResultCostOptimizationRecommendationsInner();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new ForecastApi.TrafficForecastingResponseResultCostOptimizationRecommendationsInner();
      //expect(instance).to.be();
    });

    it('should have the property currentCapacity (base name: "current_capacity")', function() {
      // uncomment below and update the code to test the property currentCapacity
      //var instance = new ForecastApi.TrafficForecastingResponseResultCostOptimizationRecommendationsInner();
      //expect(instance).to.be();
    });

    it('should have the property recommendedCapacity (base name: "recommended_capacity")', function() {
      // uncomment below and update the code to test the property recommendedCapacity
      //var instance = new ForecastApi.TrafficForecastingResponseResultCostOptimizationRecommendationsInner();
      //expect(instance).to.be();
    });

    it('should have the property potentialSavings (base name: "potential_savings")', function() {
      // uncomment below and update the code to test the property potentialSavings
      //var instance = new ForecastApi.TrafficForecastingResponseResultCostOptimizationRecommendationsInner();
      //expect(instance).to.be();
    });

  });

}));
