/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/ForecastAPI\ForecastSDK/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/ForecastAPI\ForecastSDK/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ForecastApi);
  }
}(this, function(expect, ForecastApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ForecastApi.TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner', function() {
    it('should create an instance of TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner', function() {
      // uncomment below and update the code to test TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner
      //var instance = new ForecastApi.TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner();
      //expect(instance).to.be.a(ForecastApi.TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner);
    });

    it('should have the property action (base name: "action")', function() {
      // uncomment below and update the code to test the property action
      //var instance = new ForecastApi.TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner();
      //expect(instance).to.be();
    });

    it('should have the property currentCapacity (base name: "current_capacity")', function() {
      // uncomment below and update the code to test the property currentCapacity
      //var instance = new ForecastApi.TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner();
      //expect(instance).to.be();
    });

    it('should have the property recommendedCapacity (base name: "recommended_capacity")', function() {
      // uncomment below and update the code to test the property recommendedCapacity
      //var instance = new ForecastApi.TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner();
      //expect(instance).to.be();
    });

    it('should have the property scalingFactor (base name: "scaling_factor")', function() {
      // uncomment below and update the code to test the property scalingFactor
      //var instance = new ForecastApi.TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner();
      //expect(instance).to.be();
    });

    it('should have the property reason (base name: "reason")', function() {
      // uncomment below and update the code to test the property reason
      //var instance = new ForecastApi.TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner();
      //expect(instance).to.be();
    });

    it('should have the property urgency (base name: "urgency")', function() {
      // uncomment below and update the code to test the property urgency
      //var instance = new ForecastApi.TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner();
      //expect(instance).to.be();
    });

    it('should have the property estimatedTimeToScale (base name: "estimated_time_to_scale")', function() {
      // uncomment below and update the code to test the property estimatedTimeToScale
      //var instance = new ForecastApi.TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner();
      //expect(instance).to.be();
    });

    it('should have the property potentialSavings (base name: "potential_savings")', function() {
      // uncomment below and update the code to test the property potentialSavings
      //var instance = new ForecastApi.TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner();
      //expect(instance).to.be();
    });

  });

}));
