/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.2
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AnalysisResponseMeta from './AnalysisResponseMeta';
import AnalysisResponseResult from './AnalysisResponseResult';

/**
 * The AnalysisResponse model module.
 * @module model/AnalysisResponse
 * @version 2.0.2
 */
class AnalysisResponse {
    /**
     * Constructs a new <code>AnalysisResponse</code>.
     * @alias module:model/AnalysisResponse
     */
    constructor() { 
        
        AnalysisResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AnalysisResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AnalysisResponse} obj Optional instance to populate.
     * @return {module:model/AnalysisResponse} The populated <code>AnalysisResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AnalysisResponse();

            if (data.hasOwnProperty('result')) {
                obj['result'] = AnalysisResponseResult.constructFromObject(data['result']);
            }
            if (data.hasOwnProperty('meta')) {
                obj['meta'] = AnalysisResponseMeta.constructFromObject(data['meta']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AnalysisResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AnalysisResponse</code>.
     */
    static validateJSON(data) {
        // validate the optional field `result`
        if (data['result']) { // data not null
          AnalysisResponseResult.validateJSON(data['result']);
        }
        // validate the optional field `meta`
        if (data['meta']) { // data not null
          AnalysisResponseMeta.validateJSON(data['meta']);
        }

        return true;
    }


}



/**
 * @member {module:model/AnalysisResponseResult} result
 */
AnalysisResponse.prototype['result'] = undefined;

/**
 * @member {module:model/AnalysisResponseMeta} meta
 */
AnalysisResponse.prototype['meta'] = undefined;






export default AnalysisResponse;

