/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AnalysisResponseResultCharacteristics from './AnalysisResponseResultCharacteristics';

/**
 * The AnalysisResponseResult model module.
 * @module model/AnalysisResponseResult
 * @version 2.0.0
 */
class AnalysisResponseResult {
    /**
     * Constructs a new <code>AnalysisResponseResult</code>.
     * @alias module:model/AnalysisResponseResult
     */
    constructor() { 
        
        AnalysisResponseResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AnalysisResponseResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AnalysisResponseResult} obj Optional instance to populate.
     * @return {module:model/AnalysisResponseResult} The populated <code>AnalysisResponseResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AnalysisResponseResult();

            if (data.hasOwnProperty('pattern_type')) {
                obj['pattern_type'] = ApiClient.convertToType(data['pattern_type'], 'String');
            }
            if (data.hasOwnProperty('characteristics')) {
                obj['characteristics'] = AnalysisResponseResultCharacteristics.constructFromObject(data['characteristics']);
            }
            if (data.hasOwnProperty('recommended_methods')) {
                obj['recommended_methods'] = ApiClient.convertToType(data['recommended_methods'], ['String']);
            }
            if (data.hasOwnProperty('confidence')) {
                obj['confidence'] = ApiClient.convertToType(data['confidence'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AnalysisResponseResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AnalysisResponseResult</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['pattern_type'] && !(typeof data['pattern_type'] === 'string' || data['pattern_type'] instanceof String)) {
            throw new Error("Expected the field `pattern_type` to be a primitive type in the JSON string but got " + data['pattern_type']);
        }
        // validate the optional field `characteristics`
        if (data['characteristics']) { // data not null
          AnalysisResponseResultCharacteristics.validateJSON(data['characteristics']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['recommended_methods'])) {
            throw new Error("Expected the field `recommended_methods` to be an array in the JSON data but got " + data['recommended_methods']);
        }
        // ensure the json data is a string
        if (data['confidence'] && !(typeof data['confidence'] === 'string' || data['confidence'] instanceof String)) {
            throw new Error("Expected the field `confidence` to be a primitive type in the JSON string but got " + data['confidence']);
        }

        return true;
    }


}



/**
 * @member {module:model/AnalysisResponseResult.PatternTypeEnum} pattern_type
 */
AnalysisResponseResult.prototype['pattern_type'] = undefined;

/**
 * @member {module:model/AnalysisResponseResultCharacteristics} characteristics
 */
AnalysisResponseResult.prototype['characteristics'] = undefined;

/**
 * @member {Array.<String>} recommended_methods
 */
AnalysisResponseResult.prototype['recommended_methods'] = undefined;

/**
 * @member {module:model/AnalysisResponseResult.ConfidenceEnum} confidence
 */
AnalysisResponseResult.prototype['confidence'] = undefined;





/**
 * Allowed values for the <code>pattern_type</code> property.
 * @enum {String}
 * @readonly
 */
AnalysisResponseResult['PatternTypeEnum'] = {

    /**
     * value: "regular"
     * @const
     */
    "regular": "regular",

    /**
     * value: "intermittent"
     * @const
     */
    "intermittent": "intermittent",

    /**
     * value: "seasonal"
     * @const
     */
    "seasonal": "seasonal",

    /**
     * value: "trending"
     * @const
     */
    "trending": "trending"
};


/**
 * Allowed values for the <code>confidence</code> property.
 * @enum {String}
 * @readonly
 */
AnalysisResponseResult['ConfidenceEnum'] = {

    /**
     * value: "high"
     * @const
     */
    "high": "high",

    /**
     * value: "medium"
     * @const
     */
    "medium": "medium",

    /**
     * value: "low"
     * @const
     */
    "low": "low"
};



export default AnalysisResponseResult;

