/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AnomalyDetectionRequestAllOfAnomalySettings model module.
 * @module model/AnomalyDetectionRequestAllOfAnomalySettings
 * @version 2.0.0
 */
class AnomalyDetectionRequestAllOfAnomalySettings {
    /**
     * Constructs a new <code>AnomalyDetectionRequestAllOfAnomalySettings</code>.
     * Optional detection configuration; omit for automatic method selection
     * @alias module:model/AnomalyDetectionRequestAllOfAnomalySettings
     */
    constructor() { 
        
        AnomalyDetectionRequestAllOfAnomalySettings.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['method'] = 'auto';
    }

    /**
     * Constructs a <code>AnomalyDetectionRequestAllOfAnomalySettings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AnomalyDetectionRequestAllOfAnomalySettings} obj Optional instance to populate.
     * @return {module:model/AnomalyDetectionRequestAllOfAnomalySettings} The populated <code>AnomalyDetectionRequestAllOfAnomalySettings</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AnomalyDetectionRequestAllOfAnomalySettings();

            if (data.hasOwnProperty('method')) {
                obj['method'] = ApiClient.convertToType(data['method'], 'String');
            }
            if (data.hasOwnProperty('threshold')) {
                obj['threshold'] = ApiClient.convertToType(data['threshold'], 'Number');
            }
            if (data.hasOwnProperty('multiplier')) {
                obj['multiplier'] = ApiClient.convertToType(data['multiplier'], 'Number');
            }
            if (data.hasOwnProperty('seasonal_period')) {
                obj['seasonal_period'] = ApiClient.convertToType(data['seasonal_period'], 'Number');
            }
            if (data.hasOwnProperty('minimum_periods')) {
                obj['minimum_periods'] = ApiClient.convertToType(data['minimum_periods'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AnomalyDetectionRequestAllOfAnomalySettings</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AnomalyDetectionRequestAllOfAnomalySettings</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['method'] && !(typeof data['method'] === 'string' || data['method'] instanceof String)) {
            throw new Error("Expected the field `method` to be a primitive type in the JSON string but got " + data['method']);
        }

        return true;
    }


}



/**
 * Detection method; auto picks the best fit for the data's characteristics
 * @member {module:model/AnomalyDetectionRequestAllOfAnomalySettings.MethodEnum} method
 * @default 'auto'
 */
AnomalyDetectionRequestAllOfAnomalySettings.prototype['method'] = 'auto';

/**
 * Z-score threshold for the zscore method
 * @member {Number} threshold
 */
AnomalyDetectionRequestAllOfAnomalySettings.prototype['threshold'] = undefined;

/**
 * IQR multiplier for the iqr method
 * @member {Number} multiplier
 */
AnomalyDetectionRequestAllOfAnomalySettings.prototype['multiplier'] = undefined;

/**
 * Season length for the seasonal method; detected automatically when omitted
 * @member {Number} seasonal_period
 */
AnomalyDetectionRequestAllOfAnomalySettings.prototype['seasonal_period'] = undefined;

/**
 * Minimum data points required before detection runs
 * @member {Number} minimum_periods
 */
AnomalyDetectionRequestAllOfAnomalySettings.prototype['minimum_periods'] = undefined;





/**
 * Allowed values for the <code>method</code> property.
 * @enum {String}
 * @readonly
 */
AnomalyDetectionRequestAllOfAnomalySettings['MethodEnum'] = {

    /**
     * value: "auto"
     * @const
     */
    "auto": "auto",

    /**
     * value: "zscore"
     * @const
     */
    "zscore": "zscore",

    /**
     * value: "iqr"
     * @const
     */
    "iqr": "iqr",

    /**
     * value: "seasonal"
     * @const
     */
    "seasonal": "seasonal"
};



export default AnomalyDetectionRequestAllOfAnomalySettings;

