/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AnomalyDetectionResponseResultAnomaliesInner model module.
 * @module model/AnomalyDetectionResponseResultAnomaliesInner
 * @version 2.1.0
 */
class AnomalyDetectionResponseResultAnomaliesInner {
    /**
     * Constructs a new <code>AnomalyDetectionResponseResultAnomaliesInner</code>.
     * Method-specific fields (z_score, deviation, iqr_multiple, …) accompany the common ones below
     * @alias module:model/AnomalyDetectionResponseResultAnomaliesInner
     * @extends Object
     */
    constructor() { 
        
        AnomalyDetectionResponseResultAnomaliesInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AnomalyDetectionResponseResultAnomaliesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AnomalyDetectionResponseResultAnomaliesInner} obj Optional instance to populate.
     * @return {module:model/AnomalyDetectionResponseResultAnomaliesInner} The populated <code>AnomalyDetectionResponseResultAnomaliesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AnomalyDetectionResponseResultAnomaliesInner();

            ApiClient.constructFromObject(data, obj, 'Object');
            

            if (data.hasOwnProperty('index')) {
                obj['index'] = ApiClient.convertToType(data['index'], 'Number');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
            if (data.hasOwnProperty('expected_range')) {
                obj['expected_range'] = ApiClient.convertToType(data['expected_range'], {'String': Object});
            }
            if (data.hasOwnProperty('severity')) {
                obj['severity'] = ApiClient.convertToType(data['severity'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AnomalyDetectionResponseResultAnomaliesInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AnomalyDetectionResponseResultAnomaliesInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['date'] && !(typeof data['date'] === 'string' || data['date'] instanceof String)) {
            throw new Error("Expected the field `date` to be a primitive type in the JSON string but got " + data['date']);
        }
        // ensure the json data is a string
        if (data['severity'] && !(typeof data['severity'] === 'string' || data['severity'] instanceof String)) {
            throw new Error("Expected the field `severity` to be a primitive type in the JSON string but got " + data['severity']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }

        return true;
    }


}



/**
 * Position of the point in the submitted data
 * @member {Number} index
 */
AnomalyDetectionResponseResultAnomaliesInner.prototype['index'] = undefined;

/**
 * @member {String} date
 */
AnomalyDetectionResponseResultAnomaliesInner.prototype['date'] = undefined;

/**
 * @member {Number} value
 */
AnomalyDetectionResponseResultAnomaliesInner.prototype['value'] = undefined;

/**
 * The range the point was expected to fall within
 * @member {Object.<String, Object>} expected_range
 */
AnomalyDetectionResponseResultAnomaliesInner.prototype['expected_range'] = undefined;

/**
 * @member {String} severity
 */
AnomalyDetectionResponseResultAnomaliesInner.prototype['severity'] = undefined;

/**
 * spike/dip for zscore, outlier_high/outlier_low for iqr, seasonal variants for seasonal
 * @member {String} type
 */
AnomalyDetectionResponseResultAnomaliesInner.prototype['type'] = undefined;






export default AnomalyDetectionResponseResultAnomaliesInner;

