/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AutoSelectionScoresValue from './AutoSelectionScoresValue';

/**
 * The AutoSelection model module.
 * @module model/AutoSelection
 * @version 2.2.0
 */
class AutoSelection {
    /**
     * Constructs a new <code>AutoSelection</code>.
     * Present only when &#x60;model: auto&#x60; was requested — which model actually answered, and why. On /v2/forecast and batch results it appears inside &#x60;model_info&#x60;; on /v2/inventory-planning and /v2/traffic-forecasting it appears under &#x60;meta&#x60;. 
     * @alias module:model/AutoSelection
     */
    constructor() { 
        
        AutoSelection.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AutoSelection</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AutoSelection} obj Optional instance to populate.
     * @return {module:model/AutoSelection} The populated <code>AutoSelection</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AutoSelection();

            if (data.hasOwnProperty('requested')) {
                obj['requested'] = ApiClient.convertToType(data['requested'], 'String');
            }
            if (data.hasOwnProperty('selected')) {
                obj['selected'] = ApiClient.convertToType(data['selected'], 'String');
            }
            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
            }
            if (data.hasOwnProperty('scores')) {
                obj['scores'] = ApiClient.convertToType(data['scores'], {'String': AutoSelectionScoresValue});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AutoSelection</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AutoSelection</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['requested'] && !(typeof data['requested'] === 'string' || data['requested'] instanceof String)) {
            throw new Error("Expected the field `requested` to be a primitive type in the JSON string but got " + data['requested']);
        }
        // ensure the json data is a string
        if (data['selected'] && !(typeof data['selected'] === 'string' || data['selected'] instanceof String)) {
            throw new Error("Expected the field `selected` to be a primitive type in the JSON string but got " + data['selected']);
        }
        // ensure the json data is a string
        if (data['reason'] && !(typeof data['reason'] === 'string' || data['reason'] instanceof String)) {
            throw new Error("Expected the field `reason` to be a primitive type in the JSON string but got " + data['reason']);
        }

        return true;
    }


}



/**
 * @member {String} requested
 */
AutoSelection.prototype['requested'] = undefined;

/**
 * The model that produced this response
 * @member {String} selected
 */
AutoSelection.prototype['selected'] = undefined;

/**
 * Why this model was selected. `scored_winner` means one model beat every alternative by a clear margin on realized accuracy for this identifier; everything else means the evidence-gathering default was served. 
 * @member {module:model/AutoSelection.ReasonEnum} reason
 */
AutoSelection.prototype['reason'] = undefined;

/**
 * Per-model realized-accuracy scorecard for this identifier, when one exists
 * @member {Object.<String, module:model/AutoSelectionScoresValue>} scores
 */
AutoSelection.prototype['scores'] = undefined;





/**
 * Allowed values for the <code>reason</code> property.
 * @enum {String}
 * @readonly
 */
AutoSelection['ReasonEnum'] = {

    /**
     * value: "no_history"
     * @const
     */
    "no_history": "no_history",

    /**
     * value: "insufficient_evidence"
     * @const
     */
    "insufficient_evidence": "insufficient_evidence",

    /**
     * value: "no_clear_winner"
     * @const
     */
    "no_clear_winner": "no_clear_winner",

    /**
     * value: "scored_winner"
     * @const
     */
    "scored_winner": "scored_winner"
};



export default AutoSelection;

