/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BatchForecastSeriesDataInner model module.
 * @module model/BatchForecastSeriesDataInner
 * @version 2.2.0
 */
class BatchForecastSeriesDataInner {
    /**
     * Constructs a new <code>BatchForecastSeriesDataInner</code>.
     * @alias module:model/BatchForecastSeriesDataInner
     * @param date {Date} 
     * @param value {Number} 
     */
    constructor(date, value) { 
        
        BatchForecastSeriesDataInner.initialize(this, date, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, date, value) { 
        obj['date'] = date;
        obj['value'] = value;
    }

    /**
     * Constructs a <code>BatchForecastSeriesDataInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BatchForecastSeriesDataInner} obj Optional instance to populate.
     * @return {module:model/BatchForecastSeriesDataInner} The populated <code>BatchForecastSeriesDataInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BatchForecastSeriesDataInner();

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BatchForecastSeriesDataInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BatchForecastSeriesDataInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BatchForecastSeriesDataInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

BatchForecastSeriesDataInner.RequiredProperties = ["date", "value"];

/**
 * @member {Date} date
 */
BatchForecastSeriesDataInner.prototype['date'] = undefined;

/**
 * @member {Number} value
 */
BatchForecastSeriesDataInner.prototype['value'] = undefined;






export default BatchForecastSeriesDataInner;

