/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BatchForecastStatusResponsePartsInner model module.
 * @module model/BatchForecastStatusResponsePartsInner
 * @version 2.0.0
 */
class BatchForecastStatusResponsePartsInner {
    /**
     * Constructs a new <code>BatchForecastStatusResponsePartsInner</code>.
     * @alias module:model/BatchForecastStatusResponsePartsInner
     */
    constructor() { 
        
        BatchForecastStatusResponsePartsInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BatchForecastStatusResponsePartsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BatchForecastStatusResponsePartsInner} obj Optional instance to populate.
     * @return {module:model/BatchForecastStatusResponsePartsInner} The populated <code>BatchForecastStatusResponsePartsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BatchForecastStatusResponsePartsInner();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('started_at')) {
                obj['started_at'] = ApiClient.convertToType(data['started_at'], 'Date');
            }
            if (data.hasOwnProperty('completed_at')) {
                obj['completed_at'] = ApiClient.convertToType(data['completed_at'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BatchForecastStatusResponsePartsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BatchForecastStatusResponsePartsInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}



/**
 * @member {module:model/BatchForecastStatusResponsePartsInner.StatusEnum} status
 */
BatchForecastStatusResponsePartsInner.prototype['status'] = undefined;

/**
 * @member {Date} started_at
 */
BatchForecastStatusResponsePartsInner.prototype['started_at'] = undefined;

/**
 * @member {Date} completed_at
 */
BatchForecastStatusResponsePartsInner.prototype['completed_at'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
BatchForecastStatusResponsePartsInner['StatusEnum'] = {

    /**
     * value: "pending"
     * @const
     */
    "pending": "pending",

    /**
     * value: "processing"
     * @const
     */
    "processing": "processing",

    /**
     * value: "completed"
     * @const
     */
    "completed": "completed",

    /**
     * value: "failed"
     * @const
     */
    "failed": "failed"
};



export default BatchForecastStatusResponsePartsInner;

