/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.2
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AccumulateOptions from './AccumulateOptions';
import AdjustmentsInner from './AdjustmentsInner';
import BatchForecastSeriesDataInner from './BatchForecastSeriesDataInner';
import ValueBounds from './ValueBounds';

/**
 * The BatchForecastSeries model module.
 * @module model/BatchForecastSeries
 * @version 2.0.2
 */
class BatchForecastSeries {
    /**
     * Constructs a new <code>BatchForecastSeries</code>.
     * @alias module:model/BatchForecastSeries
     * @param identifier {String} SKU, Product ID, or other identifier for this series
     * @param data {Array.<module:model/BatchForecastSeriesDataInner>} Historical data for this series (at most 1,000 points per series on the free tier)
     */
    constructor(identifier, data) { 
        
        BatchForecastSeries.initialize(this, identifier, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, identifier, data) { 
        obj['identifier'] = identifier;
        obj['data'] = data;
    }

    /**
     * Constructs a <code>BatchForecastSeries</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BatchForecastSeries} obj Optional instance to populate.
     * @return {module:model/BatchForecastSeries} The populated <code>BatchForecastSeries</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BatchForecastSeries();

            if (data.hasOwnProperty('identifier')) {
                obj['identifier'] = ApiClient.convertToType(data['identifier'], 'String');
            }
            if (data.hasOwnProperty('tenant_context')) {
                obj['tenant_context'] = ApiClient.convertToType(data['tenant_context'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [BatchForecastSeriesDataInner]);
            }
            if (data.hasOwnProperty('periods')) {
                obj['periods'] = ApiClient.convertToType(data['periods'], 'Number');
            }
            if (data.hasOwnProperty('frequency')) {
                obj['frequency'] = ApiClient.convertToType(data['frequency'], 'String');
            }
            if (data.hasOwnProperty('data_type')) {
                obj['data_type'] = ApiClient.convertToType(data['data_type'], 'String');
            }
            if (data.hasOwnProperty('confidence')) {
                obj['confidence'] = ApiClient.convertToType(data['confidence'], 'Number');
            }
            if (data.hasOwnProperty('confidence_level')) {
                obj['confidence_level'] = ApiClient.convertToType(data['confidence_level'], 'Number');
            }
            if (data.hasOwnProperty('quantiles')) {
                obj['quantiles'] = ApiClient.convertToType(data['quantiles'], ['Number']);
            }
            if (data.hasOwnProperty('value_bounds')) {
                obj['value_bounds'] = ValueBounds.constructFromObject(data['value_bounds']);
            }
            if (data.hasOwnProperty('adjustments')) {
                obj['adjustments'] = ApiClient.convertToType(data['adjustments'], [AdjustmentsInner]);
            }
            if (data.hasOwnProperty('accumulate')) {
                obj['accumulate'] = AccumulateOptions.constructFromObject(data['accumulate']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BatchForecastSeries</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BatchForecastSeries</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BatchForecastSeries.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['identifier'] && !(typeof data['identifier'] === 'string' || data['identifier'] instanceof String)) {
            throw new Error("Expected the field `identifier` to be a primitive type in the JSON string but got " + data['identifier']);
        }
        // ensure the json data is a string
        if (data['tenant_context'] && !(typeof data['tenant_context'] === 'string' || data['tenant_context'] instanceof String)) {
            throw new Error("Expected the field `tenant_context` to be a primitive type in the JSON string but got " + data['tenant_context']);
        }
        if (data['data']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['data'])) {
                throw new Error("Expected the field `data` to be an array in the JSON data but got " + data['data']);
            }
            // validate the optional field `data` (array)
            for (const item of data['data']) {
                BatchForecastSeriesDataInner.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['frequency'] && !(typeof data['frequency'] === 'string' || data['frequency'] instanceof String)) {
            throw new Error("Expected the field `frequency` to be a primitive type in the JSON string but got " + data['frequency']);
        }
        // ensure the json data is a string
        if (data['data_type'] && !(typeof data['data_type'] === 'string' || data['data_type'] instanceof String)) {
            throw new Error("Expected the field `data_type` to be a primitive type in the JSON string but got " + data['data_type']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['quantiles'])) {
            throw new Error("Expected the field `quantiles` to be an array in the JSON data but got " + data['quantiles']);
        }
        // validate the optional field `value_bounds`
        if (data['value_bounds']) { // data not null
          ValueBounds.validateJSON(data['value_bounds']);
        }
        if (data['adjustments']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['adjustments'])) {
                throw new Error("Expected the field `adjustments` to be an array in the JSON data but got " + data['adjustments']);
            }
            // validate the optional field `adjustments` (array)
            for (const item of data['adjustments']) {
                AdjustmentsInner.validateJSON(item);
            };
        }
        // validate the optional field `accumulate`
        if (data['accumulate']) { // data not null
          AccumulateOptions.validateJSON(data['accumulate']);
        }

        return true;
    }


}

BatchForecastSeries.RequiredProperties = ["identifier", "data"];

/**
 * SKU, Product ID, or other identifier for this series
 * @member {String} identifier
 */
BatchForecastSeries.prototype['identifier'] = undefined;

/**
 * Optional segmentation dimension — the same identifier may appear under several tenant_context values in one batch
 * @member {String} tenant_context
 */
BatchForecastSeries.prototype['tenant_context'] = undefined;

/**
 * Historical data for this series (at most 1,000 points per series on the free tier)
 * @member {Array.<module:model/BatchForecastSeriesDataInner>} data
 */
BatchForecastSeries.prototype['data'] = undefined;

/**
 * Override of the request-level horizon for this series
 * @member {Number} periods
 */
BatchForecastSeries.prototype['periods'] = undefined;

/**
 * Override of the request-level frequency
 * @member {module:model/BatchForecastSeries.FrequencyEnum} frequency
 */
BatchForecastSeries.prototype['frequency'] = undefined;

/**
 * Override of the request-level data type
 * @member {String} data_type
 */
BatchForecastSeries.prototype['data_type'] = undefined;

/**
 * Override of the request-level confidence
 * @member {Number} confidence
 */
BatchForecastSeries.prototype['confidence'] = undefined;

/**
 * Alias for `confidence`
 * @member {Number} confidence_level
 */
BatchForecastSeries.prototype['confidence_level'] = undefined;

/**
 * Decile levels to return per period — only deciles between 0.1 and 0.9 are accepted, because those are the levels every backend produces natively; anything finer would be interpolation served under a label the model never predicted. Adds a `quantiles` object to each forecast row alongside the usual bounds. Honoured by /v2/forecast and /v2/batch/forecast (request-level default or per-series override); rejected on grouped forecasts; ignored by other endpoints sharing this request shape. 
 * @member {Array.<module:model/BatchForecastSeries.QuantilesEnum>} quantiles
 */
BatchForecastSeries.prototype['quantiles'] = undefined;

/**
 * @member {module:model/ValueBounds} value_bounds
 */
BatchForecastSeries.prototype['value_bounds'] = undefined;

/**
 * What-if scenario applied on top of the forecast (\"assume we lose the enterprise deal\"). Adjustments compose in array order — ×2 then +50 is not +50 then ×2. Each one moves the point, both bounds and any quantile fan together. Returns an `adjusted` block; the adjusted path is never stored or accuracy-tracked. Honoured by /v2/forecast and /v2/batch/forecast (request-level default or per-series override — period windows are checked against each series' own horizon); rejected on grouped forecasts; ignored by other endpoints sharing this request shape. 
 * @member {Array.<module:model/AdjustmentsInner>} adjustments
 */
BatchForecastSeries.prototype['adjustments'] = undefined;

/**
 * @member {module:model/AccumulateOptions} accumulate
 */
BatchForecastSeries.prototype['accumulate'] = undefined;





/**
 * Allowed values for the <code>frequency</code> property.
 * @enum {String}
 * @readonly
 */
BatchForecastSeries['FrequencyEnum'] = {

    /**
     * value: "H"
     * @const
     */
    "H": "H",

    /**
     * value: "D"
     * @const
     */
    "D": "D",

    /**
     * value: "W"
     * @const
     */
    "W": "W",

    /**
     * value: "M"
     * @const
     */
    "M": "M",

    /**
     * value: "MS"
     * @const
     */
    "MS": "MS",

    /**
     * value: "ME"
     * @const
     */
    "ME": "ME",

    /**
     * value: "Q"
     * @const
     */
    "Q": "Q",

    /**
     * value: "Y"
     * @const
     */
    "Y": "Y"
};


/**
 * Allowed values for the <code>quantiles</code> property.
 * @enum {Number}
 * @readonly
 */
BatchForecastSeries['QuantilesEnum'] = {

    /**
     * value: 0.1
     * @const
     */
    "0.1": 0.1,

    /**
     * value: 0.2
     * @const
     */
    "0.2": 0.2,

    /**
     * value: 0.3
     * @const
     */
    "0.3": 0.3,

    /**
     * value: 0.4
     * @const
     */
    "0.4": 0.4,

    /**
     * value: 0.5
     * @const
     */
    "0.5": 0.5,

    /**
     * value: 0.6
     * @const
     */
    "0.6": 0.6,

    /**
     * value: 0.7
     * @const
     */
    "0.7": 0.7,

    /**
     * value: 0.8
     * @const
     */
    "0.8": 0.8,

    /**
     * value: 0.9
     * @const
     */
    "0.9": 0.9
};



export default BatchForecastSeries;

