/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.2
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AccumulateOptions from './AccumulateOptions';
import AdjustmentsInner from './AdjustmentsInner';
import BatchForecastSeries from './BatchForecastSeries';
import ValueBounds from './ValueBounds';

/**
 * The BatchForecastRequest model module.
 * @module model/BatchForecastRequest
 * @version 2.0.2
 */
class BatchForecastRequest {
    /**
     * Constructs a new <code>BatchForecastRequest</code>.
     * Either &#x60;series&#x60; (inline) or &#x60;file_key&#x60; (file-based, from /v2/batch/forecast/presign) is required. Every other field is a request-level default that each series inherits unless it declares its own override — except &#x60;model&#x60;, which is request-level only. &#x60;confidence_level&#x60; is accepted as an alias for &#x60;confidence&#x60;; if both are sent, &#x60;confidence&#x60; wins. 
     * @alias module:model/BatchForecastRequest
     */
    constructor() { 
        
        BatchForecastRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['periods'] = 6;
        obj['model'] = 'standard';
        obj['confidence'] = 0.8;
    }

    /**
     * Constructs a <code>BatchForecastRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BatchForecastRequest} obj Optional instance to populate.
     * @return {module:model/BatchForecastRequest} The populated <code>BatchForecastRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BatchForecastRequest();

            if (data.hasOwnProperty('series')) {
                obj['series'] = ApiClient.convertToType(data['series'], [BatchForecastSeries]);
            }
            if (data.hasOwnProperty('file_key')) {
                obj['file_key'] = ApiClient.convertToType(data['file_key'], 'String');
            }
            if (data.hasOwnProperty('periods')) {
                obj['periods'] = ApiClient.convertToType(data['periods'], 'Number');
            }
            if (data.hasOwnProperty('frequency')) {
                obj['frequency'] = ApiClient.convertToType(data['frequency'], 'String');
            }
            if (data.hasOwnProperty('data_type')) {
                obj['data_type'] = ApiClient.convertToType(data['data_type'], 'String');
            }
            if (data.hasOwnProperty('model')) {
                obj['model'] = ApiClient.convertToType(data['model'], 'String');
            }
            if (data.hasOwnProperty('confidence')) {
                obj['confidence'] = ApiClient.convertToType(data['confidence'], 'Number');
            }
            if (data.hasOwnProperty('confidence_level')) {
                obj['confidence_level'] = ApiClient.convertToType(data['confidence_level'], 'Number');
            }
            if (data.hasOwnProperty('quantiles')) {
                obj['quantiles'] = ApiClient.convertToType(data['quantiles'], ['Number']);
            }
            if (data.hasOwnProperty('value_bounds')) {
                obj['value_bounds'] = ValueBounds.constructFromObject(data['value_bounds']);
            }
            if (data.hasOwnProperty('adjustments')) {
                obj['adjustments'] = ApiClient.convertToType(data['adjustments'], [AdjustmentsInner]);
            }
            if (data.hasOwnProperty('accumulate')) {
                obj['accumulate'] = AccumulateOptions.constructFromObject(data['accumulate']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BatchForecastRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BatchForecastRequest</code>.
     */
    static validateJSON(data) {
        if (data['series']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['series'])) {
                throw new Error("Expected the field `series` to be an array in the JSON data but got " + data['series']);
            }
            // validate the optional field `series` (array)
            for (const item of data['series']) {
                BatchForecastSeries.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['file_key'] && !(typeof data['file_key'] === 'string' || data['file_key'] instanceof String)) {
            throw new Error("Expected the field `file_key` to be a primitive type in the JSON string but got " + data['file_key']);
        }
        // ensure the json data is a string
        if (data['frequency'] && !(typeof data['frequency'] === 'string' || data['frequency'] instanceof String)) {
            throw new Error("Expected the field `frequency` to be a primitive type in the JSON string but got " + data['frequency']);
        }
        // ensure the json data is a string
        if (data['data_type'] && !(typeof data['data_type'] === 'string' || data['data_type'] instanceof String)) {
            throw new Error("Expected the field `data_type` to be a primitive type in the JSON string but got " + data['data_type']);
        }
        // ensure the json data is a string
        if (data['model'] && !(typeof data['model'] === 'string' || data['model'] instanceof String)) {
            throw new Error("Expected the field `model` to be a primitive type in the JSON string but got " + data['model']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['quantiles'])) {
            throw new Error("Expected the field `quantiles` to be an array in the JSON data but got " + data['quantiles']);
        }
        // validate the optional field `value_bounds`
        if (data['value_bounds']) { // data not null
          ValueBounds.validateJSON(data['value_bounds']);
        }
        if (data['adjustments']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['adjustments'])) {
                throw new Error("Expected the field `adjustments` to be an array in the JSON data but got " + data['adjustments']);
            }
            // validate the optional field `adjustments` (array)
            for (const item of data['adjustments']) {
                AdjustmentsInner.validateJSON(item);
            };
        }
        // validate the optional field `accumulate`
        if (data['accumulate']) { // data not null
          AccumulateOptions.validateJSON(data['accumulate']);
        }

        return true;
    }


}



/**
 * The series to forecast — up to 100,000 per call on a paid plan, 10 on the free tier
 * @member {Array.<module:model/BatchForecastSeries>} series
 */
BatchForecastRequest.prototype['series'] = undefined;

/**
 * Instead of inline `series` — the key returned by /v2/batch/forecast/presign, after uploading a JSON file of the same shape as this request body (an object with a `series` array). Series from a file are validated as they are streamed: an invalid series fails that series, not the whole batch. 
 * @member {String} file_key
 */
BatchForecastRequest.prototype['file_key'] = undefined;

/**
 * Default forecast horizon for series that don't set their own
 * @member {Number} periods
 * @default 6
 */
BatchForecastRequest.prototype['periods'] = 6;

/**
 * Default data frequency
 * @member {module:model/BatchForecastRequest.FrequencyEnum} frequency
 */
BatchForecastRequest.prototype['frequency'] = undefined;

/**
 * Default data type
 * @member {String} data_type
 */
BatchForecastRequest.prototype['data_type'] = undefined;

/**
 * Forecasting engine for the whole batch (request-level only)
 * @member {module:model/BatchForecastRequest.ModelEnum} model
 * @default 'standard'
 */
BatchForecastRequest.prototype['model'] = 'standard';

/**
 * Default confidence level for prediction intervals
 * @member {Number} confidence
 * @default 0.8
 */
BatchForecastRequest.prototype['confidence'] = 0.8;

/**
 * Alias for `confidence`
 * @member {Number} confidence_level
 */
BatchForecastRequest.prototype['confidence_level'] = undefined;

/**
 * Decile levels to return per period — only deciles between 0.1 and 0.9 are accepted, because those are the levels every backend produces natively; anything finer would be interpolation served under a label the model never predicted. Adds a `quantiles` object to each forecast row alongside the usual bounds. Honoured by /v2/forecast and /v2/batch/forecast (request-level default or per-series override); rejected on grouped forecasts; ignored by other endpoints sharing this request shape. 
 * @member {Array.<module:model/BatchForecastRequest.QuantilesEnum>} quantiles
 */
BatchForecastRequest.prototype['quantiles'] = undefined;

/**
 * @member {module:model/ValueBounds} value_bounds
 */
BatchForecastRequest.prototype['value_bounds'] = undefined;

/**
 * What-if scenario applied on top of the forecast (\"assume we lose the enterprise deal\"). Adjustments compose in array order — ×2 then +50 is not +50 then ×2. Each one moves the point, both bounds and any quantile fan together. Returns an `adjusted` block; the adjusted path is never stored or accuracy-tracked. Honoured by /v2/forecast and /v2/batch/forecast (request-level default or per-series override — period windows are checked against each series' own horizon); rejected on grouped forecasts; ignored by other endpoints sharing this request shape. 
 * @member {Array.<module:model/AdjustmentsInner>} adjustments
 */
BatchForecastRequest.prototype['adjustments'] = undefined;

/**
 * @member {module:model/AccumulateOptions} accumulate
 */
BatchForecastRequest.prototype['accumulate'] = undefined;





/**
 * Allowed values for the <code>frequency</code> property.
 * @enum {String}
 * @readonly
 */
BatchForecastRequest['FrequencyEnum'] = {

    /**
     * value: "H"
     * @const
     */
    "H": "H",

    /**
     * value: "D"
     * @const
     */
    "D": "D",

    /**
     * value: "W"
     * @const
     */
    "W": "W",

    /**
     * value: "M"
     * @const
     */
    "M": "M",

    /**
     * value: "MS"
     * @const
     */
    "MS": "MS",

    /**
     * value: "ME"
     * @const
     */
    "ME": "ME",

    /**
     * value: "Q"
     * @const
     */
    "Q": "Q",

    /**
     * value: "Y"
     * @const
     */
    "Y": "Y"
};


/**
 * Allowed values for the <code>model</code> property.
 * @enum {String}
 * @readonly
 */
BatchForecastRequest['ModelEnum'] = {

    /**
     * value: "standard"
     * @const
     */
    "standard": "standard",

    /**
     * value: "advanced"
     * @const
     */
    "advanced": "advanced",

    /**
     * value: "advanced-quantized"
     * @const
     */
    "advanced-quantized": "advanced-quantized",

    /**
     * value: "advanced-patched"
     * @const
     */
    "advanced-patched": "advanced-patched",

    /**
     * value: "ensemble"
     * @const
     */
    "ensemble": "ensemble"
};


/**
 * Allowed values for the <code>quantiles</code> property.
 * @enum {Number}
 * @readonly
 */
BatchForecastRequest['QuantilesEnum'] = {

    /**
     * value: 0.1
     * @const
     */
    "0.1": 0.1,

    /**
     * value: 0.2
     * @const
     */
    "0.2": 0.2,

    /**
     * value: 0.3
     * @const
     */
    "0.3": 0.3,

    /**
     * value: 0.4
     * @const
     */
    "0.4": 0.4,

    /**
     * value: 0.5
     * @const
     */
    "0.5": 0.5,

    /**
     * value: 0.6
     * @const
     */
    "0.6": 0.6,

    /**
     * value: 0.7
     * @const
     */
    "0.7": 0.7,

    /**
     * value: 0.8
     * @const
     */
    "0.8": 0.8,

    /**
     * value: 0.9
     * @const
     */
    "0.9": 0.9
};



export default BatchForecastRequest;

