/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AccumulatedForecast from './AccumulatedForecast';
import AdjustedForecast from './AdjustedForecast';
import ForecastPeriod from './ForecastPeriod';

/**
 * The BatchSeriesResult model module.
 * @module model/BatchSeriesResult
 * @version 2.2.0
 */
class BatchSeriesResult {
    /**
     * Constructs a new <code>BatchSeriesResult</code>.
     * One series&#39; results — the same object a single forecast returns under &#x60;result&#x60; (identifier, tenant_context, forecasts, model_info). Unlike single forecasts, &#x60;adjusted&#x60; and &#x60;accumulated&#x60; live INSIDE this object, next to &#x60;forecasts&#x60; — a batch flattens each series into &#x60;results.data[entity_id]&#x60;, so there is no sibling level. For a failed series the object is &#x60;{\&quot;error\&quot;: \&quot;...\&quot;, \&quot;reason\&quot;: \&quot;...\&quot;}&#x60; instead; null while the series is still pending. 
     * @alias module:model/BatchSeriesResult
     * @extends Object
     */
    constructor() { 
        
        BatchSeriesResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BatchSeriesResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BatchSeriesResult} obj Optional instance to populate.
     * @return {module:model/BatchSeriesResult} The populated <code>BatchSeriesResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BatchSeriesResult();

            ApiClient.constructFromObject(data, obj, 'Object');
            

            if (data.hasOwnProperty('identifier')) {
                obj['identifier'] = ApiClient.convertToType(data['identifier'], 'String');
            }
            if (data.hasOwnProperty('tenant_context')) {
                obj['tenant_context'] = ApiClient.convertToType(data['tenant_context'], 'String');
            }
            if (data.hasOwnProperty('forecasts')) {
                obj['forecasts'] = ApiClient.convertToType(data['forecasts'], [ForecastPeriod]);
            }
            if (data.hasOwnProperty('model_info')) {
                obj['model_info'] = ApiClient.convertToType(data['model_info'], {'String': Object});
            }
            if (data.hasOwnProperty('adjusted')) {
                obj['adjusted'] = AdjustedForecast.constructFromObject(data['adjusted']);
            }
            if (data.hasOwnProperty('accumulated')) {
                obj['accumulated'] = AccumulatedForecast.constructFromObject(data['accumulated']);
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BatchSeriesResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BatchSeriesResult</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['identifier'] && !(typeof data['identifier'] === 'string' || data['identifier'] instanceof String)) {
            throw new Error("Expected the field `identifier` to be a primitive type in the JSON string but got " + data['identifier']);
        }
        // ensure the json data is a string
        if (data['tenant_context'] && !(typeof data['tenant_context'] === 'string' || data['tenant_context'] instanceof String)) {
            throw new Error("Expected the field `tenant_context` to be a primitive type in the JSON string but got " + data['tenant_context']);
        }
        if (data['forecasts']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['forecasts'])) {
                throw new Error("Expected the field `forecasts` to be an array in the JSON data but got " + data['forecasts']);
            }
            // validate the optional field `forecasts` (array)
            for (const item of data['forecasts']) {
                ForecastPeriod.validateJSON(item);
            };
        }
        // validate the optional field `adjusted`
        if (data['adjusted']) { // data not null
          AdjustedForecast.validateJSON(data['adjusted']);
        }
        // validate the optional field `accumulated`
        if (data['accumulated']) { // data not null
          AccumulatedForecast.validateJSON(data['accumulated']);
        }
        // ensure the json data is a string
        if (data['error'] && !(typeof data['error'] === 'string' || data['error'] instanceof String)) {
            throw new Error("Expected the field `error` to be a primitive type in the JSON string but got " + data['error']);
        }

        return true;
    }


}



/**
 * @member {String} identifier
 */
BatchSeriesResult.prototype['identifier'] = undefined;

/**
 * @member {String} tenant_context
 */
BatchSeriesResult.prototype['tenant_context'] = undefined;

/**
 * @member {Array.<module:model/ForecastPeriod>} forecasts
 */
BatchSeriesResult.prototype['forecasts'] = undefined;

/**
 * @member {Object.<String, Object>} model_info
 */
BatchSeriesResult.prototype['model_info'] = undefined;

/**
 * @member {module:model/AdjustedForecast} adjusted
 */
BatchSeriesResult.prototype['adjusted'] = undefined;

/**
 * @member {module:model/AccumulatedForecast} accumulated
 */
BatchSeriesResult.prototype['accumulated'] = undefined;

/**
 * Present instead of forecasts when this series failed
 * @member {String} error
 */
BatchSeriesResult.prototype['error'] = undefined;






export default BatchSeriesResult;

