/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BatchForecastAccepted model module.
 * @module model/BatchForecastAccepted
 * @version 2.0.0
 */
class BatchForecastAccepted {
    /**
     * Constructs a new <code>BatchForecastAccepted</code>.
     * @alias module:model/BatchForecastAccepted
     */
    constructor() { 
        
        BatchForecastAccepted.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BatchForecastAccepted</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BatchForecastAccepted} obj Optional instance to populate.
     * @return {module:model/BatchForecastAccepted} The populated <code>BatchForecastAccepted</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BatchForecastAccepted();

            if (data.hasOwnProperty('batch_id')) {
                obj['batch_id'] = ApiClient.convertToType(data['batch_id'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('series_count')) {
                obj['series_count'] = ApiClient.convertToType(data['series_count'], 'Number');
            }
            if (data.hasOwnProperty('time_taken_ms')) {
                obj['time_taken_ms'] = ApiClient.convertToType(data['time_taken_ms'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BatchForecastAccepted</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BatchForecastAccepted</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['batch_id'] && !(typeof data['batch_id'] === 'string' || data['batch_id'] instanceof String)) {
            throw new Error("Expected the field `batch_id` to be a primitive type in the JSON string but got " + data['batch_id']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}



/**
 * Id to poll via GET /v2/batch/forecast/{batch_id}
 * @member {String} batch_id
 */
BatchForecastAccepted.prototype['batch_id'] = undefined;

/**
 * @member {String} status
 */
BatchForecastAccepted.prototype['status'] = undefined;

/**
 * Number of series accepted. Present on inline submissions; a file-based submission counts its series during processing.
 * @member {Number} series_count
 */
BatchForecastAccepted.prototype['series_count'] = undefined;

/**
 * @member {Number} time_taken_ms
 */
BatchForecastAccepted.prototype['time_taken_ms'] = undefined;






export default BatchForecastAccepted;

