/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.2
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ForecastResponseMetaTiming model module.
 * @module model/ForecastResponseMetaTiming
 * @version 2.0.2
 */
class ForecastResponseMetaTiming {
    /**
     * Constructs a new <code>ForecastResponseMetaTiming</code>.
     * @alias module:model/ForecastResponseMetaTiming
     */
    constructor() { 
        
        ForecastResponseMetaTiming.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ForecastResponseMetaTiming</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ForecastResponseMetaTiming} obj Optional instance to populate.
     * @return {module:model/ForecastResponseMetaTiming} The populated <code>ForecastResponseMetaTiming</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ForecastResponseMetaTiming();

            if (data.hasOwnProperty('validation')) {
                obj['validation'] = ApiClient.convertToType(data['validation'], 'Number');
            }
            if (data.hasOwnProperty('selection')) {
                obj['selection'] = ApiClient.convertToType(data['selection'], 'Number');
            }
            if (data.hasOwnProperty('forecasting')) {
                obj['forecasting'] = ApiClient.convertToType(data['forecasting'], 'Number');
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ForecastResponseMetaTiming</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ForecastResponseMetaTiming</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Time taken for validation in milliseconds
 * @member {Number} validation
 */
ForecastResponseMetaTiming.prototype['validation'] = undefined;

/**
 * Time taken for method selection in milliseconds
 * @member {Number} selection
 */
ForecastResponseMetaTiming.prototype['selection'] = undefined;

/**
 * Time taken for forecasting in milliseconds
 * @member {Number} forecasting
 */
ForecastResponseMetaTiming.prototype['forecasting'] = undefined;

/**
 * Total processing time in milliseconds
 * @member {Number} total
 */
ForecastResponseMetaTiming.prototype['total'] = undefined;






export default ForecastResponseMetaTiming;

