/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.3
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AccumulateOptions from './AccumulateOptions';
import AdjustmentsInner from './AdjustmentsInner';
import ForecastRequestDataInner from './ForecastRequestDataInner';
import ValueBounds from './ValueBounds';

/**
 * The ForecastRequest model module.
 * @module model/ForecastRequest
 * @version 2.0.3
 */
class ForecastRequest {
    /**
     * Constructs a new <code>ForecastRequest</code>.
     * @alias module:model/ForecastRequest
     * @param identifier {String} SKU, Product ID, or other identifier for the data series
     * @param frequency {module:model/ForecastRequest.FrequencyEnum} Data frequency: - H: Hourly - D: Daily - W: Weekly - M: Monthly (end of month) - MS: Monthly (start of month) - ME: Monthly (end of month) - Q: Quarterly - Y: Yearly 
     * @param dataType {String} Type of data (e.g., sales, demand, inventory, web_traffic)
     * @param periods {Number} Number of periods to forecast
     * @param data {Array.<module:model/ForecastRequestDataInner>} Historical time series data
     */
    constructor(identifier, frequency, dataType, periods, data) { 
        
        ForecastRequest.initialize(this, identifier, frequency, dataType, periods, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, identifier, frequency, dataType, periods, data) { 
        obj['identifier'] = identifier;
        obj['frequency'] = frequency;
        obj['data_type'] = dataType;
        obj['periods'] = periods;
        obj['model'] = 'standard';
        obj['confidence_level'] = 0.8;
        obj['data'] = data;
    }

    /**
     * Constructs a <code>ForecastRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ForecastRequest} obj Optional instance to populate.
     * @return {module:model/ForecastRequest} The populated <code>ForecastRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ForecastRequest();

            if (data.hasOwnProperty('identifier')) {
                obj['identifier'] = ApiClient.convertToType(data['identifier'], 'String');
            }
            if (data.hasOwnProperty('tenant_context')) {
                obj['tenant_context'] = ApiClient.convertToType(data['tenant_context'], 'String');
            }
            if (data.hasOwnProperty('frequency')) {
                obj['frequency'] = ApiClient.convertToType(data['frequency'], 'String');
            }
            if (data.hasOwnProperty('start_date')) {
                obj['start_date'] = ApiClient.convertToType(data['start_date'], 'Date');
            }
            if (data.hasOwnProperty('data_type')) {
                obj['data_type'] = ApiClient.convertToType(data['data_type'], 'String');
            }
            if (data.hasOwnProperty('periods')) {
                obj['periods'] = ApiClient.convertToType(data['periods'], 'Number');
            }
            if (data.hasOwnProperty('model')) {
                obj['model'] = ApiClient.convertToType(data['model'], 'String');
            }
            if (data.hasOwnProperty('confidence_level')) {
                obj['confidence_level'] = ApiClient.convertToType(data['confidence_level'], 'Number');
            }
            if (data.hasOwnProperty('quantiles')) {
                obj['quantiles'] = ApiClient.convertToType(data['quantiles'], ['Number']);
            }
            if (data.hasOwnProperty('value_bounds')) {
                obj['value_bounds'] = ValueBounds.constructFromObject(data['value_bounds']);
            }
            if (data.hasOwnProperty('adjustments')) {
                obj['adjustments'] = ApiClient.convertToType(data['adjustments'], [AdjustmentsInner]);
            }
            if (data.hasOwnProperty('accumulate')) {
                obj['accumulate'] = AccumulateOptions.constructFromObject(data['accumulate']);
            }
            if (data.hasOwnProperty('selection_metric')) {
                obj['selection_metric'] = ApiClient.convertToType(data['selection_metric'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [ForecastRequestDataInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ForecastRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ForecastRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ForecastRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['identifier'] && !(typeof data['identifier'] === 'string' || data['identifier'] instanceof String)) {
            throw new Error("Expected the field `identifier` to be a primitive type in the JSON string but got " + data['identifier']);
        }
        // ensure the json data is a string
        if (data['tenant_context'] && !(typeof data['tenant_context'] === 'string' || data['tenant_context'] instanceof String)) {
            throw new Error("Expected the field `tenant_context` to be a primitive type in the JSON string but got " + data['tenant_context']);
        }
        // ensure the json data is a string
        if (data['frequency'] && !(typeof data['frequency'] === 'string' || data['frequency'] instanceof String)) {
            throw new Error("Expected the field `frequency` to be a primitive type in the JSON string but got " + data['frequency']);
        }
        // ensure the json data is a string
        if (data['data_type'] && !(typeof data['data_type'] === 'string' || data['data_type'] instanceof String)) {
            throw new Error("Expected the field `data_type` to be a primitive type in the JSON string but got " + data['data_type']);
        }
        // ensure the json data is a string
        if (data['model'] && !(typeof data['model'] === 'string' || data['model'] instanceof String)) {
            throw new Error("Expected the field `model` to be a primitive type in the JSON string but got " + data['model']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['quantiles'])) {
            throw new Error("Expected the field `quantiles` to be an array in the JSON data but got " + data['quantiles']);
        }
        // validate the optional field `value_bounds`
        if (data['value_bounds']) { // data not null
          ValueBounds.validateJSON(data['value_bounds']);
        }
        if (data['adjustments']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['adjustments'])) {
                throw new Error("Expected the field `adjustments` to be an array in the JSON data but got " + data['adjustments']);
            }
            // validate the optional field `adjustments` (array)
            for (const item of data['adjustments']) {
                AdjustmentsInner.validateJSON(item);
            };
        }
        // validate the optional field `accumulate`
        if (data['accumulate']) { // data not null
          AccumulateOptions.validateJSON(data['accumulate']);
        }
        // ensure the json data is a string
        if (data['selection_metric'] && !(typeof data['selection_metric'] === 'string' || data['selection_metric'] instanceof String)) {
            throw new Error("Expected the field `selection_metric` to be a primitive type in the JSON string but got " + data['selection_metric']);
        }
        if (data['data']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['data'])) {
                throw new Error("Expected the field `data` to be an array in the JSON data but got " + data['data']);
            }
            // validate the optional field `data` (array)
            for (const item of data['data']) {
                ForecastRequestDataInner.validateJSON(item);
            };
        }

        return true;
    }


}

ForecastRequest.RequiredProperties = ["identifier", "frequency", "data_type", "periods", "data"];

/**
 * SKU, Product ID, or other identifier for the data series
 * @member {String} identifier
 */
ForecastRequest.prototype['identifier'] = undefined;

/**
 * Optional segmentation dimension. A series is identified by the pair identifier + tenant_context, so \"mrr\" on \"plan-pro\" and \"mrr\" on \"plan-free\" are two independent series, each with its own history and accuracy tracking. Despite the name it isn't only for multi-tenancy — use it for any slice: plan, region, store, channel, cohort, device type. 
 * @member {String} tenant_context
 */
ForecastRequest.prototype['tenant_context'] = undefined;

/**
 * Data frequency: - H: Hourly - D: Daily - W: Weekly - M: Monthly (end of month) - MS: Monthly (start of month) - ME: Monthly (end of month) - Q: Quarterly - Y: Yearly 
 * @member {module:model/ForecastRequest.FrequencyEnum} frequency
 */
ForecastRequest.prototype['frequency'] = undefined;

/**
 * Optional start date for the forecast
 * @member {Date} start_date
 */
ForecastRequest.prototype['start_date'] = undefined;

/**
 * Type of data (e.g., sales, demand, inventory, web_traffic)
 * @member {String} data_type
 */
ForecastRequest.prototype['data_type'] = undefined;

/**
 * Number of periods to forecast
 * @member {Number} periods
 */
ForecastRequest.prototype['periods'] = undefined;

/**
 * Which forecasting engine to use. The advanced variants and ensemble provide higher accuracy at a higher usage cost than standard. 
 * @member {module:model/ForecastRequest.ModelEnum} model
 * @default 'standard'
 */
ForecastRequest.prototype['model'] = 'standard';

/**
 * Confidence level for the prediction interval. Note that 0.80 is the widest band the foundation models (advanced-quantized, advanced-patched, ensemble) produce natively — for genuinely distinct levels beyond that, request a quantile fan via `quantiles` instead of repeating the call at several confidence levels. 
 * @member {Number} confidence_level
 * @default 0.8
 */
ForecastRequest.prototype['confidence_level'] = 0.8;

/**
 * Decile levels to return per period — only deciles between 0.1 and 0.9 are accepted, because those are the levels every backend produces natively; anything finer would be interpolation served under a label the model never predicted. Adds a `quantiles` object to each forecast row alongside the usual bounds. Honoured by /v2/forecast and /v2/batch/forecast (request-level default or per-series override); rejected on grouped forecasts; ignored by other endpoints sharing this request shape. 
 * @member {Array.<module:model/ForecastRequest.QuantilesEnum>} quantiles
 */
ForecastRequest.prototype['quantiles'] = undefined;

/**
 * @member {module:model/ValueBounds} value_bounds
 */
ForecastRequest.prototype['value_bounds'] = undefined;

/**
 * What-if scenario applied on top of the forecast (\"assume we lose the enterprise deal\"). Adjustments compose in array order — ×2 then +50 is not +50 then ×2. Each one moves the point, both bounds and any quantile fan together. Returns an `adjusted` block; the adjusted path is never stored or accuracy-tracked. Honoured by /v2/forecast and /v2/batch/forecast (request-level default or per-series override — period windows are checked against each series' own horizon); rejected on grouped forecasts; ignored by other endpoints sharing this request shape. 
 * @member {Array.<module:model/AdjustmentsInner>} adjustments
 */
ForecastRequest.prototype['adjustments'] = undefined;

/**
 * @member {module:model/AccumulateOptions} accumulate
 */
ForecastRequest.prototype['accumulate'] = undefined;

/**
 * Which back-testing error metric decides the winning model when candidates are compared: - auto: combined for demand/sales/inventory, sMAPE otherwise (default) - combined: 0.6·MASE + 0.4·sMAPE — balances accuracy and trend capture - mase: Mean Absolute Scaled Error — accuracy relative to a naive forecast - smape: Symmetric Mean Absolute Percentage Error 
 * @member {module:model/ForecastRequest.SelectionMetricEnum} selection_metric
 */
ForecastRequest.prototype['selection_metric'] = undefined;

/**
 * Historical time series data
 * @member {Array.<module:model/ForecastRequestDataInner>} data
 */
ForecastRequest.prototype['data'] = undefined;





/**
 * Allowed values for the <code>frequency</code> property.
 * @enum {String}
 * @readonly
 */
ForecastRequest['FrequencyEnum'] = {

    /**
     * value: "H"
     * @const
     */
    "H": "H",

    /**
     * value: "D"
     * @const
     */
    "D": "D",

    /**
     * value: "W"
     * @const
     */
    "W": "W",

    /**
     * value: "M"
     * @const
     */
    "M": "M",

    /**
     * value: "MS"
     * @const
     */
    "MS": "MS",

    /**
     * value: "ME"
     * @const
     */
    "ME": "ME",

    /**
     * value: "Q"
     * @const
     */
    "Q": "Q",

    /**
     * value: "Y"
     * @const
     */
    "Y": "Y"
};


/**
 * Allowed values for the <code>model</code> property.
 * @enum {String}
 * @readonly
 */
ForecastRequest['ModelEnum'] = {

    /**
     * value: "standard"
     * @const
     */
    "standard": "standard",

    /**
     * value: "advanced"
     * @const
     */
    "advanced": "advanced",

    /**
     * value: "advanced-quantized"
     * @const
     */
    "advanced-quantized": "advanced-quantized",

    /**
     * value: "advanced-patched"
     * @const
     */
    "advanced-patched": "advanced-patched",

    /**
     * value: "ensemble"
     * @const
     */
    "ensemble": "ensemble"
};


/**
 * Allowed values for the <code>quantiles</code> property.
 * @enum {Number}
 * @readonly
 */
ForecastRequest['QuantilesEnum'] = {

    /**
     * value: 0.1
     * @const
     */
    "0.1": 0.1,

    /**
     * value: 0.2
     * @const
     */
    "0.2": 0.2,

    /**
     * value: 0.3
     * @const
     */
    "0.3": 0.3,

    /**
     * value: 0.4
     * @const
     */
    "0.4": 0.4,

    /**
     * value: 0.5
     * @const
     */
    "0.5": 0.5,

    /**
     * value: 0.6
     * @const
     */
    "0.6": 0.6,

    /**
     * value: 0.7
     * @const
     */
    "0.7": 0.7,

    /**
     * value: 0.8
     * @const
     */
    "0.8": 0.8,

    /**
     * value: 0.9
     * @const
     */
    "0.9": 0.9
};


/**
 * Allowed values for the <code>selection_metric</code> property.
 * @enum {String}
 * @readonly
 */
ForecastRequest['SelectionMetricEnum'] = {

    /**
     * value: "auto"
     * @const
     */
    "auto": "auto",

    /**
     * value: "combined"
     * @const
     */
    "combined": "combined",

    /**
     * value: "mase"
     * @const
     */
    "mase": "mase",

    /**
     * value: "smape"
     * @const
     */
    "smape": "smape"
};



export default ForecastRequest;

