/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ForecastPeriod from './ForecastPeriod';

/**
 * The ForecastResponseResult model module.
 * @module model/ForecastResponseResult
 * @version 2.1.0
 */
class ForecastResponseResult {
    /**
     * Constructs a new <code>ForecastResponseResult</code>.
     * The baseline forecast — the only path that is stored and accuracy-tracked
     * @alias module:model/ForecastResponseResult
     */
    constructor() { 
        
        ForecastResponseResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ForecastResponseResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ForecastResponseResult} obj Optional instance to populate.
     * @return {module:model/ForecastResponseResult} The populated <code>ForecastResponseResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ForecastResponseResult();

            if (data.hasOwnProperty('identifier')) {
                obj['identifier'] = ApiClient.convertToType(data['identifier'], 'String');
            }
            if (data.hasOwnProperty('tenant_context')) {
                obj['tenant_context'] = ApiClient.convertToType(data['tenant_context'], 'String');
            }
            if (data.hasOwnProperty('forecasts')) {
                obj['forecasts'] = ApiClient.convertToType(data['forecasts'], [ForecastPeriod]);
            }
            if (data.hasOwnProperty('model_info')) {
                obj['model_info'] = ApiClient.convertToType(data['model_info'], {'String': Object});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ForecastResponseResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ForecastResponseResult</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['identifier'] && !(typeof data['identifier'] === 'string' || data['identifier'] instanceof String)) {
            throw new Error("Expected the field `identifier` to be a primitive type in the JSON string but got " + data['identifier']);
        }
        // ensure the json data is a string
        if (data['tenant_context'] && !(typeof data['tenant_context'] === 'string' || data['tenant_context'] instanceof String)) {
            throw new Error("Expected the field `tenant_context` to be a primitive type in the JSON string but got " + data['tenant_context']);
        }
        if (data['forecasts']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['forecasts'])) {
                throw new Error("Expected the field `forecasts` to be an array in the JSON data but got " + data['forecasts']);
            }
            // validate the optional field `forecasts` (array)
            for (const item of data['forecasts']) {
                ForecastPeriod.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Echoes the series identifier from the request
 * @member {String} identifier
 */
ForecastResponseResult.prototype['identifier'] = undefined;

/**
 * @member {String} tenant_context
 */
ForecastResponseResult.prototype['tenant_context'] = undefined;

/**
 * One row per forecast period. Each period carries its own bounds, and they widen with horizon.
 * @member {Array.<module:model/ForecastPeriod>} forecasts
 */
ForecastResponseResult.prototype['forecasts'] = undefined;

/**
 * The selected model (`best_model`), the models evaluated, the interval source, and per-model back-testing scores (smape/mape/mase) when validation runs. Also carries `bounds_transform` when `value_bounds` was sent, and `quantile_levels` when a fan was requested. 
 * @member {Object.<String, Object>} model_info
 */
ForecastResponseResult.prototype['model_info'] = undefined;






export default ForecastResponseResult;

