/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.2
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GroupedForecastNode from './GroupedForecastNode';
import GroupedForecastResultsReconciliation from './GroupedForecastResultsReconciliation';

/**
 * The GroupedForecastResults model module.
 * @module model/GroupedForecastResults
 * @version 2.0.2
 */
class GroupedForecastResults {
    /**
     * Constructs a new <code>GroupedForecastResults</code>.
     * @alias module:model/GroupedForecastResults
     */
    constructor() { 
        
        GroupedForecastResults.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GroupedForecastResults</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GroupedForecastResults} obj Optional instance to populate.
     * @return {module:model/GroupedForecastResults} The populated <code>GroupedForecastResults</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GroupedForecastResults();

            if (data.hasOwnProperty('identifier')) {
                obj['identifier'] = ApiClient.convertToType(data['identifier'], 'String');
            }
            if (data.hasOwnProperty('tenant_context')) {
                obj['tenant_context'] = ApiClient.convertToType(data['tenant_context'], 'String');
            }
            if (data.hasOwnProperty('hierarchy')) {
                obj['hierarchy'] = ApiClient.convertToType(data['hierarchy'], ['String']);
            }
            if (data.hasOwnProperty('reconciliation')) {
                obj['reconciliation'] = GroupedForecastResultsReconciliation.constructFromObject(data['reconciliation']);
            }
            if (data.hasOwnProperty('confidence_level')) {
                obj['confidence_level'] = ApiClient.convertToType(data['confidence_level'], 'Number');
            }
            if (data.hasOwnProperty('node_count')) {
                obj['node_count'] = ApiClient.convertToType(data['node_count'], 'Number');
            }
            if (data.hasOwnProperty('nodes')) {
                obj['nodes'] = ApiClient.convertToType(data['nodes'], {'String': GroupedForecastNode});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GroupedForecastResults</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GroupedForecastResults</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['identifier'] && !(typeof data['identifier'] === 'string' || data['identifier'] instanceof String)) {
            throw new Error("Expected the field `identifier` to be a primitive type in the JSON string but got " + data['identifier']);
        }
        // ensure the json data is a string
        if (data['tenant_context'] && !(typeof data['tenant_context'] === 'string' || data['tenant_context'] instanceof String)) {
            throw new Error("Expected the field `tenant_context` to be a primitive type in the JSON string but got " + data['tenant_context']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['hierarchy'])) {
            throw new Error("Expected the field `hierarchy` to be an array in the JSON data but got " + data['hierarchy']);
        }
        // validate the optional field `reconciliation`
        if (data['reconciliation']) { // data not null
          GroupedForecastResultsReconciliation.validateJSON(data['reconciliation']);
        }

        return true;
    }


}



/**
 * @member {String} identifier
 */
GroupedForecastResults.prototype['identifier'] = undefined;

/**
 * @member {String} tenant_context
 */
GroupedForecastResults.prototype['tenant_context'] = undefined;

/**
 * @member {Array.<String>} hierarchy
 */
GroupedForecastResults.prototype['hierarchy'] = undefined;

/**
 * @member {module:model/GroupedForecastResultsReconciliation} reconciliation
 */
GroupedForecastResults.prototype['reconciliation'] = undefined;

/**
 * @member {Number} confidence_level
 */
GroupedForecastResults.prototype['confidence_level'] = undefined;

/**
 * @member {Number} node_count
 */
GroupedForecastResults.prototype['node_count'] = undefined;

/**
 * Every node of the hierarchy, keyed by segment key: `total` for the root, then e.g. `region=eu` for aggregates and `plan=pro|region=eu` for leaves. Every parent equals the sum of its children in every period. 
 * @member {Object.<String, module:model/GroupedForecastNode>} nodes
 */
GroupedForecastResults.prototype['nodes'] = undefined;






export default GroupedForecastResults;

