/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GroupedForecastResults from './GroupedForecastResults';

/**
 * The GroupedForecastStatusResponse model module.
 * @module model/GroupedForecastStatusResponse
 * @version 2.1.0
 */
class GroupedForecastStatusResponse {
    /**
     * Constructs a new <code>GroupedForecastStatusResponse</code>.
     * @alias module:model/GroupedForecastStatusResponse
     */
    constructor() { 
        
        GroupedForecastStatusResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GroupedForecastStatusResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GroupedForecastStatusResponse} obj Optional instance to populate.
     * @return {module:model/GroupedForecastStatusResponse} The populated <code>GroupedForecastStatusResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GroupedForecastStatusResponse();

            if (data.hasOwnProperty('grouped_forecast_id')) {
                obj['grouped_forecast_id'] = ApiClient.convertToType(data['grouped_forecast_id'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('node_count')) {
                obj['node_count'] = ApiClient.convertToType(data['node_count'], 'Number');
            }
            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], GroupedForecastResults);
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
            if (data.hasOwnProperty('started_at')) {
                obj['started_at'] = ApiClient.convertToType(data['started_at'], 'Date');
            }
            if (data.hasOwnProperty('completed_at')) {
                obj['completed_at'] = ApiClient.convertToType(data['completed_at'], 'Date');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GroupedForecastStatusResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GroupedForecastStatusResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['grouped_forecast_id'] && !(typeof data['grouped_forecast_id'] === 'string' || data['grouped_forecast_id'] instanceof String)) {
            throw new Error("Expected the field `grouped_forecast_id` to be a primitive type in the JSON string but got " + data['grouped_forecast_id']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // validate the optional field `results`
        if (data['results']) { // data not null
          GroupedForecastResults.validateJSON(data['results']);
        }
        // ensure the json data is a string
        if (data['error'] && !(typeof data['error'] === 'string' || data['error'] instanceof String)) {
            throw new Error("Expected the field `error` to be a primitive type in the JSON string but got " + data['error']);
        }

        return true;
    }


}



/**
 * @member {String} grouped_forecast_id
 */
GroupedForecastStatusResponse.prototype['grouped_forecast_id'] = undefined;

/**
 * The run is all-or-nothing — there is no per-node failure state
 * @member {module:model/GroupedForecastStatusResponse.StatusEnum} status
 */
GroupedForecastStatusResponse.prototype['status'] = undefined;

/**
 * @member {Number} node_count
 */
GroupedForecastStatusResponse.prototype['node_count'] = undefined;

/**
 * Populated once status is `completed`; null before that and on failure
 * @member {module:model/GroupedForecastResults} results
 */
GroupedForecastStatusResponse.prototype['results'] = undefined;

/**
 * Failure reason when status is `failed`
 * @member {String} error
 */
GroupedForecastStatusResponse.prototype['error'] = undefined;

/**
 * @member {Date} started_at
 */
GroupedForecastStatusResponse.prototype['started_at'] = undefined;

/**
 * @member {Date} completed_at
 */
GroupedForecastStatusResponse.prototype['completed_at'] = undefined;

/**
 * @member {Date} created_at
 */
GroupedForecastStatusResponse.prototype['created_at'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
GroupedForecastStatusResponse['StatusEnum'] = {

    /**
     * value: "pending"
     * @const
     */
    "pending": "pending",

    /**
     * value: "processing"
     * @const
     */
    "processing": "processing",

    /**
     * value: "completed"
     * @const
     */
    "completed": "completed",

    /**
     * value: "failed"
     * @const
     */
    "failed": "failed"
};



export default GroupedForecastStatusResponse;

