/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GroupedForecastSeriesDataInner from './GroupedForecastSeriesDataInner';

/**
 * The GroupedForecastSeries model module.
 * @module model/GroupedForecastSeries
 * @version 2.1.0
 */
class GroupedForecastSeries {
    /**
     * Constructs a new <code>GroupedForecastSeries</code>.
     * @alias module:model/GroupedForecastSeries
     * @param segment {Object.<String, Object>} Names exactly the declared hierarchy dimensions — no more, no fewer. Values are non-empty scalars of at most 128 characters. 
     * @param data {Array.<module:model/GroupedForecastSeriesDataInner>} Historical data for this leaf (at most 1,000 points per series on the free tier)
     */
    constructor(segment, data) { 
        
        GroupedForecastSeries.initialize(this, segment, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, segment, data) { 
        obj['segment'] = segment;
        obj['data'] = data;
    }

    /**
     * Constructs a <code>GroupedForecastSeries</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GroupedForecastSeries} obj Optional instance to populate.
     * @return {module:model/GroupedForecastSeries} The populated <code>GroupedForecastSeries</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GroupedForecastSeries();

            if (data.hasOwnProperty('segment')) {
                obj['segment'] = ApiClient.convertToType(data['segment'], {'String': Object});
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [GroupedForecastSeriesDataInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GroupedForecastSeries</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GroupedForecastSeries</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GroupedForecastSeries.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['data']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['data'])) {
                throw new Error("Expected the field `data` to be an array in the JSON data but got " + data['data']);
            }
            // validate the optional field `data` (array)
            for (const item of data['data']) {
                GroupedForecastSeriesDataInner.validateJSON(item);
            };
        }

        return true;
    }


}

GroupedForecastSeries.RequiredProperties = ["segment", "data"];

/**
 * Names exactly the declared hierarchy dimensions — no more, no fewer. Values are non-empty scalars of at most 128 characters. 
 * @member {Object.<String, Object>} segment
 */
GroupedForecastSeries.prototype['segment'] = undefined;

/**
 * Historical data for this leaf (at most 1,000 points per series on the free tier)
 * @member {Array.<module:model/GroupedForecastSeriesDataInner>} data
 */
GroupedForecastSeries.prototype['data'] = undefined;






export default GroupedForecastSeries;

