/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.3
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InventoryPlanningRequestInventorySettingsSuppliersInner from './InventoryPlanningRequestInventorySettingsSuppliersInner';

/**
 * The InventoryPlanningRequestInventorySettings model module.
 * @module model/InventoryPlanningRequestInventorySettings
 * @version 2.0.3
 */
class InventoryPlanningRequestInventorySettings {
    /**
     * Constructs a new <code>InventoryPlanningRequestInventorySettings</code>.
     * Current inventory status and supplier information
     * @alias module:model/InventoryPlanningRequestInventorySettings
     * @param currentStock {Number} Current quantity in stock
     * @param minimumStock {Number} Minimum stock level to maintain
     * @param serviceLevel {Number} Target service level (probability of not stocking out)
     * @param suppliers {Array.<module:model/InventoryPlanningRequestInventorySettingsSuppliersInner>} Available suppliers with their characteristics
     */
    constructor(currentStock, minimumStock, serviceLevel, suppliers) { 
        
        InventoryPlanningRequestInventorySettings.initialize(this, currentStock, minimumStock, serviceLevel, suppliers);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, currentStock, minimumStock, serviceLevel, suppliers) { 
        obj['current_stock'] = currentStock;
        obj['minimum_stock'] = minimumStock;
        obj['service_level'] = serviceLevel;
        obj['suppliers'] = suppliers;
    }

    /**
     * Constructs a <code>InventoryPlanningRequestInventorySettings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InventoryPlanningRequestInventorySettings} obj Optional instance to populate.
     * @return {module:model/InventoryPlanningRequestInventorySettings} The populated <code>InventoryPlanningRequestInventorySettings</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InventoryPlanningRequestInventorySettings();

            if (data.hasOwnProperty('current_stock')) {
                obj['current_stock'] = ApiClient.convertToType(data['current_stock'], 'Number');
            }
            if (data.hasOwnProperty('minimum_stock')) {
                obj['minimum_stock'] = ApiClient.convertToType(data['minimum_stock'], 'Number');
            }
            if (data.hasOwnProperty('service_level')) {
                obj['service_level'] = ApiClient.convertToType(data['service_level'], 'Number');
            }
            if (data.hasOwnProperty('suppliers')) {
                obj['suppliers'] = ApiClient.convertToType(data['suppliers'], [InventoryPlanningRequestInventorySettingsSuppliersInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InventoryPlanningRequestInventorySettings</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InventoryPlanningRequestInventorySettings</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of InventoryPlanningRequestInventorySettings.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['suppliers']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['suppliers'])) {
                throw new Error("Expected the field `suppliers` to be an array in the JSON data but got " + data['suppliers']);
            }
            // validate the optional field `suppliers` (array)
            for (const item of data['suppliers']) {
                InventoryPlanningRequestInventorySettingsSuppliersInner.validateJSON(item);
            };
        }

        return true;
    }


}

InventoryPlanningRequestInventorySettings.RequiredProperties = ["current_stock", "minimum_stock", "service_level", "suppliers"];

/**
 * Current quantity in stock
 * @member {Number} current_stock
 */
InventoryPlanningRequestInventorySettings.prototype['current_stock'] = undefined;

/**
 * Minimum stock level to maintain
 * @member {Number} minimum_stock
 */
InventoryPlanningRequestInventorySettings.prototype['minimum_stock'] = undefined;

/**
 * Target service level (probability of not stocking out)
 * @member {Number} service_level
 */
InventoryPlanningRequestInventorySettings.prototype['service_level'] = undefined;

/**
 * Available suppliers with their characteristics
 * @member {Array.<module:model/InventoryPlanningRequestInventorySettingsSuppliersInner>} suppliers
 */
InventoryPlanningRequestInventorySettings.prototype['suppliers'] = undefined;






export default InventoryPlanningRequestInventorySettings;

