/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.4
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InventoryPlanningResponseResultSuppliersInner model module.
 * @module model/InventoryPlanningResponseResultSuppliersInner
 * @version 2.0.4
 */
class InventoryPlanningResponseResultSuppliersInner {
    /**
     * Constructs a new <code>InventoryPlanningResponseResultSuppliersInner</code>.
     * @alias module:model/InventoryPlanningResponseResultSuppliersInner
     */
    constructor() { 
        
        InventoryPlanningResponseResultSuppliersInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InventoryPlanningResponseResultSuppliersInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InventoryPlanningResponseResultSuppliersInner} obj Optional instance to populate.
     * @return {module:model/InventoryPlanningResponseResultSuppliersInner} The populated <code>InventoryPlanningResponseResultSuppliersInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InventoryPlanningResponseResultSuppliersInner();

            if (data.hasOwnProperty('supplier')) {
                obj['supplier'] = ApiClient.convertToType(data['supplier'], 'String');
            }
            if (data.hasOwnProperty('order_quantity')) {
                obj['order_quantity'] = ApiClient.convertToType(data['order_quantity'], 'Number');
            }
            if (data.hasOwnProperty('total_cost')) {
                obj['total_cost'] = ApiClient.convertToType(data['total_cost'], 'Number');
            }
            if (data.hasOwnProperty('cost_per_unit')) {
                obj['cost_per_unit'] = ApiClient.convertToType(data['cost_per_unit'], 'Number');
            }
            if (data.hasOwnProperty('expected_delivery')) {
                obj['expected_delivery'] = ApiClient.convertToType(data['expected_delivery'], 'Date');
            }
            if (data.hasOwnProperty('lead_time_days')) {
                obj['lead_time_days'] = ApiClient.convertToType(data['lead_time_days'], 'Number');
            }
            if (data.hasOwnProperty('minimum_order_quantity')) {
                obj['minimum_order_quantity'] = ApiClient.convertToType(data['minimum_order_quantity'], 'Number');
            }
            if (data.hasOwnProperty('reliability_score')) {
                obj['reliability_score'] = ApiClient.convertToType(data['reliability_score'], 'Number');
            }
            if (data.hasOwnProperty('lead_time_demand')) {
                obj['lead_time_demand'] = ApiClient.convertToType(data['lead_time_demand'], 'Number');
            }
            if (data.hasOwnProperty('safety_stock')) {
                obj['safety_stock'] = ApiClient.convertToType(data['safety_stock'], 'Number');
            }
            if (data.hasOwnProperty('reorder_point')) {
                obj['reorder_point'] = ApiClient.convertToType(data['reorder_point'], 'Number');
            }
            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InventoryPlanningResponseResultSuppliersInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InventoryPlanningResponseResultSuppliersInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['supplier'] && !(typeof data['supplier'] === 'string' || data['supplier'] instanceof String)) {
            throw new Error("Expected the field `supplier` to be a primitive type in the JSON string but got " + data['supplier']);
        }
        // ensure the json data is a string
        if (data['reason'] && !(typeof data['reason'] === 'string' || data['reason'] instanceof String)) {
            throw new Error("Expected the field `reason` to be a primitive type in the JSON string but got " + data['reason']);
        }

        return true;
    }


}



/**
 * Supplier identifier
 * @member {String} supplier
 */
InventoryPlanningResponseResultSuppliersInner.prototype['supplier'] = undefined;

/**
 * Recommended order quantity
 * @member {Number} order_quantity
 */
InventoryPlanningResponseResultSuppliersInner.prototype['order_quantity'] = undefined;

/**
 * Total cost for the recommended order
 * @member {Number} total_cost
 */
InventoryPlanningResponseResultSuppliersInner.prototype['total_cost'] = undefined;

/**
 * Cost per unit from this supplier
 * @member {Number} cost_per_unit
 */
InventoryPlanningResponseResultSuppliersInner.prototype['cost_per_unit'] = undefined;

/**
 * Expected delivery date
 * @member {Date} expected_delivery
 */
InventoryPlanningResponseResultSuppliersInner.prototype['expected_delivery'] = undefined;

/**
 * Lead time in days
 * @member {Number} lead_time_days
 */
InventoryPlanningResponseResultSuppliersInner.prototype['lead_time_days'] = undefined;

/**
 * Minimum order quantity
 * @member {Number} minimum_order_quantity
 */
InventoryPlanningResponseResultSuppliersInner.prototype['minimum_order_quantity'] = undefined;

/**
 * Supplier reliability score
 * @member {Number} reliability_score
 */
InventoryPlanningResponseResultSuppliersInner.prototype['reliability_score'] = undefined;

/**
 * Expected demand during lead time
 * @member {Number} lead_time_demand
 */
InventoryPlanningResponseResultSuppliersInner.prototype['lead_time_demand'] = undefined;

/**
 * Calculated safety stock for this supplier
 * @member {Number} safety_stock
 */
InventoryPlanningResponseResultSuppliersInner.prototype['safety_stock'] = undefined;

/**
 * Calculated reorder point for this supplier
 * @member {Number} reorder_point
 */
InventoryPlanningResponseResultSuppliersInner.prototype['reorder_point'] = undefined;

/**
 * Explanation for the recommendation
 * @member {String} reason
 */
InventoryPlanningResponseResultSuppliersInner.prototype['reason'] = undefined;






export default InventoryPlanningResponseResultSuppliersInner;

