/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProductInsightsRequestSalesInner model module.
 * @module model/ProductInsightsRequestSalesInner
 * @version 2.0.0
 */
class ProductInsightsRequestSalesInner {
    /**
     * Constructs a new <code>ProductInsightsRequestSalesInner</code>.
     * @alias module:model/ProductInsightsRequestSalesInner
     * @param date {String} 
     * @param quantitySold {Number} 
     * @param sellingPrice {Number} 
     */
    constructor(date, quantitySold, sellingPrice) { 
        
        ProductInsightsRequestSalesInner.initialize(this, date, quantitySold, sellingPrice);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, date, quantitySold, sellingPrice) { 
        obj['date'] = date;
        obj['quantity_sold'] = quantitySold;
        obj['selling_price'] = sellingPrice;
    }

    /**
     * Constructs a <code>ProductInsightsRequestSalesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductInsightsRequestSalesInner} obj Optional instance to populate.
     * @return {module:model/ProductInsightsRequestSalesInner} The populated <code>ProductInsightsRequestSalesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductInsightsRequestSalesInner();

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('quantity_sold')) {
                obj['quantity_sold'] = ApiClient.convertToType(data['quantity_sold'], 'Number');
            }
            if (data.hasOwnProperty('selling_price')) {
                obj['selling_price'] = ApiClient.convertToType(data['selling_price'], 'Number');
            }
            if (data.hasOwnProperty('selling_price_converted')) {
                obj['selling_price_converted'] = ApiClient.convertToType(data['selling_price_converted'], 'Number');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('customer_id')) {
                obj['customer_id'] = ApiClient.convertToType(data['customer_id'], 'String');
            }
            if (data.hasOwnProperty('customer_segment')) {
                obj['customer_segment'] = ApiClient.convertToType(data['customer_segment'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductInsightsRequestSalesInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductInsightsRequestSalesInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ProductInsightsRequestSalesInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['date'] && !(typeof data['date'] === 'string' || data['date'] instanceof String)) {
            throw new Error("Expected the field `date` to be a primitive type in the JSON string but got " + data['date']);
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }
        // ensure the json data is a string
        if (data['customer_id'] && !(typeof data['customer_id'] === 'string' || data['customer_id'] instanceof String)) {
            throw new Error("Expected the field `customer_id` to be a primitive type in the JSON string but got " + data['customer_id']);
        }
        // ensure the json data is a string
        if (data['customer_segment'] && !(typeof data['customer_segment'] === 'string' || data['customer_segment'] instanceof String)) {
            throw new Error("Expected the field `customer_segment` to be a primitive type in the JSON string but got " + data['customer_segment']);
        }

        return true;
    }


}

ProductInsightsRequestSalesInner.RequiredProperties = ["date", "quantity_sold", "selling_price"];

/**
 * @member {String} date
 */
ProductInsightsRequestSalesInner.prototype['date'] = undefined;

/**
 * @member {Number} quantity_sold
 */
ProductInsightsRequestSalesInner.prototype['quantity_sold'] = undefined;

/**
 * @member {Number} selling_price
 */
ProductInsightsRequestSalesInner.prototype['selling_price'] = undefined;

/**
 * Price converted to base_currency, when the sale was in another currency
 * @member {Number} selling_price_converted
 */
ProductInsightsRequestSalesInner.prototype['selling_price_converted'] = undefined;

/**
 * @member {String} currency
 */
ProductInsightsRequestSalesInner.prototype['currency'] = undefined;

/**
 * @member {String} customer_id
 */
ProductInsightsRequestSalesInner.prototype['customer_id'] = undefined;

/**
 * @member {String} customer_segment
 */
ProductInsightsRequestSalesInner.prototype['customer_segment'] = undefined;






export default ProductInsightsRequestSalesInner;

