/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.4
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProductInsightsResponseMetaDataQuality from './ProductInsightsResponseMetaDataQuality';
import ProductInsightsResponseMetaTiming from './ProductInsightsResponseMetaTiming';

/**
 * The ProductInsightsResponseMeta model module.
 * @module model/ProductInsightsResponseMeta
 * @version 2.0.4
 */
class ProductInsightsResponseMeta {
    /**
     * Constructs a new <code>ProductInsightsResponseMeta</code>.
     * @alias module:model/ProductInsightsResponseMeta
     */
    constructor() { 
        
        ProductInsightsResponseMeta.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductInsightsResponseMeta</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductInsightsResponseMeta} obj Optional instance to populate.
     * @return {module:model/ProductInsightsResponseMeta} The populated <code>ProductInsightsResponseMeta</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductInsightsResponseMeta();

            if (data.hasOwnProperty('timing')) {
                obj['timing'] = ProductInsightsResponseMetaTiming.constructFromObject(data['timing']);
            }
            if (data.hasOwnProperty('data_quality')) {
                obj['data_quality'] = ProductInsightsResponseMetaDataQuality.constructFromObject(data['data_quality']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductInsightsResponseMeta</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductInsightsResponseMeta</code>.
     */
    static validateJSON(data) {
        // validate the optional field `timing`
        if (data['timing']) { // data not null
          ProductInsightsResponseMetaTiming.validateJSON(data['timing']);
        }
        // validate the optional field `data_quality`
        if (data['data_quality']) { // data not null
          ProductInsightsResponseMetaDataQuality.validateJSON(data['data_quality']);
        }

        return true;
    }


}



/**
 * @member {module:model/ProductInsightsResponseMetaTiming} timing
 */
ProductInsightsResponseMeta.prototype['timing'] = undefined;

/**
 * @member {module:model/ProductInsightsResponseMetaDataQuality} data_quality
 */
ProductInsightsResponseMeta.prototype['data_quality'] = undefined;






export default ProductInsightsResponseMeta;

