/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.4
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProductInsight from './ProductInsight';
import ProductInsightsResponseResultComparison from './ProductInsightsResponseResultComparison';
import ProductInsightsResponseResultProductInfo from './ProductInsightsResponseResultProductInfo';
import ProductInsightsResponseResultSummary from './ProductInsightsResponseResultSummary';

/**
 * The ProductInsightsResponseResult model module.
 * @module model/ProductInsightsResponseResult
 * @version 2.0.4
 */
class ProductInsightsResponseResult {
    /**
     * Constructs a new <code>ProductInsightsResponseResult</code>.
     * @alias module:model/ProductInsightsResponseResult
     */
    constructor() { 
        
        ProductInsightsResponseResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductInsightsResponseResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductInsightsResponseResult} obj Optional instance to populate.
     * @return {module:model/ProductInsightsResponseResult} The populated <code>ProductInsightsResponseResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductInsightsResponseResult();

            if (data.hasOwnProperty('identifier')) {
                obj['identifier'] = ApiClient.convertToType(data['identifier'], 'String');
            }
            if (data.hasOwnProperty('tenant_context')) {
                obj['tenant_context'] = ApiClient.convertToType(data['tenant_context'], 'String');
            }
            if (data.hasOwnProperty('product_info')) {
                obj['product_info'] = ProductInsightsResponseResultProductInfo.constructFromObject(data['product_info']);
            }
            if (data.hasOwnProperty('base_currency')) {
                obj['base_currency'] = ApiClient.convertToType(data['base_currency'], 'String');
            }
            if (data.hasOwnProperty('insights')) {
                obj['insights'] = ApiClient.convertToType(data['insights'], [ProductInsight]);
            }
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = ProductInsightsResponseResultSummary.constructFromObject(data['summary']);
            }
            if (data.hasOwnProperty('comparison')) {
                obj['comparison'] = ProductInsightsResponseResultComparison.constructFromObject(data['comparison']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductInsightsResponseResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductInsightsResponseResult</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['identifier'] && !(typeof data['identifier'] === 'string' || data['identifier'] instanceof String)) {
            throw new Error("Expected the field `identifier` to be a primitive type in the JSON string but got " + data['identifier']);
        }
        // ensure the json data is a string
        if (data['tenant_context'] && !(typeof data['tenant_context'] === 'string' || data['tenant_context'] instanceof String)) {
            throw new Error("Expected the field `tenant_context` to be a primitive type in the JSON string but got " + data['tenant_context']);
        }
        // validate the optional field `product_info`
        if (data['product_info']) { // data not null
          ProductInsightsResponseResultProductInfo.validateJSON(data['product_info']);
        }
        // ensure the json data is a string
        if (data['base_currency'] && !(typeof data['base_currency'] === 'string' || data['base_currency'] instanceof String)) {
            throw new Error("Expected the field `base_currency` to be a primitive type in the JSON string but got " + data['base_currency']);
        }
        if (data['insights']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['insights'])) {
                throw new Error("Expected the field `insights` to be an array in the JSON data but got " + data['insights']);
            }
            // validate the optional field `insights` (array)
            for (const item of data['insights']) {
                ProductInsight.validateJSON(item);
            };
        }
        // validate the optional field `summary`
        if (data['summary']) { // data not null
          ProductInsightsResponseResultSummary.validateJSON(data['summary']);
        }
        // validate the optional field `comparison`
        if (data['comparison']) { // data not null
          ProductInsightsResponseResultComparison.validateJSON(data['comparison']);
        }

        return true;
    }


}



/**
 * @member {String} identifier
 */
ProductInsightsResponseResult.prototype['identifier'] = undefined;

/**
 * @member {String} tenant_context
 */
ProductInsightsResponseResult.prototype['tenant_context'] = undefined;

/**
 * @member {module:model/ProductInsightsResponseResultProductInfo} product_info
 */
ProductInsightsResponseResult.prototype['product_info'] = undefined;

/**
 * @member {String} base_currency
 */
ProductInsightsResponseResult.prototype['base_currency'] = undefined;

/**
 * @member {Array.<module:model/ProductInsight>} insights
 */
ProductInsightsResponseResult.prototype['insights'] = undefined;

/**
 * @member {module:model/ProductInsightsResponseResultSummary} summary
 */
ProductInsightsResponseResult.prototype['summary'] = undefined;

/**
 * @member {module:model/ProductInsightsResponseResultComparison} comparison
 */
ProductInsightsResponseResult.prototype['comparison'] = undefined;






export default ProductInsightsResponseResult;

