/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProductInsightRecommendation from './ProductInsightRecommendation';

/**
 * The ProductInsight model module.
 * @module model/ProductInsight
 * @version 2.1.0
 */
class ProductInsight {
    /**
     * Constructs a new <code>ProductInsight</code>.
     * @alias module:model/ProductInsight
     */
    constructor() { 
        
        ProductInsight.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductInsight</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductInsight} obj Optional instance to populate.
     * @return {module:model/ProductInsight} The populated <code>ProductInsight</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductInsight();

            if (data.hasOwnProperty('class')) {
                obj['class'] = ApiClient.convertToType(data['class'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('severity')) {
                obj['severity'] = ApiClient.convertToType(data['severity'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('metrics')) {
                obj['metrics'] = ApiClient.convertToType(data['metrics'], {'String': Object});
            }
            if (data.hasOwnProperty('recommendation')) {
                obj['recommendation'] = ProductInsightRecommendation.constructFromObject(data['recommendation']);
            }
            if (data.hasOwnProperty('confidence')) {
                obj['confidence'] = ApiClient.convertToType(data['confidence'], 'String');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('change_status')) {
                obj['change_status'] = ApiClient.convertToType(data['change_status'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductInsight</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductInsight</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['class'] && !(typeof data['class'] === 'string' || data['class'] instanceof String)) {
            throw new Error("Expected the field `class` to be a primitive type in the JSON string but got " + data['class']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['severity'] && !(typeof data['severity'] === 'string' || data['severity'] instanceof String)) {
            throw new Error("Expected the field `severity` to be a primitive type in the JSON string but got " + data['severity']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // validate the optional field `recommendation`
        if (data['recommendation']) { // data not null
          ProductInsightRecommendation.validateJSON(data['recommendation']);
        }
        // ensure the json data is a string
        if (data['confidence'] && !(typeof data['confidence'] === 'string' || data['confidence'] instanceof String)) {
            throw new Error("Expected the field `confidence` to be a primitive type in the JSON string but got " + data['confidence']);
        }
        // ensure the json data is a string
        if (data['date'] && !(typeof data['date'] === 'string' || data['date'] instanceof String)) {
            throw new Error("Expected the field `date` to be a primitive type in the JSON string but got " + data['date']);
        }
        // ensure the json data is a string
        if (data['change_status'] && !(typeof data['change_status'] === 'string' || data['change_status'] instanceof String)) {
            throw new Error("Expected the field `change_status` to be a primitive type in the JSON string but got " + data['change_status']);
        }

        return true;
    }


}



/**
 * Insight family (e.g. margin, sales, cost, lead_time)
 * @member {String} class
 */
ProductInsight.prototype['class'] = undefined;

/**
 * @member {String} type
 */
ProductInsight.prototype['type'] = undefined;

/**
 * @member {module:model/ProductInsight.SeverityEnum} severity
 */
ProductInsight.prototype['severity'] = undefined;

/**
 * @member {String} title
 */
ProductInsight.prototype['title'] = undefined;

/**
 * @member {String} description
 */
ProductInsight.prototype['description'] = undefined;

/**
 * The numbers behind the insight
 * @member {Object.<String, Object>} metrics
 */
ProductInsight.prototype['metrics'] = undefined;

/**
 * @member {module:model/ProductInsightRecommendation} recommendation
 */
ProductInsight.prototype['recommendation'] = undefined;

/**
 * @member {String} confidence
 */
ProductInsight.prototype['confidence'] = undefined;

/**
 * @member {String} date
 */
ProductInsight.prototype['date'] = undefined;

/**
 * How this insight compares to the previous analysis of the same product — every insight is \"new\" on the first analysis
 * @member {String} change_status
 */
ProductInsight.prototype['change_status'] = undefined;





/**
 * Allowed values for the <code>severity</code> property.
 * @enum {String}
 * @readonly
 */
ProductInsight['SeverityEnum'] = {

    /**
     * value: "critical"
     * @const
     */
    "critical": "critical",

    /**
     * value: "warning"
     * @const
     */
    "warning": "warning",

    /**
     * value: "info"
     * @const
     */
    "info": "info"
};



export default ProductInsight;

