/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProductInsightsRequestCostHistoryInner model module.
 * @module model/ProductInsightsRequestCostHistoryInner
 * @version 2.2.0
 */
class ProductInsightsRequestCostHistoryInner {
    /**
     * Constructs a new <code>ProductInsightsRequestCostHistoryInner</code>.
     * @alias module:model/ProductInsightsRequestCostHistoryInner
     * @param date {String} 
     * @param costPrice {Number} 
     */
    constructor(date, costPrice) { 
        
        ProductInsightsRequestCostHistoryInner.initialize(this, date, costPrice);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, date, costPrice) { 
        obj['date'] = date;
        obj['cost_price'] = costPrice;
    }

    /**
     * Constructs a <code>ProductInsightsRequestCostHistoryInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductInsightsRequestCostHistoryInner} obj Optional instance to populate.
     * @return {module:model/ProductInsightsRequestCostHistoryInner} The populated <code>ProductInsightsRequestCostHistoryInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductInsightsRequestCostHistoryInner();

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('cost_price')) {
                obj['cost_price'] = ApiClient.convertToType(data['cost_price'], 'Number');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('change_reason')) {
                obj['change_reason'] = ApiClient.convertToType(data['change_reason'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductInsightsRequestCostHistoryInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductInsightsRequestCostHistoryInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ProductInsightsRequestCostHistoryInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['date'] && !(typeof data['date'] === 'string' || data['date'] instanceof String)) {
            throw new Error("Expected the field `date` to be a primitive type in the JSON string but got " + data['date']);
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }
        // ensure the json data is a string
        if (data['change_reason'] && !(typeof data['change_reason'] === 'string' || data['change_reason'] instanceof String)) {
            throw new Error("Expected the field `change_reason` to be a primitive type in the JSON string but got " + data['change_reason']);
        }

        return true;
    }


}

ProductInsightsRequestCostHistoryInner.RequiredProperties = ["date", "cost_price"];

/**
 * @member {String} date
 */
ProductInsightsRequestCostHistoryInner.prototype['date'] = undefined;

/**
 * @member {Number} cost_price
 */
ProductInsightsRequestCostHistoryInner.prototype['cost_price'] = undefined;

/**
 * @member {String} currency
 */
ProductInsightsRequestCostHistoryInner.prototype['currency'] = undefined;

/**
 * @member {String} change_reason
 */
ProductInsightsRequestCostHistoryInner.prototype['change_reason'] = undefined;






export default ProductInsightsRequestCostHistoryInner;

