/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProductInsightsRequestInsightSettings model module.
 * @module model/ProductInsightsRequestInsightSettings
 * @version 2.1.0
 */
class ProductInsightsRequestInsightSettings {
    /**
     * Constructs a new <code>ProductInsightsRequestInsightSettings</code>.
     * Sensitivity tuning for the individual insight detectors
     * @alias module:model/ProductInsightsRequestInsightSettings
     */
    constructor() { 
        
        ProductInsightsRequestInsightSettings.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductInsightsRequestInsightSettings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductInsightsRequestInsightSettings} obj Optional instance to populate.
     * @return {module:model/ProductInsightsRequestInsightSettings} The populated <code>ProductInsightsRequestInsightSettings</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductInsightsRequestInsightSettings();

            if (data.hasOwnProperty('sales_threshold')) {
                obj['sales_threshold'] = ApiClient.convertToType(data['sales_threshold'], 'Number');
            }
            if (data.hasOwnProperty('margin_threshold')) {
                obj['margin_threshold'] = ApiClient.convertToType(data['margin_threshold'], 'Number');
            }
            if (data.hasOwnProperty('cost_threshold')) {
                obj['cost_threshold'] = ApiClient.convertToType(data['cost_threshold'], 'Number');
            }
            if (data.hasOwnProperty('purchase_threshold')) {
                obj['purchase_threshold'] = ApiClient.convertToType(data['purchase_threshold'], 'Number');
            }
            if (data.hasOwnProperty('enable_seasonality_detection')) {
                obj['enable_seasonality_detection'] = ApiClient.convertToType(data['enable_seasonality_detection'], 'Boolean');
            }
            if (data.hasOwnProperty('severity_levels')) {
                obj['severity_levels'] = ApiClient.convertToType(data['severity_levels'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductInsightsRequestInsightSettings</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductInsightsRequestInsightSettings</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['severity_levels'])) {
            throw new Error("Expected the field `severity_levels` to be an array in the JSON data but got " + data['severity_levels']);
        }

        return true;
    }


}



/**
 * @member {Number} sales_threshold
 */
ProductInsightsRequestInsightSettings.prototype['sales_threshold'] = undefined;

/**
 * @member {Number} margin_threshold
 */
ProductInsightsRequestInsightSettings.prototype['margin_threshold'] = undefined;

/**
 * @member {Number} cost_threshold
 */
ProductInsightsRequestInsightSettings.prototype['cost_threshold'] = undefined;

/**
 * @member {Number} purchase_threshold
 */
ProductInsightsRequestInsightSettings.prototype['purchase_threshold'] = undefined;

/**
 * @member {Boolean} enable_seasonality_detection
 */
ProductInsightsRequestInsightSettings.prototype['enable_seasonality_detection'] = undefined;

/**
 * Only emit insights at these severities
 * @member {Array.<module:model/ProductInsightsRequestInsightSettings.SeverityLevelsEnum>} severity_levels
 */
ProductInsightsRequestInsightSettings.prototype['severity_levels'] = undefined;





/**
 * Allowed values for the <code>severityLevels</code> property.
 * @enum {String}
 * @readonly
 */
ProductInsightsRequestInsightSettings['SeverityLevelsEnum'] = {

    /**
     * value: "critical"
     * @const
     */
    "critical": "critical",

    /**
     * value: "warning"
     * @const
     */
    "warning": "warning",

    /**
     * value: "info"
     * @const
     */
    "info": "info"
};



export default ProductInsightsRequestInsightSettings;

