/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.4
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProductInsightsRequestPurchasesInner model module.
 * @module model/ProductInsightsRequestPurchasesInner
 * @version 2.0.4
 */
class ProductInsightsRequestPurchasesInner {
    /**
     * Constructs a new <code>ProductInsightsRequestPurchasesInner</code>.
     * @alias module:model/ProductInsightsRequestPurchasesInner
     * @param date {String} 
     * @param quantityPurchased {Number} 
     * @param costPrice {Number} 
     */
    constructor(date, quantityPurchased, costPrice) { 
        
        ProductInsightsRequestPurchasesInner.initialize(this, date, quantityPurchased, costPrice);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, date, quantityPurchased, costPrice) { 
        obj['date'] = date;
        obj['quantity_purchased'] = quantityPurchased;
        obj['cost_price'] = costPrice;
    }

    /**
     * Constructs a <code>ProductInsightsRequestPurchasesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductInsightsRequestPurchasesInner} obj Optional instance to populate.
     * @return {module:model/ProductInsightsRequestPurchasesInner} The populated <code>ProductInsightsRequestPurchasesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductInsightsRequestPurchasesInner();

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('quantity_purchased')) {
                obj['quantity_purchased'] = ApiClient.convertToType(data['quantity_purchased'], 'Number');
            }
            if (data.hasOwnProperty('cost_price')) {
                obj['cost_price'] = ApiClient.convertToType(data['cost_price'], 'Number');
            }
            if (data.hasOwnProperty('cost_price_converted')) {
                obj['cost_price_converted'] = ApiClient.convertToType(data['cost_price_converted'], 'Number');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('supplier_id')) {
                obj['supplier_id'] = ApiClient.convertToType(data['supplier_id'], 'String');
            }
            if (data.hasOwnProperty('purchase_order_date')) {
                obj['purchase_order_date'] = ApiClient.convertToType(data['purchase_order_date'], 'Date');
            }
            if (data.hasOwnProperty('expected_delivery_date')) {
                obj['expected_delivery_date'] = ApiClient.convertToType(data['expected_delivery_date'], 'Date');
            }
            if (data.hasOwnProperty('actual_delivery_date')) {
                obj['actual_delivery_date'] = ApiClient.convertToType(data['actual_delivery_date'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductInsightsRequestPurchasesInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductInsightsRequestPurchasesInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ProductInsightsRequestPurchasesInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['date'] && !(typeof data['date'] === 'string' || data['date'] instanceof String)) {
            throw new Error("Expected the field `date` to be a primitive type in the JSON string but got " + data['date']);
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }
        // ensure the json data is a string
        if (data['supplier_id'] && !(typeof data['supplier_id'] === 'string' || data['supplier_id'] instanceof String)) {
            throw new Error("Expected the field `supplier_id` to be a primitive type in the JSON string but got " + data['supplier_id']);
        }

        return true;
    }


}

ProductInsightsRequestPurchasesInner.RequiredProperties = ["date", "quantity_purchased", "cost_price"];

/**
 * @member {String} date
 */
ProductInsightsRequestPurchasesInner.prototype['date'] = undefined;

/**
 * @member {Number} quantity_purchased
 */
ProductInsightsRequestPurchasesInner.prototype['quantity_purchased'] = undefined;

/**
 * @member {Number} cost_price
 */
ProductInsightsRequestPurchasesInner.prototype['cost_price'] = undefined;

/**
 * @member {Number} cost_price_converted
 */
ProductInsightsRequestPurchasesInner.prototype['cost_price_converted'] = undefined;

/**
 * @member {String} currency
 */
ProductInsightsRequestPurchasesInner.prototype['currency'] = undefined;

/**
 * @member {String} supplier_id
 */
ProductInsightsRequestPurchasesInner.prototype['supplier_id'] = undefined;

/**
 * Used for lead-time reliability analysis
 * @member {Date} purchase_order_date
 */
ProductInsightsRequestPurchasesInner.prototype['purchase_order_date'] = undefined;

/**
 * @member {Date} expected_delivery_date
 */
ProductInsightsRequestPurchasesInner.prototype['expected_delivery_date'] = undefined;

/**
 * @member {Date} actual_delivery_date
 */
ProductInsightsRequestPurchasesInner.prototype['actual_delivery_date'] = undefined;






export default ProductInsightsRequestPurchasesInner;

