/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.3
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProductInsightsResponseResultComparisonDevelopments model module.
 * @module model/ProductInsightsResponseResultComparisonDevelopments
 * @version 2.0.3
 */
class ProductInsightsResponseResultComparisonDevelopments {
    /**
     * Constructs a new <code>ProductInsightsResponseResultComparisonDevelopments</code>.
     * New / changed / resolved breakdown so repeat calls make genuine developments easy to pick out
     * @alias module:model/ProductInsightsResponseResultComparisonDevelopments
     */
    constructor() { 
        
        ProductInsightsResponseResultComparisonDevelopments.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductInsightsResponseResultComparisonDevelopments</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductInsightsResponseResultComparisonDevelopments} obj Optional instance to populate.
     * @return {module:model/ProductInsightsResponseResultComparisonDevelopments} The populated <code>ProductInsightsResponseResultComparisonDevelopments</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductInsightsResponseResultComparisonDevelopments();

            if (data.hasOwnProperty('new')) {
                obj['new'] = ApiClient.convertToType(data['new'], [{'String': Object}]);
            }
            if (data.hasOwnProperty('changed')) {
                obj['changed'] = ApiClient.convertToType(data['changed'], [{'String': Object}]);
            }
            if (data.hasOwnProperty('resolved')) {
                obj['resolved'] = ApiClient.convertToType(data['resolved'], [{'String': Object}]);
            }
            if (data.hasOwnProperty('unchanged_count')) {
                obj['unchanged_count'] = ApiClient.convertToType(data['unchanged_count'], 'Number');
            }
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = ApiClient.convertToType(data['summary'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductInsightsResponseResultComparisonDevelopments</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductInsightsResponseResultComparisonDevelopments</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['new'])) {
            throw new Error("Expected the field `new` to be an array in the JSON data but got " + data['new']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['changed'])) {
            throw new Error("Expected the field `changed` to be an array in the JSON data but got " + data['changed']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['resolved'])) {
            throw new Error("Expected the field `resolved` to be an array in the JSON data but got " + data['resolved']);
        }
        // ensure the json data is a string
        if (data['summary'] && !(typeof data['summary'] === 'string' || data['summary'] instanceof String)) {
            throw new Error("Expected the field `summary` to be a primitive type in the JSON string but got " + data['summary']);
        }

        return true;
    }


}



/**
 * @member {Array.<Object.<String, Object>>} new
 */
ProductInsightsResponseResultComparisonDevelopments.prototype['new'] = undefined;

/**
 * @member {Array.<Object.<String, Object>>} changed
 */
ProductInsightsResponseResultComparisonDevelopments.prototype['changed'] = undefined;

/**
 * @member {Array.<Object.<String, Object>>} resolved
 */
ProductInsightsResponseResultComparisonDevelopments.prototype['resolved'] = undefined;

/**
 * @member {Number} unchanged_count
 */
ProductInsightsResponseResultComparisonDevelopments.prototype['unchanged_count'] = undefined;

/**
 * @member {String} summary
 */
ProductInsightsResponseResultComparisonDevelopments.prototype['summary'] = undefined;






export default ProductInsightsResponseResultComparisonDevelopments;

