/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProductInsightsRequestBaselinePeriodDays from './ProductInsightsRequestBaselinePeriodDays';
import ProductInsightsRequestCostHistoryInner from './ProductInsightsRequestCostHistoryInner';
import ProductInsightsRequestInsightSettings from './ProductInsightsRequestInsightSettings';
import ProductInsightsRequestPurchasesInner from './ProductInsightsRequestPurchasesInner';
import ProductInsightsRequestSalesInner from './ProductInsightsRequestSalesInner';

/**
 * The ProductInsightsRequest model module.
 * @module model/ProductInsightsRequest
 * @version 2.2.0
 */
class ProductInsightsRequest {
    /**
     * Constructs a new <code>ProductInsightsRequest</code>.
     * At least one of &#x60;sales&#x60;, &#x60;purchases&#x60; or &#x60;cost_history&#x60; must be provided.
     * @alias module:model/ProductInsightsRequest
     * @param identifier {String} Product identifier
     */
    constructor(identifier) { 
        
        ProductInsightsRequest.initialize(this, identifier);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, identifier) { 
        obj['identifier'] = identifier;
        obj['locale'] = 'en';
    }

    /**
     * Constructs a <code>ProductInsightsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductInsightsRequest} obj Optional instance to populate.
     * @return {module:model/ProductInsightsRequest} The populated <code>ProductInsightsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductInsightsRequest();

            if (data.hasOwnProperty('identifier')) {
                obj['identifier'] = ApiClient.convertToType(data['identifier'], 'String');
            }
            if (data.hasOwnProperty('tenant_context')) {
                obj['tenant_context'] = ApiClient.convertToType(data['tenant_context'], 'String');
            }
            if (data.hasOwnProperty('product_name')) {
                obj['product_name'] = ApiClient.convertToType(data['product_name'], 'String');
            }
            if (data.hasOwnProperty('product_group_id')) {
                obj['product_group_id'] = ApiClient.convertToType(data['product_group_id'], 'String');
            }
            if (data.hasOwnProperty('base_currency')) {
                obj['base_currency'] = ApiClient.convertToType(data['base_currency'], 'String');
            }
            if (data.hasOwnProperty('baseline_period_days')) {
                obj['baseline_period_days'] = ProductInsightsRequestBaselinePeriodDays.constructFromObject(data['baseline_period_days']);
            }
            if (data.hasOwnProperty('locale')) {
                obj['locale'] = ApiClient.convertToType(data['locale'], 'String');
            }
            if (data.hasOwnProperty('sales')) {
                obj['sales'] = ApiClient.convertToType(data['sales'], [ProductInsightsRequestSalesInner]);
            }
            if (data.hasOwnProperty('purchases')) {
                obj['purchases'] = ApiClient.convertToType(data['purchases'], [ProductInsightsRequestPurchasesInner]);
            }
            if (data.hasOwnProperty('cost_history')) {
                obj['cost_history'] = ApiClient.convertToType(data['cost_history'], [ProductInsightsRequestCostHistoryInner]);
            }
            if (data.hasOwnProperty('insight_settings')) {
                obj['insight_settings'] = ProductInsightsRequestInsightSettings.constructFromObject(data['insight_settings']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductInsightsRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductInsightsRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ProductInsightsRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['identifier'] && !(typeof data['identifier'] === 'string' || data['identifier'] instanceof String)) {
            throw new Error("Expected the field `identifier` to be a primitive type in the JSON string but got " + data['identifier']);
        }
        // ensure the json data is a string
        if (data['tenant_context'] && !(typeof data['tenant_context'] === 'string' || data['tenant_context'] instanceof String)) {
            throw new Error("Expected the field `tenant_context` to be a primitive type in the JSON string but got " + data['tenant_context']);
        }
        // ensure the json data is a string
        if (data['product_name'] && !(typeof data['product_name'] === 'string' || data['product_name'] instanceof String)) {
            throw new Error("Expected the field `product_name` to be a primitive type in the JSON string but got " + data['product_name']);
        }
        // ensure the json data is a string
        if (data['product_group_id'] && !(typeof data['product_group_id'] === 'string' || data['product_group_id'] instanceof String)) {
            throw new Error("Expected the field `product_group_id` to be a primitive type in the JSON string but got " + data['product_group_id']);
        }
        // ensure the json data is a string
        if (data['base_currency'] && !(typeof data['base_currency'] === 'string' || data['base_currency'] instanceof String)) {
            throw new Error("Expected the field `base_currency` to be a primitive type in the JSON string but got " + data['base_currency']);
        }
        // validate the optional field `baseline_period_days`
        if (data['baseline_period_days']) { // data not null
          ProductInsightsRequestBaselinePeriodDays.validateJSON(data['baseline_period_days']);
        }
        // ensure the json data is a string
        if (data['locale'] && !(typeof data['locale'] === 'string' || data['locale'] instanceof String)) {
            throw new Error("Expected the field `locale` to be a primitive type in the JSON string but got " + data['locale']);
        }
        if (data['sales']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['sales'])) {
                throw new Error("Expected the field `sales` to be an array in the JSON data but got " + data['sales']);
            }
            // validate the optional field `sales` (array)
            for (const item of data['sales']) {
                ProductInsightsRequestSalesInner.validateJSON(item);
            };
        }
        if (data['purchases']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['purchases'])) {
                throw new Error("Expected the field `purchases` to be an array in the JSON data but got " + data['purchases']);
            }
            // validate the optional field `purchases` (array)
            for (const item of data['purchases']) {
                ProductInsightsRequestPurchasesInner.validateJSON(item);
            };
        }
        if (data['cost_history']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['cost_history'])) {
                throw new Error("Expected the field `cost_history` to be an array in the JSON data but got " + data['cost_history']);
            }
            // validate the optional field `cost_history` (array)
            for (const item of data['cost_history']) {
                ProductInsightsRequestCostHistoryInner.validateJSON(item);
            };
        }
        // validate the optional field `insight_settings`
        if (data['insight_settings']) { // data not null
          ProductInsightsRequestInsightSettings.validateJSON(data['insight_settings']);
        }

        return true;
    }


}

ProductInsightsRequest.RequiredProperties = ["identifier"];

/**
 * Product identifier
 * @member {String} identifier
 */
ProductInsightsRequest.prototype['identifier'] = undefined;

/**
 * @member {String} tenant_context
 */
ProductInsightsRequest.prototype['tenant_context'] = undefined;

/**
 * @member {String} product_name
 */
ProductInsightsRequest.prototype['product_name'] = undefined;

/**
 * @member {String} product_group_id
 */
ProductInsightsRequest.prototype['product_group_id'] = undefined;

/**
 * ISO 4217 currency the analysis reports in
 * @member {String} base_currency
 */
ProductInsightsRequest.prototype['base_currency'] = undefined;

/**
 * @member {module:model/ProductInsightsRequestBaselinePeriodDays} baseline_period_days
 */
ProductInsightsRequest.prototype['baseline_period_days'] = undefined;

/**
 * Locale for insight texts
 * @member {String} locale
 * @default 'en'
 */
ProductInsightsRequest.prototype['locale'] = 'en';

/**
 * @member {Array.<module:model/ProductInsightsRequestSalesInner>} sales
 */
ProductInsightsRequest.prototype['sales'] = undefined;

/**
 * @member {Array.<module:model/ProductInsightsRequestPurchasesInner>} purchases
 */
ProductInsightsRequest.prototype['purchases'] = undefined;

/**
 * @member {Array.<module:model/ProductInsightsRequestCostHistoryInner>} cost_history
 */
ProductInsightsRequest.prototype['cost_history'] = undefined;

/**
 * @member {module:model/ProductInsightsRequestInsightSettings} insight_settings
 */
ProductInsightsRequest.prototype['insight_settings'] = undefined;






export default ProductInsightsRequest;

