/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TrafficForecastingResponseMetaTiming from './TrafficForecastingResponseMetaTiming';

/**
 * The TrafficForecastingResponseMeta model module.
 * @module model/TrafficForecastingResponseMeta
 * @version 2.0.0
 */
class TrafficForecastingResponseMeta {
    /**
     * Constructs a new <code>TrafficForecastingResponseMeta</code>.
     * @alias module:model/TrafficForecastingResponseMeta
     */
    constructor() { 
        
        TrafficForecastingResponseMeta.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TrafficForecastingResponseMeta</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TrafficForecastingResponseMeta} obj Optional instance to populate.
     * @return {module:model/TrafficForecastingResponseMeta} The populated <code>TrafficForecastingResponseMeta</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TrafficForecastingResponseMeta();

            if (data.hasOwnProperty('timing')) {
                obj['timing'] = TrafficForecastingResponseMetaTiming.constructFromObject(data['timing']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TrafficForecastingResponseMeta</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TrafficForecastingResponseMeta</code>.
     */
    static validateJSON(data) {
        // validate the optional field `timing`
        if (data['timing']) { // data not null
          TrafficForecastingResponseMetaTiming.validateJSON(data['timing']);
        }

        return true;
    }


}



/**
 * @member {module:model/TrafficForecastingResponseMetaTiming} timing
 */
TrafficForecastingResponseMeta.prototype['timing'] = undefined;






export default TrafficForecastingResponseMeta;

