/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.2
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TrafficForecastingResponseResultCapacityAnalysis from './TrafficForecastingResponseResultCapacityAnalysis';
import TrafficForecastingResponseResultCostOptimization from './TrafficForecastingResponseResultCostOptimization';
import TrafficForecastingResponseResultForecastDataInner from './TrafficForecastingResponseResultForecastDataInner';
import TrafficForecastingResponseResultScalingRecommendations from './TrafficForecastingResponseResultScalingRecommendations';
import TrafficForecastingResponseResultTrafficAlerts from './TrafficForecastingResponseResultTrafficAlerts';

/**
 * The TrafficForecastingResponseResult model module.
 * @module model/TrafficForecastingResponseResult
 * @version 2.0.2
 */
class TrafficForecastingResponseResult {
    /**
     * Constructs a new <code>TrafficForecastingResponseResult</code>.
     * @alias module:model/TrafficForecastingResponseResult
     */
    constructor() { 
        
        TrafficForecastingResponseResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TrafficForecastingResponseResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TrafficForecastingResponseResult} obj Optional instance to populate.
     * @return {module:model/TrafficForecastingResponseResult} The populated <code>TrafficForecastingResponseResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TrafficForecastingResponseResult();

            if (data.hasOwnProperty('metric')) {
                obj['metric'] = ApiClient.convertToType(data['metric'], 'String');
            }
            if (data.hasOwnProperty('current_capacity')) {
                obj['current_capacity'] = ApiClient.convertToType(data['current_capacity'], 'Number');
            }
            if (data.hasOwnProperty('baseline_traffic')) {
                obj['baseline_traffic'] = ApiClient.convertToType(data['baseline_traffic'], 'Number');
            }
            if (data.hasOwnProperty('scaling_recommendations')) {
                obj['scaling_recommendations'] = TrafficForecastingResponseResultScalingRecommendations.constructFromObject(data['scaling_recommendations']);
            }
            if (data.hasOwnProperty('capacity_analysis')) {
                obj['capacity_analysis'] = TrafficForecastingResponseResultCapacityAnalysis.constructFromObject(data['capacity_analysis']);
            }
            if (data.hasOwnProperty('traffic_alerts')) {
                obj['traffic_alerts'] = TrafficForecastingResponseResultTrafficAlerts.constructFromObject(data['traffic_alerts']);
            }
            if (data.hasOwnProperty('cost_optimization')) {
                obj['cost_optimization'] = TrafficForecastingResponseResultCostOptimization.constructFromObject(data['cost_optimization']);
            }
            if (data.hasOwnProperty('forecast_data')) {
                obj['forecast_data'] = ApiClient.convertToType(data['forecast_data'], [TrafficForecastingResponseResultForecastDataInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TrafficForecastingResponseResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TrafficForecastingResponseResult</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['metric'] && !(typeof data['metric'] === 'string' || data['metric'] instanceof String)) {
            throw new Error("Expected the field `metric` to be a primitive type in the JSON string but got " + data['metric']);
        }
        // validate the optional field `scaling_recommendations`
        if (data['scaling_recommendations']) { // data not null
          TrafficForecastingResponseResultScalingRecommendations.validateJSON(data['scaling_recommendations']);
        }
        // validate the optional field `capacity_analysis`
        if (data['capacity_analysis']) { // data not null
          TrafficForecastingResponseResultCapacityAnalysis.validateJSON(data['capacity_analysis']);
        }
        // validate the optional field `traffic_alerts`
        if (data['traffic_alerts']) { // data not null
          TrafficForecastingResponseResultTrafficAlerts.validateJSON(data['traffic_alerts']);
        }
        // validate the optional field `cost_optimization`
        if (data['cost_optimization']) { // data not null
          TrafficForecastingResponseResultCostOptimization.validateJSON(data['cost_optimization']);
        }
        if (data['forecast_data']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['forecast_data'])) {
                throw new Error("Expected the field `forecast_data` to be an array in the JSON data but got " + data['forecast_data']);
            }
            // validate the optional field `forecast_data` (array)
            for (const item of data['forecast_data']) {
                TrafficForecastingResponseResultForecastDataInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Metric identifier from the request
 * @member {String} metric
 */
TrafficForecastingResponseResult.prototype['metric'] = undefined;

/**
 * Current infrastructure capacity
 * @member {Number} current_capacity
 */
TrafficForecastingResponseResult.prototype['current_capacity'] = undefined;

/**
 * Baseline traffic level
 * @member {Number} baseline_traffic
 */
TrafficForecastingResponseResult.prototype['baseline_traffic'] = undefined;

/**
 * @member {module:model/TrafficForecastingResponseResultScalingRecommendations} scaling_recommendations
 */
TrafficForecastingResponseResult.prototype['scaling_recommendations'] = undefined;

/**
 * @member {module:model/TrafficForecastingResponseResultCapacityAnalysis} capacity_analysis
 */
TrafficForecastingResponseResult.prototype['capacity_analysis'] = undefined;

/**
 * @member {module:model/TrafficForecastingResponseResultTrafficAlerts} traffic_alerts
 */
TrafficForecastingResponseResult.prototype['traffic_alerts'] = undefined;

/**
 * @member {module:model/TrafficForecastingResponseResultCostOptimization} cost_optimization
 */
TrafficForecastingResponseResult.prototype['cost_optimization'] = undefined;

/**
 * Underlying forecast data used for analysis
 * @member {Array.<module:model/TrafficForecastingResponseResultForecastDataInner>} forecast_data
 */
TrafficForecastingResponseResult.prototype['forecast_data'] = undefined;






export default TrafficForecastingResponseResult;

