/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner from './TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner';

/**
 * The TrafficForecastingResponseResultScalingRecommendations model module.
 * @module model/TrafficForecastingResponseResultScalingRecommendations
 * @version 2.2.0
 */
class TrafficForecastingResponseResultScalingRecommendations {
    /**
     * Constructs a new <code>TrafficForecastingResponseResultScalingRecommendations</code>.
     * Infrastructure scaling analysis and recommendations
     * @alias module:model/TrafficForecastingResponseResultScalingRecommendations
     */
    constructor() { 
        
        TrafficForecastingResponseResultScalingRecommendations.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TrafficForecastingResponseResultScalingRecommendations</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TrafficForecastingResponseResultScalingRecommendations} obj Optional instance to populate.
     * @return {module:model/TrafficForecastingResponseResultScalingRecommendations} The populated <code>TrafficForecastingResponseResultScalingRecommendations</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TrafficForecastingResponseResultScalingRecommendations();

            if (data.hasOwnProperty('peak_traffic')) {
                obj['peak_traffic'] = ApiClient.convertToType(data['peak_traffic'], 'Number');
            }
            if (data.hasOwnProperty('average_traffic')) {
                obj['average_traffic'] = ApiClient.convertToType(data['average_traffic'], 'Number');
            }
            if (data.hasOwnProperty('current_utilization')) {
                obj['current_utilization'] = ApiClient.convertToType(data['current_utilization'], 'Number');
            }
            if (data.hasOwnProperty('recommendations')) {
                obj['recommendations'] = ApiClient.convertToType(data['recommendations'], [TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TrafficForecastingResponseResultScalingRecommendations</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TrafficForecastingResponseResultScalingRecommendations</code>.
     */
    static validateJSON(data) {
        if (data['recommendations']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['recommendations'])) {
                throw new Error("Expected the field `recommendations` to be an array in the JSON data but got " + data['recommendations']);
            }
            // validate the optional field `recommendations` (array)
            for (const item of data['recommendations']) {
                TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Predicted peak traffic across forecast periods
 * @member {Number} peak_traffic
 */
TrafficForecastingResponseResultScalingRecommendations.prototype['peak_traffic'] = undefined;

/**
 * Average predicted traffic
 * @member {Number} average_traffic
 */
TrafficForecastingResponseResultScalingRecommendations.prototype['average_traffic'] = undefined;

/**
 * Peak utilization percentage of current capacity
 * @member {Number} current_utilization
 */
TrafficForecastingResponseResultScalingRecommendations.prototype['current_utilization'] = undefined;

/**
 * Scaling action recommendations
 * @member {Array.<module:model/TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner>} recommendations
 */
TrafficForecastingResponseResultScalingRecommendations.prototype['recommendations'] = undefined;






export default TrafficForecastingResponseResultScalingRecommendations;

