/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TrafficForecastingResponseResultCostOptimizationCostBreakdown from './TrafficForecastingResponseResultCostOptimizationCostBreakdown';
import TrafficForecastingResponseResultCostOptimizationRecommendationsInner from './TrafficForecastingResponseResultCostOptimizationRecommendationsInner';

/**
 * The TrafficForecastingResponseResultCostOptimization model module.
 * @module model/TrafficForecastingResponseResultCostOptimization
 * @version 2.2.0
 */
class TrafficForecastingResponseResultCostOptimization {
    /**
     * Constructs a new <code>TrafficForecastingResponseResultCostOptimization</code>.
     * Cost analysis and optimization recommendations
     * @alias module:model/TrafficForecastingResponseResultCostOptimization
     */
    constructor() { 
        
        TrafficForecastingResponseResultCostOptimization.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TrafficForecastingResponseResultCostOptimization</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TrafficForecastingResponseResultCostOptimization} obj Optional instance to populate.
     * @return {module:model/TrafficForecastingResponseResultCostOptimization} The populated <code>TrafficForecastingResponseResultCostOptimization</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TrafficForecastingResponseResultCostOptimization();

            if (data.hasOwnProperty('current_cost')) {
                obj['current_cost'] = ApiClient.convertToType(data['current_cost'], 'Number');
            }
            if (data.hasOwnProperty('optimized_cost')) {
                obj['optimized_cost'] = ApiClient.convertToType(data['optimized_cost'], 'Number');
            }
            if (data.hasOwnProperty('potential_savings')) {
                obj['potential_savings'] = ApiClient.convertToType(data['potential_savings'], 'Number');
            }
            if (data.hasOwnProperty('savings_percentage')) {
                obj['savings_percentage'] = ApiClient.convertToType(data['savings_percentage'], 'Number');
            }
            if (data.hasOwnProperty('cost_breakdown')) {
                obj['cost_breakdown'] = TrafficForecastingResponseResultCostOptimizationCostBreakdown.constructFromObject(data['cost_breakdown']);
            }
            if (data.hasOwnProperty('recommendations')) {
                obj['recommendations'] = ApiClient.convertToType(data['recommendations'], [TrafficForecastingResponseResultCostOptimizationRecommendationsInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TrafficForecastingResponseResultCostOptimization</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TrafficForecastingResponseResultCostOptimization</code>.
     */
    static validateJSON(data) {
        // validate the optional field `cost_breakdown`
        if (data['cost_breakdown']) { // data not null
          TrafficForecastingResponseResultCostOptimizationCostBreakdown.validateJSON(data['cost_breakdown']);
        }
        if (data['recommendations']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['recommendations'])) {
                throw new Error("Expected the field `recommendations` to be an array in the JSON data but got " + data['recommendations']);
            }
            // validate the optional field `recommendations` (array)
            for (const item of data['recommendations']) {
                TrafficForecastingResponseResultCostOptimizationRecommendationsInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Current total cost based on capacity
 * @member {Number} current_cost
 */
TrafficForecastingResponseResultCostOptimization.prototype['current_cost'] = undefined;

/**
 * Optimized cost after recommendations
 * @member {Number} optimized_cost
 */
TrafficForecastingResponseResultCostOptimization.prototype['optimized_cost'] = undefined;

/**
 * Potential cost savings
 * @member {Number} potential_savings
 */
TrafficForecastingResponseResultCostOptimization.prototype['potential_savings'] = undefined;

/**
 * Savings as percentage of current cost
 * @member {Number} savings_percentage
 */
TrafficForecastingResponseResultCostOptimization.prototype['savings_percentage'] = undefined;

/**
 * @member {module:model/TrafficForecastingResponseResultCostOptimizationCostBreakdown} cost_breakdown
 */
TrafficForecastingResponseResultCostOptimization.prototype['cost_breakdown'] = undefined;

/**
 * Cost optimization recommendations
 * @member {Array.<module:model/TrafficForecastingResponseResultCostOptimizationRecommendationsInner>} recommendations
 */
TrafficForecastingResponseResultCostOptimization.prototype['recommendations'] = undefined;






export default TrafficForecastingResponseResultCostOptimization;

