/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TrafficForecastingResponseResultCostOptimizationRecommendationsInner model module.
 * @module model/TrafficForecastingResponseResultCostOptimizationRecommendationsInner
 * @version 2.1.0
 */
class TrafficForecastingResponseResultCostOptimizationRecommendationsInner {
    /**
     * Constructs a new <code>TrafficForecastingResponseResultCostOptimizationRecommendationsInner</code>.
     * @alias module:model/TrafficForecastingResponseResultCostOptimizationRecommendationsInner
     */
    constructor() { 
        
        TrafficForecastingResponseResultCostOptimizationRecommendationsInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TrafficForecastingResponseResultCostOptimizationRecommendationsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TrafficForecastingResponseResultCostOptimizationRecommendationsInner} obj Optional instance to populate.
     * @return {module:model/TrafficForecastingResponseResultCostOptimizationRecommendationsInner} The populated <code>TrafficForecastingResponseResultCostOptimizationRecommendationsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TrafficForecastingResponseResultCostOptimizationRecommendationsInner();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('current_capacity')) {
                obj['current_capacity'] = ApiClient.convertToType(data['current_capacity'], 'Number');
            }
            if (data.hasOwnProperty('recommended_capacity')) {
                obj['recommended_capacity'] = ApiClient.convertToType(data['recommended_capacity'], 'Number');
            }
            if (data.hasOwnProperty('potential_savings')) {
                obj['potential_savings'] = ApiClient.convertToType(data['potential_savings'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TrafficForecastingResponseResultCostOptimizationRecommendationsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TrafficForecastingResponseResultCostOptimizationRecommendationsInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}



/**
 * Type of cost optimization
 * @member {module:model/TrafficForecastingResponseResultCostOptimizationRecommendationsInner.TypeEnum} type
 */
TrafficForecastingResponseResultCostOptimizationRecommendationsInner.prototype['type'] = undefined;

/**
 * Recommendation description
 * @member {String} description
 */
TrafficForecastingResponseResultCostOptimizationRecommendationsInner.prototype['description'] = undefined;

/**
 * Current capacity (for capacity optimization)
 * @member {Number} current_capacity
 */
TrafficForecastingResponseResultCostOptimizationRecommendationsInner.prototype['current_capacity'] = undefined;

/**
 * Recommended capacity (for capacity optimization)
 * @member {Number} recommended_capacity
 */
TrafficForecastingResponseResultCostOptimizationRecommendationsInner.prototype['recommended_capacity'] = undefined;

/**
 * Potential cost savings
 * @member {Number} potential_savings
 */
TrafficForecastingResponseResultCostOptimizationRecommendationsInner.prototype['potential_savings'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
TrafficForecastingResponseResultCostOptimizationRecommendationsInner['TypeEnum'] = {

    /**
     * value: "capacity_optimization"
     * @const
     */
    "capacity_optimization": "capacity_optimization",

    /**
     * value: "enable_auto_scaling"
     * @const
     */
    "enable_auto_scaling": "enable_auto_scaling"
};



export default TrafficForecastingResponseResultCostOptimizationRecommendationsInner;

