/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ValidationFailedResponse model module.
 * @module model/ValidationFailedResponse
 * @version 2.2.0
 */
class ValidationFailedResponse {
    /**
     * Constructs a new <code>ValidationFailedResponse</code>.
     * The validation-error shape shared by the grouped, batch and product-insights endpoints
     * @alias module:model/ValidationFailedResponse
     */
    constructor() { 
        
        ValidationFailedResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ValidationFailedResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ValidationFailedResponse} obj Optional instance to populate.
     * @return {module:model/ValidationFailedResponse} The populated <code>ValidationFailedResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ValidationFailedResponse();

            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], {'String': ['String']});
            }
            if (data.hasOwnProperty('time_taken_ms')) {
                obj['time_taken_ms'] = ApiClient.convertToType(data['time_taken_ms'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ValidationFailedResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ValidationFailedResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['error'] && !(typeof data['error'] === 'string' || data['error'] instanceof String)) {
            throw new Error("Expected the field `error` to be a primitive type in the JSON string but got " + data['error']);
        }

        return true;
    }


}



/**
 * @member {String} error
 */
ValidationFailedResponse.prototype['error'] = undefined;

/**
 * @member {Object.<String, Array.<String>>} errors
 */
ValidationFailedResponse.prototype['errors'] = undefined;

/**
 * @member {Number} time_taken_ms
 */
ValidationFailedResponse.prototype['time_taken_ms'] = undefined;






export default ValidationFailedResponse;

