/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ValueBounds model module.
 * @module model/ValueBounds
 * @version 2.0.0
 */
class ValueBounds {
    /**
     * Constructs a new <code>ValueBounds</code>.
     * The range the series cannot leave — a rate has both sides, a backlog only a floor. At least one side must be declared, and min must be less than max. The series is forecast on a transformed scale and mapped back, so the point, both bounds and every quantile land inside the range and the band takes the right asymmetric shape near a bound. Checked against the series&#39; own history: bounds the history already contradicts are rejected up front (usually a unit mismatch, e.g. 0–1 rates declared as 0–100). Honoured by /v2/forecast and /v2/batch/forecast (request-level default or per-series override); rejected on grouped forecasts; ignored by other endpoints sharing this request shape. 
     * @alias module:model/ValueBounds
     */
    constructor() { 
        
        ValueBounds.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ValueBounds</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ValueBounds} obj Optional instance to populate.
     * @return {module:model/ValueBounds} The populated <code>ValueBounds</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ValueBounds();

            if (data.hasOwnProperty('min')) {
                obj['min'] = ApiClient.convertToType(data['min'], 'Number');
            }
            if (data.hasOwnProperty('max')) {
                obj['max'] = ApiClient.convertToType(data['max'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ValueBounds</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ValueBounds</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Floor the series cannot go below
 * @member {Number} min
 */
ValueBounds.prototype['min'] = undefined;

/**
 * Ceiling the series cannot exceed
 * @member {Number} max
 */
ValueBounds.prototype['max'] = undefined;






export default ValueBounds;

