/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V2HealthGet200Response model module.
 * @module ForecastAPI/model/V2HealthGet200Response
 * @version 2.0.0
 */
class V2HealthGet200Response {
    /**
     * Constructs a new <code>V2HealthGet200Response</code>.
     * @alias module:ForecastAPI/model/V2HealthGet200Response
     */
    constructor() { 
        
        V2HealthGet200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V2HealthGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:ForecastAPI/model/V2HealthGet200Response} obj Optional instance to populate.
     * @return {module:ForecastAPI/model/V2HealthGet200Response} The populated <code>V2HealthGet200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V2HealthGet200Response();

            if (data.hasOwnProperty('api')) {
                obj['api'] = ApiClient.convertToType(data['api'], 'String');
            }
            if (data.hasOwnProperty('advanced_models')) {
                obj['advanced_models'] = ApiClient.convertToType(data['advanced_models'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V2HealthGet200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V2HealthGet200Response</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['api'] && !(typeof data['api'] === 'string' || data['api'] instanceof String)) {
            throw new Error("Expected the field `api` to be a primitive type in the JSON string but got " + data['api']);
        }
        // ensure the json data is a string
        if (data['advanced_models'] && !(typeof data['advanced_models'] === 'string' || data['advanced_models'] instanceof String)) {
            throw new Error("Expected the field `advanced_models` to be a primitive type in the JSON string but got " + data['advanced_models']);
        }

        return true;
    }


}



/**
 * @member {module:ForecastAPI/model/V2HealthGet200Response.ApiEnum} api
 */
V2HealthGet200Response.prototype['api'] = undefined;

/**
 * @member {module:ForecastAPI/model/V2HealthGet200Response.AdvancedModelsEnum} advanced_models
 */
V2HealthGet200Response.prototype['advanced_models'] = undefined;





/**
 * Allowed values for the <code>api</code> property.
 * @enum {String}
 * @readonly
 */
V2HealthGet200Response['ApiEnum'] = {

    /**
     * value: "ok"
     * @const
     */
    "ok": "ok",

    /**
     * value: "down"
     * @const
     */
    "down": "down"
};


/**
 * Allowed values for the <code>advanced_models</code> property.
 * @enum {String}
 * @readonly
 */
V2HealthGet200Response['AdvancedModelsEnum'] = {

    /**
     * value: "ok"
     * @const
     */
    "ok": "ok",

    /**
     * value: "down"
     * @const
     */
    "down": "down"
};



export default V2HealthGet200Response;

