/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.3
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import BatchForecastAccepted from '../model/BatchForecastAccepted';
import BatchForecastRequest from '../model/BatchForecastRequest';
import BatchForecastStatusResponse from '../model/BatchForecastStatusResponse';
import BatchPresignResponse from '../model/BatchPresignResponse';
import ErrorResponse from '../model/ErrorResponse';
import GetGroupedForecast404Response from '../model/GetGroupedForecast404Response';
import ValidationFailedResponse from '../model/ValidationFailedResponse';

/**
* BatchForecasting service.
* @module api/BatchForecastingApi
* @version 2.0.3
*/
export default class BatchForecastingApi {

    /**
    * Constructs a new BatchForecastingApi. 
    * @alias module:api/BatchForecastingApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Submit a batch of series for forecasting
     * Forecast up to 100,000 independent series in one call (10 on the free tier), at a discount per forecast. Each series is processed independently — one failing series does not fail the others. Submission returns `202` with a `batch_id` to poll via `GET /v2/batch/forecast/{batch_id}`.  Request-level `periods`, `frequency`, `data_type`, `confidence` and the four planning parameters (`quantiles`, `value_bounds`, `adjustments`, `accumulate`) act as defaults every series inherits; any series may override any of them. `model` is request-level only.  For payloads too large to send inline, get a presigned upload URL from `POST /v2/batch/forecast/presign` and submit `file_key` instead of `series`. 
     * @param {module:model/BatchForecastRequest} batchForecastRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/BatchForecastAccepted} and HTTP response
     */
    createBatchForecastWithHttpInfo(batchForecastRequest) {
      let postBody = batchForecastRequest;
      // verify the required parameter 'batchForecastRequest' is set
      if (batchForecastRequest === undefined || batchForecastRequest === null) {
        throw new Error("Missing the required parameter 'batchForecastRequest' when calling createBatchForecast");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = BatchForecastAccepted;
      return this.apiClient.callApi(
        '/v2/batch/forecast', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Submit a batch of series for forecasting
     * Forecast up to 100,000 independent series in one call (10 on the free tier), at a discount per forecast. Each series is processed independently — one failing series does not fail the others. Submission returns `202` with a `batch_id` to poll via `GET /v2/batch/forecast/{batch_id}`.  Request-level `periods`, `frequency`, `data_type`, `confidence` and the four planning parameters (`quantiles`, `value_bounds`, `adjustments`, `accumulate`) act as defaults every series inherits; any series may override any of them. `model` is request-level only.  For payloads too large to send inline, get a presigned upload URL from `POST /v2/batch/forecast/presign` and submit `file_key` instead of `series`. 
     * @param {module:model/BatchForecastRequest} batchForecastRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/BatchForecastAccepted}
     */
    createBatchForecast(batchForecastRequest) {
      return this.createBatchForecastWithHttpInfo(batchForecastRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Poll a batch forecast for status and results
     * Returns the batch's status, a summary once it finalises, and each series' results under `results.data` — keyed by **entity id** rather than by your identifier, because one batch may contain the same identifier under several `tenant_context` values. Match series via the `identifier` and `tenant_context` echoed inside each result object. 
     * @param {String} batchId The id returned by POST /v2/batch/forecast
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/BatchForecastStatusResponse} and HTTP response
     */
    getBatchForecastWithHttpInfo(batchId) {
      let postBody = null;
      // verify the required parameter 'batchId' is set
      if (batchId === undefined || batchId === null) {
        throw new Error("Missing the required parameter 'batchId' when calling getBatchForecast");
      }

      let pathParams = {
        'batch_id': batchId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKey'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = BatchForecastStatusResponse;
      return this.apiClient.callApi(
        '/v2/batch/forecast/{batch_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Poll a batch forecast for status and results
     * Returns the batch's status, a summary once it finalises, and each series' results under `results.data` — keyed by **entity id** rather than by your identifier, because one batch may contain the same identifier under several `tenant_context` values. Match series via the `identifier` and `tenant_context` echoed inside each result object. 
     * @param {String} batchId The id returned by POST /v2/batch/forecast
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/BatchForecastStatusResponse}
     */
    getBatchForecast(batchId) {
      return this.getBatchForecastWithHttpInfo(batchId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get a presigned URL for a file-based batch upload
     * Returns a presigned URL for uploading a JSON file containing the batch request body — an object with a `series` array, the same shape as the inline `/v2/batch/forecast` request. HTTP PUT the file to `upload_url` (including any returned `headers`), then submit the batch by POSTing the returned `file_key` to `/v2/batch/forecast`. The URL is valid for 30 minutes. 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/BatchPresignResponse} and HTTP response
     */
    presignBatchForecastWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKey'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = BatchPresignResponse;
      return this.apiClient.callApi(
        '/v2/batch/forecast/presign', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get a presigned URL for a file-based batch upload
     * Returns a presigned URL for uploading a JSON file containing the batch request body — an object with a `series` array, the same shape as the inline `/v2/batch/forecast` request. HTTP PUT the file to `upload_url` (including any returned `headers`), then submit the batch by POSTing the returned `file_key` to `/v2/batch/forecast`. The URL is valid for 30 minutes. 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/BatchPresignResponse}
     */
    presignBatchForecast() {
      return this.presignBatchForecastWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
