/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.2
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import DeprecatedV1404Response from '../model/DeprecatedV1404Response';

/**
* Default service.
* @module api/DefaultApi
* @version 2.0.2
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Deprecated v1 endpoints
     * @param {String} any 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    deprecatedV1WithHttpInfo(any) {
      let postBody = null;
      // verify the required parameter 'any' is set
      if (any === undefined || any === null) {
        throw new Error("Missing the required parameter 'any' when calling deprecatedV1");
      }

      let pathParams = {
        'any': any
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/v1/{any}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Deprecated v1 endpoints
     * @param {String} any 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    deprecatedV1(any) {
      return this.deprecatedV1WithHttpInfo(any)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
