/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateForecast400Response from '../model/CreateForecast400Response';
import CreateForecast502Response from '../model/CreateForecast502Response';
import ErrorResponse from '../model/ErrorResponse';
import ForecastRequest from '../model/ForecastRequest';
import ForecastResponse from '../model/ForecastResponse';
import ValidationErrorResponse from '../model/ValidationErrorResponse';

/**
* Forecasting service.
* @module api/ForecastingApi
* @version 2.2.0
*/
export default class ForecastingApi {

    /**
    * Constructs a new ForecastingApi. 
    * @alias module:api/ForecastingApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Generate forecast for time series data
     * @param {module:model/ForecastRequest} forecastRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ForecastResponse} and HTTP response
     */
    createForecastWithHttpInfo(forecastRequest) {
      let postBody = forecastRequest;
      // verify the required parameter 'forecastRequest' is set
      if (forecastRequest === undefined || forecastRequest === null) {
        throw new Error("Missing the required parameter 'forecastRequest' when calling createForecast");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ForecastResponse;
      return this.apiClient.callApi(
        '/v2/forecast', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Generate forecast for time series data
     * @param {module:model/ForecastRequest} forecastRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ForecastResponse}
     */
    createForecast(forecastRequest) {
      return this.createForecastWithHttpInfo(forecastRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
