/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.3
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../model/ErrorResponse';
import GetGroupedForecast404Response from '../model/GetGroupedForecast404Response';
import GroupedForecastAccepted from '../model/GroupedForecastAccepted';
import GroupedForecastRequest from '../model/GroupedForecastRequest';
import GroupedForecastStatusResponse from '../model/GroupedForecastStatusResponse';
import ValidationFailedResponse from '../model/ValidationFailedResponse';

/**
* GroupedForecasting service.
* @module api/GroupedForecastingApi
* @version 2.0.3
*/
export default class GroupedForecastingApi {

    /**
    * Constructs a new GroupedForecastingApi. 
    * @alias module:api/GroupedForecastingApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Submit a grouped (hierarchical) forecast with reconciliation
     * Forecast a set of related series that roll up to a total — MRR by plan and region, demand by warehouse, revenue by category — and get back one coherent result: every parent equals the sum of its children, in every period, at every level.  You send only the **leaves** of the hierarchy (every combination of the declared dimensions, each with its own history). The API derives every aggregate level and the grand total by summing the leaf histories, forecasts the nodes, reconciles them to coherence, and stores each node as its own entity with independently tracked accuracy.  Processing is **asynchronous**: submission returns `202` with an id to poll via `GET /v2/forecast/grouped/{grouped_forecast_id}`. The run executes in the background as one all-or-nothing job — a hierarchy is one coherent answer, so there is no partial success. If any node cannot be forecast, the run fails with the reason rather than returning numbers that don't add up.  If you just want independent forecasts per slice — no coherent roll-up — the batch endpoint with per-series identifiers or `tenant_context` is simpler and tolerates per-series failure. 
     * @param {module:model/GroupedForecastRequest} groupedForecastRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GroupedForecastAccepted} and HTTP response
     */
    createGroupedForecastWithHttpInfo(groupedForecastRequest) {
      let postBody = groupedForecastRequest;
      // verify the required parameter 'groupedForecastRequest' is set
      if (groupedForecastRequest === undefined || groupedForecastRequest === null) {
        throw new Error("Missing the required parameter 'groupedForecastRequest' when calling createGroupedForecast");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = GroupedForecastAccepted;
      return this.apiClient.callApi(
        '/v2/forecast/grouped', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Submit a grouped (hierarchical) forecast with reconciliation
     * Forecast a set of related series that roll up to a total — MRR by plan and region, demand by warehouse, revenue by category — and get back one coherent result: every parent equals the sum of its children, in every period, at every level.  You send only the **leaves** of the hierarchy (every combination of the declared dimensions, each with its own history). The API derives every aggregate level and the grand total by summing the leaf histories, forecasts the nodes, reconciles them to coherence, and stores each node as its own entity with independently tracked accuracy.  Processing is **asynchronous**: submission returns `202` with an id to poll via `GET /v2/forecast/grouped/{grouped_forecast_id}`. The run executes in the background as one all-or-nothing job — a hierarchy is one coherent answer, so there is no partial success. If any node cannot be forecast, the run fails with the reason rather than returning numbers that don't add up.  If you just want independent forecasts per slice — no coherent roll-up — the batch endpoint with per-series identifiers or `tenant_context` is simpler and tolerates per-series failure. 
     * @param {module:model/GroupedForecastRequest} groupedForecastRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GroupedForecastAccepted}
     */
    createGroupedForecast(groupedForecastRequest) {
      return this.createGroupedForecastWithHttpInfo(groupedForecastRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Poll a grouped forecast for status and results
     * Returns the run's status. Once `completed`, `results` carries a node map keyed by segment (`total`, `region=eu`, `plan=pro|region=eu`, …) — every node with its own forecast rows, its place in the tree, and the reconciliation details. If the run `failed`, `error` carries the reason and `results` stays null. 
     * @param {String} groupedForecastId The id returned by POST /v2/forecast/grouped
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GroupedForecastStatusResponse} and HTTP response
     */
    getGroupedForecastWithHttpInfo(groupedForecastId) {
      let postBody = null;
      // verify the required parameter 'groupedForecastId' is set
      if (groupedForecastId === undefined || groupedForecastId === null) {
        throw new Error("Missing the required parameter 'groupedForecastId' when calling getGroupedForecast");
      }

      let pathParams = {
        'grouped_forecast_id': groupedForecastId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKey'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GroupedForecastStatusResponse;
      return this.apiClient.callApi(
        '/v2/forecast/grouped/{grouped_forecast_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Poll a grouped forecast for status and results
     * Returns the run's status. Once `completed`, `results` carries a node map keyed by segment (`total`, `region=eu`, `plan=pro|region=eu`, …) — every node with its own forecast rows, its place in the tree, and the reconciliation details. If the run `failed`, `error` carries the reason and `results` stays null. 
     * @param {String} groupedForecastId The id returned by POST /v2/forecast/grouped
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GroupedForecastStatusResponse}
     */
    getGroupedForecast(groupedForecastId) {
      return this.getGroupedForecastWithHttpInfo(groupedForecastId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
