/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AnalysisResponse from './model/AnalysisResponse';
import AnalysisResponseMeta from './model/AnalysisResponseMeta';
import AnalysisResponseMetaTiming from './model/AnalysisResponseMetaTiming';
import AnalysisResponseResult from './model/AnalysisResponseResult';
import AnalysisResponseResultCharacteristics from './model/AnalysisResponseResultCharacteristics';
import ErrorResponse from './model/ErrorResponse';
import ForecastRequest from './model/ForecastRequest';
import ForecastRequestDataInner from './model/ForecastRequestDataInner';
import ForecastResponse from './model/ForecastResponse';
import ForecastResponseMeta from './model/ForecastResponseMeta';
import ForecastResponseMetaTiming from './model/ForecastResponseMetaTiming';
import ForecastResponseResult from './model/ForecastResponseResult';
import InventoryPlanningRequest from './model/InventoryPlanningRequest';
import InventoryPlanningRequestDataInner from './model/InventoryPlanningRequestDataInner';
import InventoryPlanningRequestInventorySettings from './model/InventoryPlanningRequestInventorySettings';
import InventoryPlanningRequestInventorySettingsSuppliersInner from './model/InventoryPlanningRequestInventorySettingsSuppliersInner';
import InventoryPlanningResponse from './model/InventoryPlanningResponse';
import InventoryPlanningResponseMeta from './model/InventoryPlanningResponseMeta';
import InventoryPlanningResponseMetaTiming from './model/InventoryPlanningResponseMetaTiming';
import InventoryPlanningResponseResult from './model/InventoryPlanningResponseResult';
import InventoryPlanningResponseResultForecastDataInner from './model/InventoryPlanningResponseResultForecastDataInner';
import InventoryPlanningResponseResultStockAnalysis from './model/InventoryPlanningResponseResultStockAnalysis';
import InventoryPlanningResponseResultSuppliersInner from './model/InventoryPlanningResponseResultSuppliersInner';
import TrafficForecastingRequest from './model/TrafficForecastingRequest';
import TrafficForecastingRequestDataInner from './model/TrafficForecastingRequestDataInner';
import TrafficForecastingRequestTrafficSettings from './model/TrafficForecastingRequestTrafficSettings';
import TrafficForecastingResponse from './model/TrafficForecastingResponse';
import TrafficForecastingResponseMeta from './model/TrafficForecastingResponseMeta';
import TrafficForecastingResponseMetaTiming from './model/TrafficForecastingResponseMetaTiming';
import TrafficForecastingResponseResult from './model/TrafficForecastingResponseResult';
import TrafficForecastingResponseResultCapacityAnalysis from './model/TrafficForecastingResponseResultCapacityAnalysis';
import TrafficForecastingResponseResultCapacityAnalysisUtilizationPeriodsInner from './model/TrafficForecastingResponseResultCapacityAnalysisUtilizationPeriodsInner';
import TrafficForecastingResponseResultCostOptimization from './model/TrafficForecastingResponseResultCostOptimization';
import TrafficForecastingResponseResultCostOptimizationCostBreakdown from './model/TrafficForecastingResponseResultCostOptimizationCostBreakdown';
import TrafficForecastingResponseResultCostOptimizationRecommendationsInner from './model/TrafficForecastingResponseResultCostOptimizationRecommendationsInner';
import TrafficForecastingResponseResultForecastDataInner from './model/TrafficForecastingResponseResultForecastDataInner';
import TrafficForecastingResponseResultScalingRecommendations from './model/TrafficForecastingResponseResultScalingRecommendations';
import TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner from './model/TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner';
import TrafficForecastingResponseResultTrafficAlerts from './model/TrafficForecastingResponseResultTrafficAlerts';
import TrafficForecastingResponseResultTrafficAlertsAlertsInner from './model/TrafficForecastingResponseResultTrafficAlertsAlertsInner';
import V1AnyGet404Response from './model/V1AnyGet404Response';
import V2ForecastPost400Response from './model/V2ForecastPost400Response';
import V2Get200Response from './model/V2Get200Response';
import V2HealthGet200Response from './model/V2HealthGet200Response';
import V2InventoryPlanningPost400Response from './model/V2InventoryPlanningPost400Response';
import V2InventoryPlanningPost500Response from './model/V2InventoryPlanningPost500Response';
import V2TrafficForecastingPost500Response from './model/V2TrafficForecastingPost500Response';
import ValidationErrorResponse from './model/ValidationErrorResponse';
import AnalysisApi from './api/AnalysisApi';
import DefaultApi from './api/DefaultApi';
import ForecastingApi from './api/ForecastingApi';
import HealthApi from './api/HealthApi';
import InventoryPlanningApi from './api/InventoryPlanningApi';
import TrafficForecastingApi from './api/TrafficForecastingApi';


/**
* Time series forecasting service with multiple algorithms and automatic method selection.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ForecastapiSdk = require('ForecastAPI/index'); // See note below*.
* var xxxSvc = new ForecastapiSdk.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ForecastapiSdk.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['ForecastAPI/index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ForecastapiSdk.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ForecastapiSdk.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module ForecastAPI/index
* @version 2.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ForecastAPI/ApiClient}
     */
    ApiClient,

    /**
     * The AnalysisResponse model constructor.
     * @property {module:ForecastAPI/model/AnalysisResponse}
     */
    AnalysisResponse,

    /**
     * The AnalysisResponseMeta model constructor.
     * @property {module:ForecastAPI/model/AnalysisResponseMeta}
     */
    AnalysisResponseMeta,

    /**
     * The AnalysisResponseMetaTiming model constructor.
     * @property {module:ForecastAPI/model/AnalysisResponseMetaTiming}
     */
    AnalysisResponseMetaTiming,

    /**
     * The AnalysisResponseResult model constructor.
     * @property {module:ForecastAPI/model/AnalysisResponseResult}
     */
    AnalysisResponseResult,

    /**
     * The AnalysisResponseResultCharacteristics model constructor.
     * @property {module:ForecastAPI/model/AnalysisResponseResultCharacteristics}
     */
    AnalysisResponseResultCharacteristics,

    /**
     * The ErrorResponse model constructor.
     * @property {module:ForecastAPI/model/ErrorResponse}
     */
    ErrorResponse,

    /**
     * The ForecastRequest model constructor.
     * @property {module:ForecastAPI/model/ForecastRequest}
     */
    ForecastRequest,

    /**
     * The ForecastRequestDataInner model constructor.
     * @property {module:ForecastAPI/model/ForecastRequestDataInner}
     */
    ForecastRequestDataInner,

    /**
     * The ForecastResponse model constructor.
     * @property {module:ForecastAPI/model/ForecastResponse}
     */
    ForecastResponse,

    /**
     * The ForecastResponseMeta model constructor.
     * @property {module:ForecastAPI/model/ForecastResponseMeta}
     */
    ForecastResponseMeta,

    /**
     * The ForecastResponseMetaTiming model constructor.
     * @property {module:ForecastAPI/model/ForecastResponseMetaTiming}
     */
    ForecastResponseMetaTiming,

    /**
     * The ForecastResponseResult model constructor.
     * @property {module:ForecastAPI/model/ForecastResponseResult}
     */
    ForecastResponseResult,

    /**
     * The InventoryPlanningRequest model constructor.
     * @property {module:ForecastAPI/model/InventoryPlanningRequest}
     */
    InventoryPlanningRequest,

    /**
     * The InventoryPlanningRequestDataInner model constructor.
     * @property {module:ForecastAPI/model/InventoryPlanningRequestDataInner}
     */
    InventoryPlanningRequestDataInner,

    /**
     * The InventoryPlanningRequestInventorySettings model constructor.
     * @property {module:ForecastAPI/model/InventoryPlanningRequestInventorySettings}
     */
    InventoryPlanningRequestInventorySettings,

    /**
     * The InventoryPlanningRequestInventorySettingsSuppliersInner model constructor.
     * @property {module:ForecastAPI/model/InventoryPlanningRequestInventorySettingsSuppliersInner}
     */
    InventoryPlanningRequestInventorySettingsSuppliersInner,

    /**
     * The InventoryPlanningResponse model constructor.
     * @property {module:ForecastAPI/model/InventoryPlanningResponse}
     */
    InventoryPlanningResponse,

    /**
     * The InventoryPlanningResponseMeta model constructor.
     * @property {module:ForecastAPI/model/InventoryPlanningResponseMeta}
     */
    InventoryPlanningResponseMeta,

    /**
     * The InventoryPlanningResponseMetaTiming model constructor.
     * @property {module:ForecastAPI/model/InventoryPlanningResponseMetaTiming}
     */
    InventoryPlanningResponseMetaTiming,

    /**
     * The InventoryPlanningResponseResult model constructor.
     * @property {module:ForecastAPI/model/InventoryPlanningResponseResult}
     */
    InventoryPlanningResponseResult,

    /**
     * The InventoryPlanningResponseResultForecastDataInner model constructor.
     * @property {module:ForecastAPI/model/InventoryPlanningResponseResultForecastDataInner}
     */
    InventoryPlanningResponseResultForecastDataInner,

    /**
     * The InventoryPlanningResponseResultStockAnalysis model constructor.
     * @property {module:ForecastAPI/model/InventoryPlanningResponseResultStockAnalysis}
     */
    InventoryPlanningResponseResultStockAnalysis,

    /**
     * The InventoryPlanningResponseResultSuppliersInner model constructor.
     * @property {module:ForecastAPI/model/InventoryPlanningResponseResultSuppliersInner}
     */
    InventoryPlanningResponseResultSuppliersInner,

    /**
     * The TrafficForecastingRequest model constructor.
     * @property {module:ForecastAPI/model/TrafficForecastingRequest}
     */
    TrafficForecastingRequest,

    /**
     * The TrafficForecastingRequestDataInner model constructor.
     * @property {module:ForecastAPI/model/TrafficForecastingRequestDataInner}
     */
    TrafficForecastingRequestDataInner,

    /**
     * The TrafficForecastingRequestTrafficSettings model constructor.
     * @property {module:ForecastAPI/model/TrafficForecastingRequestTrafficSettings}
     */
    TrafficForecastingRequestTrafficSettings,

    /**
     * The TrafficForecastingResponse model constructor.
     * @property {module:ForecastAPI/model/TrafficForecastingResponse}
     */
    TrafficForecastingResponse,

    /**
     * The TrafficForecastingResponseMeta model constructor.
     * @property {module:ForecastAPI/model/TrafficForecastingResponseMeta}
     */
    TrafficForecastingResponseMeta,

    /**
     * The TrafficForecastingResponseMetaTiming model constructor.
     * @property {module:ForecastAPI/model/TrafficForecastingResponseMetaTiming}
     */
    TrafficForecastingResponseMetaTiming,

    /**
     * The TrafficForecastingResponseResult model constructor.
     * @property {module:ForecastAPI/model/TrafficForecastingResponseResult}
     */
    TrafficForecastingResponseResult,

    /**
     * The TrafficForecastingResponseResultCapacityAnalysis model constructor.
     * @property {module:ForecastAPI/model/TrafficForecastingResponseResultCapacityAnalysis}
     */
    TrafficForecastingResponseResultCapacityAnalysis,

    /**
     * The TrafficForecastingResponseResultCapacityAnalysisUtilizationPeriodsInner model constructor.
     * @property {module:ForecastAPI/model/TrafficForecastingResponseResultCapacityAnalysisUtilizationPeriodsInner}
     */
    TrafficForecastingResponseResultCapacityAnalysisUtilizationPeriodsInner,

    /**
     * The TrafficForecastingResponseResultCostOptimization model constructor.
     * @property {module:ForecastAPI/model/TrafficForecastingResponseResultCostOptimization}
     */
    TrafficForecastingResponseResultCostOptimization,

    /**
     * The TrafficForecastingResponseResultCostOptimizationCostBreakdown model constructor.
     * @property {module:ForecastAPI/model/TrafficForecastingResponseResultCostOptimizationCostBreakdown}
     */
    TrafficForecastingResponseResultCostOptimizationCostBreakdown,

    /**
     * The TrafficForecastingResponseResultCostOptimizationRecommendationsInner model constructor.
     * @property {module:ForecastAPI/model/TrafficForecastingResponseResultCostOptimizationRecommendationsInner}
     */
    TrafficForecastingResponseResultCostOptimizationRecommendationsInner,

    /**
     * The TrafficForecastingResponseResultForecastDataInner model constructor.
     * @property {module:ForecastAPI/model/TrafficForecastingResponseResultForecastDataInner}
     */
    TrafficForecastingResponseResultForecastDataInner,

    /**
     * The TrafficForecastingResponseResultScalingRecommendations model constructor.
     * @property {module:ForecastAPI/model/TrafficForecastingResponseResultScalingRecommendations}
     */
    TrafficForecastingResponseResultScalingRecommendations,

    /**
     * The TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner model constructor.
     * @property {module:ForecastAPI/model/TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner}
     */
    TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner,

    /**
     * The TrafficForecastingResponseResultTrafficAlerts model constructor.
     * @property {module:ForecastAPI/model/TrafficForecastingResponseResultTrafficAlerts}
     */
    TrafficForecastingResponseResultTrafficAlerts,

    /**
     * The TrafficForecastingResponseResultTrafficAlertsAlertsInner model constructor.
     * @property {module:ForecastAPI/model/TrafficForecastingResponseResultTrafficAlertsAlertsInner}
     */
    TrafficForecastingResponseResultTrafficAlertsAlertsInner,

    /**
     * The V1AnyGet404Response model constructor.
     * @property {module:ForecastAPI/model/V1AnyGet404Response}
     */
    V1AnyGet404Response,

    /**
     * The V2ForecastPost400Response model constructor.
     * @property {module:ForecastAPI/model/V2ForecastPost400Response}
     */
    V2ForecastPost400Response,

    /**
     * The V2Get200Response model constructor.
     * @property {module:ForecastAPI/model/V2Get200Response}
     */
    V2Get200Response,

    /**
     * The V2HealthGet200Response model constructor.
     * @property {module:ForecastAPI/model/V2HealthGet200Response}
     */
    V2HealthGet200Response,

    /**
     * The V2InventoryPlanningPost400Response model constructor.
     * @property {module:ForecastAPI/model/V2InventoryPlanningPost400Response}
     */
    V2InventoryPlanningPost400Response,

    /**
     * The V2InventoryPlanningPost500Response model constructor.
     * @property {module:ForecastAPI/model/V2InventoryPlanningPost500Response}
     */
    V2InventoryPlanningPost500Response,

    /**
     * The V2TrafficForecastingPost500Response model constructor.
     * @property {module:ForecastAPI/model/V2TrafficForecastingPost500Response}
     */
    V2TrafficForecastingPost500Response,

    /**
     * The ValidationErrorResponse model constructor.
     * @property {module:ForecastAPI/model/ValidationErrorResponse}
     */
    ValidationErrorResponse,

    /**
    * The AnalysisApi service constructor.
    * @property {module:ForecastAPI/api/AnalysisApi}
    */
    AnalysisApi,

    /**
    * The DefaultApi service constructor.
    * @property {module:ForecastAPI/api/DefaultApi}
    */
    DefaultApi,

    /**
    * The ForecastingApi service constructor.
    * @property {module:ForecastAPI/api/ForecastingApi}
    */
    ForecastingApi,

    /**
    * The HealthApi service constructor.
    * @property {module:ForecastAPI/api/HealthApi}
    */
    HealthApi,

    /**
    * The InventoryPlanningApi service constructor.
    * @property {module:ForecastAPI/api/InventoryPlanningApi}
    */
    InventoryPlanningApi,

    /**
    * The TrafficForecastingApi service constructor.
    * @property {module:ForecastAPI/api/TrafficForecastingApi}
    */
    TrafficForecastingApi
};
