/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ForecastRequestDataInner from './ForecastRequestDataInner';

/**
 * The ForecastRequest model module.
 * @module ForecastAPI\ForecastSDK/model/ForecastRequest
 * @version 2.0.0
 */
class ForecastRequest {
    /**
     * Constructs a new <code>ForecastRequest</code>.
     * @alias module:ForecastAPI\ForecastSDK/model/ForecastRequest
     * @param identifier {String} SKU, Product ID, or other identifier for the data series
     * @param frequency {module:ForecastAPI\ForecastSDK/model/ForecastRequest.FrequencyEnum} Data frequency: - D: Daily - W: Weekly - M: Monthly (end of month) - MS: Monthly (start of month) - ME: Monthly (end of month) - Q: Quarterly - Y: Yearly 
     * @param dataType {String} Type of data (e.g., sales, demand, inventory, web_traffic)
     * @param periods {Number} Number of periods to forecast
     * @param data {Array.<module:ForecastAPI\ForecastSDK/model/ForecastRequestDataInner>} Historical time series data
     */
    constructor(identifier, frequency, dataType, periods, data) { 
        
        ForecastRequest.initialize(this, identifier, frequency, dataType, periods, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, identifier, frequency, dataType, periods, data) { 
        obj['identifier'] = identifier;
        obj['frequency'] = frequency;
        obj['data_type'] = dataType;
        obj['periods'] = periods;
        obj['data'] = data;
    }

    /**
     * Constructs a <code>ForecastRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:ForecastAPI\ForecastSDK/model/ForecastRequest} obj Optional instance to populate.
     * @return {module:ForecastAPI\ForecastSDK/model/ForecastRequest} The populated <code>ForecastRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ForecastRequest();

            if (data.hasOwnProperty('identifier')) {
                obj['identifier'] = ApiClient.convertToType(data['identifier'], 'String');
            }
            if (data.hasOwnProperty('frequency')) {
                obj['frequency'] = ApiClient.convertToType(data['frequency'], 'String');
            }
            if (data.hasOwnProperty('start_date')) {
                obj['start_date'] = ApiClient.convertToType(data['start_date'], 'Date');
            }
            if (data.hasOwnProperty('data_type')) {
                obj['data_type'] = ApiClient.convertToType(data['data_type'], 'String');
            }
            if (data.hasOwnProperty('periods')) {
                obj['periods'] = ApiClient.convertToType(data['periods'], 'Number');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [ForecastRequestDataInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ForecastRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ForecastRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ForecastRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['identifier'] && !(typeof data['identifier'] === 'string' || data['identifier'] instanceof String)) {
            throw new Error("Expected the field `identifier` to be a primitive type in the JSON string but got " + data['identifier']);
        }
        // ensure the json data is a string
        if (data['frequency'] && !(typeof data['frequency'] === 'string' || data['frequency'] instanceof String)) {
            throw new Error("Expected the field `frequency` to be a primitive type in the JSON string but got " + data['frequency']);
        }
        // ensure the json data is a string
        if (data['data_type'] && !(typeof data['data_type'] === 'string' || data['data_type'] instanceof String)) {
            throw new Error("Expected the field `data_type` to be a primitive type in the JSON string but got " + data['data_type']);
        }
        if (data['data']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['data'])) {
                throw new Error("Expected the field `data` to be an array in the JSON data but got " + data['data']);
            }
            // validate the optional field `data` (array)
            for (const item of data['data']) {
                ForecastRequestDataInner.validateJSON(item);
            };
        }

        return true;
    }


}

ForecastRequest.RequiredProperties = ["identifier", "frequency", "data_type", "periods", "data"];

/**
 * SKU, Product ID, or other identifier for the data series
 * @member {String} identifier
 */
ForecastRequest.prototype['identifier'] = undefined;

/**
 * Data frequency: - D: Daily - W: Weekly - M: Monthly (end of month) - MS: Monthly (start of month) - ME: Monthly (end of month) - Q: Quarterly - Y: Yearly 
 * @member {module:ForecastAPI\ForecastSDK/model/ForecastRequest.FrequencyEnum} frequency
 */
ForecastRequest.prototype['frequency'] = undefined;

/**
 * Optional start date for the forecast
 * @member {Date} start_date
 */
ForecastRequest.prototype['start_date'] = undefined;

/**
 * Type of data (e.g., sales, demand, inventory, web_traffic)
 * @member {String} data_type
 */
ForecastRequest.prototype['data_type'] = undefined;

/**
 * Number of periods to forecast
 * @member {Number} periods
 */
ForecastRequest.prototype['periods'] = undefined;

/**
 * Historical time series data
 * @member {Array.<module:ForecastAPI\ForecastSDK/model/ForecastRequestDataInner>} data
 */
ForecastRequest.prototype['data'] = undefined;





/**
 * Allowed values for the <code>frequency</code> property.
 * @enum {String}
 * @readonly
 */
ForecastRequest['FrequencyEnum'] = {

    /**
     * value: "D"
     * @const
     */
    "D": "D",

    /**
     * value: "W"
     * @const
     */
    "W": "W",

    /**
     * value: "M"
     * @const
     */
    "M": "M",

    /**
     * value: "MS"
     * @const
     */
    "MS": "MS",

    /**
     * value: "ME"
     * @const
     */
    "ME": "ME",

    /**
     * value: "Q"
     * @const
     */
    "Q": "Q",

    /**
     * value: "Y"
     * @const
     */
    "Y": "Y"
};



export default ForecastRequest;

