/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ForecastResponseResult model module.
 * @module ForecastAPI\ForecastSDK/model/ForecastResponseResult
 * @version 2.0.0
 */
class ForecastResponseResult {
    /**
     * Constructs a new <code>ForecastResponseResult</code>.
     * @alias module:ForecastAPI\ForecastSDK/model/ForecastResponseResult
     */
    constructor() { 
        
        ForecastResponseResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ForecastResponseResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:ForecastAPI\ForecastSDK/model/ForecastResponseResult} obj Optional instance to populate.
     * @return {module:ForecastAPI\ForecastSDK/model/ForecastResponseResult} The populated <code>ForecastResponseResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ForecastResponseResult();

            if (data.hasOwnProperty('forecast_value')) {
                obj['forecast_value'] = ApiClient.convertToType(data['forecast_value'], 'Number');
            }
            if (data.hasOwnProperty('confidence_lower')) {
                obj['confidence_lower'] = ApiClient.convertToType(data['confidence_lower'], 'Number');
            }
            if (data.hasOwnProperty('confidence_upper')) {
                obj['confidence_upper'] = ApiClient.convertToType(data['confidence_upper'], 'Number');
            }
            if (data.hasOwnProperty('method_used')) {
                obj['method_used'] = ApiClient.convertToType(data['method_used'], 'String');
            }
            if (data.hasOwnProperty('forecast_dates')) {
                obj['forecast_dates'] = ApiClient.convertToType(data['forecast_dates'], ['Date']);
            }
            if (data.hasOwnProperty('forecast_values')) {
                obj['forecast_values'] = ApiClient.convertToType(data['forecast_values'], ['Number']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ForecastResponseResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ForecastResponseResult</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['method_used'] && !(typeof data['method_used'] === 'string' || data['method_used'] instanceof String)) {
            throw new Error("Expected the field `method_used` to be a primitive type in the JSON string but got " + data['method_used']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['forecast_dates'])) {
            throw new Error("Expected the field `forecast_dates` to be an array in the JSON data but got " + data['forecast_dates']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['forecast_values'])) {
            throw new Error("Expected the field `forecast_values` to be an array in the JSON data but got " + data['forecast_values']);
        }

        return true;
    }


}



/**
 * @member {Number} forecast_value
 */
ForecastResponseResult.prototype['forecast_value'] = undefined;

/**
 * @member {Number} confidence_lower
 */
ForecastResponseResult.prototype['confidence_lower'] = undefined;

/**
 * @member {Number} confidence_upper
 */
ForecastResponseResult.prototype['confidence_upper'] = undefined;

/**
 * @member {String} method_used
 */
ForecastResponseResult.prototype['method_used'] = undefined;

/**
 * @member {Array.<Date>} forecast_dates
 */
ForecastResponseResult.prototype['forecast_dates'] = undefined;

/**
 * @member {Array.<Number>} forecast_values
 */
ForecastResponseResult.prototype['forecast_values'] = undefined;






export default ForecastResponseResult;

