/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InventoryPlanningResponseResultStockAnalysis model module.
 * @module ForecastAPI\ForecastSDK/model/InventoryPlanningResponseResultStockAnalysis
 * @version 2.0.0
 */
class InventoryPlanningResponseResultStockAnalysis {
    /**
     * Constructs a new <code>InventoryPlanningResponseResultStockAnalysis</code>.
     * Current stock situation analysis
     * @alias module:ForecastAPI\ForecastSDK/model/InventoryPlanningResponseResultStockAnalysis
     */
    constructor() { 
        
        InventoryPlanningResponseResultStockAnalysis.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InventoryPlanningResponseResultStockAnalysis</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:ForecastAPI\ForecastSDK/model/InventoryPlanningResponseResultStockAnalysis} obj Optional instance to populate.
     * @return {module:ForecastAPI\ForecastSDK/model/InventoryPlanningResponseResultStockAnalysis} The populated <code>InventoryPlanningResponseResultStockAnalysis</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InventoryPlanningResponseResultStockAnalysis();

            if (data.hasOwnProperty('days_of_coverage')) {
                obj['days_of_coverage'] = ApiClient.convertToType(data['days_of_coverage'], 'Number');
            }
            if (data.hasOwnProperty('stockout_risk')) {
                obj['stockout_risk'] = ApiClient.convertToType(data['stockout_risk'], 'Number');
            }
            if (data.hasOwnProperty('next_order_date')) {
                obj['next_order_date'] = ApiClient.convertToType(data['next_order_date'], 'Date');
            }
            if (data.hasOwnProperty('daily_demand_rate')) {
                obj['daily_demand_rate'] = ApiClient.convertToType(data['daily_demand_rate'], 'Number');
            }
            if (data.hasOwnProperty('stock_status')) {
                obj['stock_status'] = ApiClient.convertToType(data['stock_status'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InventoryPlanningResponseResultStockAnalysis</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InventoryPlanningResponseResultStockAnalysis</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['stock_status'] && !(typeof data['stock_status'] === 'string' || data['stock_status'] instanceof String)) {
            throw new Error("Expected the field `stock_status` to be a primitive type in the JSON string but got " + data['stock_status']);
        }

        return true;
    }


}



/**
 * Number of days current stock will last
 * @member {Number} days_of_coverage
 */
InventoryPlanningResponseResultStockAnalysis.prototype['days_of_coverage'] = undefined;

/**
 * Risk of stockout (0-1, where 1 is certain stockout)
 * @member {Number} stockout_risk
 */
InventoryPlanningResponseResultStockAnalysis.prototype['stockout_risk'] = undefined;

/**
 * Recommended date for next order
 * @member {Date} next_order_date
 */
InventoryPlanningResponseResultStockAnalysis.prototype['next_order_date'] = undefined;

/**
 * Average daily demand rate
 * @member {Number} daily_demand_rate
 */
InventoryPlanningResponseResultStockAnalysis.prototype['daily_demand_rate'] = undefined;

/**
 * Current stock status assessment
 * @member {module:ForecastAPI\ForecastSDK/model/InventoryPlanningResponseResultStockAnalysis.StockStatusEnum} stock_status
 */
InventoryPlanningResponseResultStockAnalysis.prototype['stock_status'] = undefined;





/**
 * Allowed values for the <code>stock_status</code> property.
 * @enum {String}
 * @readonly
 */
InventoryPlanningResponseResultStockAnalysis['StockStatusEnum'] = {

    /**
     * value: "critical"
     * @const
     */
    "critical": "critical",

    /**
     * value: "reorder_needed"
     * @const
     */
    "reorder_needed": "reorder_needed",

    /**
     * value: "low"
     * @const
     */
    "low": "low",

    /**
     * value: "adequate"
     * @const
     */
    "adequate": "adequate"
};



export default InventoryPlanningResponseResultStockAnalysis;

