/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InventoryPlanningResponseMetaTiming model module.
 * @module ForecastAPI\ForecastSDK/model/InventoryPlanningResponseMetaTiming
 * @version 2.0.0
 */
class InventoryPlanningResponseMetaTiming {
    /**
     * Constructs a new <code>InventoryPlanningResponseMetaTiming</code>.
     * @alias module:ForecastAPI\ForecastSDK/model/InventoryPlanningResponseMetaTiming
     */
    constructor() { 
        
        InventoryPlanningResponseMetaTiming.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InventoryPlanningResponseMetaTiming</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:ForecastAPI\ForecastSDK/model/InventoryPlanningResponseMetaTiming} obj Optional instance to populate.
     * @return {module:ForecastAPI\ForecastSDK/model/InventoryPlanningResponseMetaTiming} The populated <code>InventoryPlanningResponseMetaTiming</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InventoryPlanningResponseMetaTiming();

            if (data.hasOwnProperty('validation')) {
                obj['validation'] = ApiClient.convertToType(data['validation'], 'Number');
            }
            if (data.hasOwnProperty('planning')) {
                obj['planning'] = ApiClient.convertToType(data['planning'], 'Number');
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InventoryPlanningResponseMetaTiming</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InventoryPlanningResponseMetaTiming</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Time taken for request validation in milliseconds
 * @member {Number} validation
 */
InventoryPlanningResponseMetaTiming.prototype['validation'] = undefined;

/**
 * Time taken for inventory planning in milliseconds
 * @member {Number} planning
 */
InventoryPlanningResponseMetaTiming.prototype['planning'] = undefined;

/**
 * Total processing time in milliseconds
 * @member {Number} total
 */
InventoryPlanningResponseMetaTiming.prototype['total'] = undefined;






export default InventoryPlanningResponseMetaTiming;

