/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TrafficForecastingRequestDataInner model module.
 * @module ForecastAPI\ForecastSDK/model/TrafficForecastingRequestDataInner
 * @version 2.0.0
 */
class TrafficForecastingRequestDataInner {
    /**
     * Constructs a new <code>TrafficForecastingRequestDataInner</code>.
     * @alias module:ForecastAPI\ForecastSDK/model/TrafficForecastingRequestDataInner
     * @param date {String} Date/time of the data point (supports both date and datetime formats)
     * @param value {Number} Traffic volume for the period
     */
    constructor(date, value) { 
        
        TrafficForecastingRequestDataInner.initialize(this, date, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, date, value) { 
        obj['date'] = date;
        obj['value'] = value;
    }

    /**
     * Constructs a <code>TrafficForecastingRequestDataInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:ForecastAPI\ForecastSDK/model/TrafficForecastingRequestDataInner} obj Optional instance to populate.
     * @return {module:ForecastAPI\ForecastSDK/model/TrafficForecastingRequestDataInner} The populated <code>TrafficForecastingRequestDataInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TrafficForecastingRequestDataInner();

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TrafficForecastingRequestDataInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TrafficForecastingRequestDataInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TrafficForecastingRequestDataInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['date'] && !(typeof data['date'] === 'string' || data['date'] instanceof String)) {
            throw new Error("Expected the field `date` to be a primitive type in the JSON string but got " + data['date']);
        }

        return true;
    }


}

TrafficForecastingRequestDataInner.RequiredProperties = ["date", "value"];

/**
 * Date/time of the data point (supports both date and datetime formats)
 * @member {String} date
 */
TrafficForecastingRequestDataInner.prototype['date'] = undefined;

/**
 * Traffic volume for the period
 * @member {Number} value
 */
TrafficForecastingRequestDataInner.prototype['value'] = undefined;






export default TrafficForecastingRequestDataInner;

