/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ForecastAPI);
  }
}(this, function(expect, ForecastAPI) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ForecastAPI.AccumulatedForecast();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AccumulatedForecast', function() {
    it('should create an instance of AccumulatedForecast', function() {
      // uncomment below and update the code to test AccumulatedForecast
      //var instance = new ForecastAPI.AccumulatedForecast();
      //expect(instance).to.be.a(ForecastAPI.AccumulatedForecast);
    });

    it('should have the property total (base name: "total")', function() {
      // uncomment below and update the code to test the property total
      //var instance = new ForecastAPI.AccumulatedForecast();
      //expect(instance).to.be();
    });

    it('should have the property totalReason (base name: "total_reason")', function() {
      // uncomment below and update the code to test the property totalReason
      //var instance = new ForecastAPI.AccumulatedForecast();
      //expect(instance).to.be();
    });

    it('should have the property lower (base name: "lower")', function() {
      // uncomment below and update the code to test the property lower
      //var instance = new ForecastAPI.AccumulatedForecast();
      //expect(instance).to.be();
    });

    it('should have the property upper (base name: "upper")', function() {
      // uncomment below and update the code to test the property upper
      //var instance = new ForecastAPI.AccumulatedForecast();
      //expect(instance).to.be();
    });

    it('should have the property intervalReason (base name: "interval_reason")', function() {
      // uncomment below and update the code to test the property intervalReason
      //var instance = new ForecastAPI.AccumulatedForecast();
      //expect(instance).to.be();
    });

    it('should have the property confidenceLevel (base name: "confidence_level")', function() {
      // uncomment below and update the code to test the property confidenceLevel
      //var instance = new ForecastAPI.AccumulatedForecast();
      //expect(instance).to.be();
    });

    it('should have the property path (base name: "path")', function() {
      // uncomment below and update the code to test the property path
      //var instance = new ForecastAPI.AccumulatedForecast();
      //expect(instance).to.be();
    });

    it('should have the property assumptions (base name: "assumptions")', function() {
      // uncomment below and update the code to test the property assumptions
      //var instance = new ForecastAPI.AccumulatedForecast();
      //expect(instance).to.be();
    });

    it('should have the property byPeriod (base name: "by_period")', function() {
      // uncomment below and update the code to test the property byPeriod
      //var instance = new ForecastAPI.AccumulatedForecast();
      //expect(instance).to.be();
    });

  });

}));
