/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.4
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ForecastAPI);
  }
}(this, function(expect, ForecastAPI) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ForecastAPI.AdjustedForecast();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AdjustedForecast', function() {
    it('should create an instance of AdjustedForecast', function() {
      // uncomment below and update the code to test AdjustedForecast
      //var instance = new ForecastAPI.AdjustedForecast();
      //expect(instance).to.be.a(ForecastAPI.AdjustedForecast);
    });

    it('should have the property forecasts (base name: "forecasts")', function() {
      // uncomment below and update the code to test the property forecasts
      //var instance = new ForecastAPI.AdjustedForecast();
      //expect(instance).to.be();
    });

    it('should have the property adjustmentsApplied (base name: "adjustments_applied")', function() {
      // uncomment below and update the code to test the property adjustmentsApplied
      //var instance = new ForecastAPI.AdjustedForecast();
      //expect(instance).to.be();
    });

    it('should have the property stored (base name: "stored")', function() {
      // uncomment below and update the code to test the property stored
      //var instance = new ForecastAPI.AdjustedForecast();
      //expect(instance).to.be();
    });

  });

}));
