/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ForecastAPI);
  }
}(this, function(expect, ForecastAPI) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ForecastAPI.AnalysisResponseResultCharacteristics();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AnalysisResponseResultCharacteristics', function() {
    it('should create an instance of AnalysisResponseResultCharacteristics', function() {
      // uncomment below and update the code to test AnalysisResponseResultCharacteristics
      //var instance = new ForecastAPI.AnalysisResponseResultCharacteristics();
      //expect(instance).to.be.a(ForecastAPI.AnalysisResponseResultCharacteristics);
    });

    it('should have the property totalPeriods (base name: "total_periods")', function() {
      // uncomment below and update the code to test the property totalPeriods
      //var instance = new ForecastAPI.AnalysisResponseResultCharacteristics();
      //expect(instance).to.be();
    });

    it('should have the property nonZeroEvents (base name: "non_zero_events")', function() {
      // uncomment below and update the code to test the property nonZeroEvents
      //var instance = new ForecastAPI.AnalysisResponseResultCharacteristics();
      //expect(instance).to.be();
    });

    it('should have the property meanValue (base name: "mean_value")', function() {
      // uncomment below and update the code to test the property meanValue
      //var instance = new ForecastAPI.AnalysisResponseResultCharacteristics();
      //expect(instance).to.be();
    });

    it('should have the property stdDeviation (base name: "std_deviation")', function() {
      // uncomment below and update the code to test the property stdDeviation
      //var instance = new ForecastAPI.AnalysisResponseResultCharacteristics();
      //expect(instance).to.be();
    });

    it('should have the property trendStrength (base name: "trend_strength")', function() {
      // uncomment below and update the code to test the property trendStrength
      //var instance = new ForecastAPI.AnalysisResponseResultCharacteristics();
      //expect(instance).to.be();
    });

    it('should have the property seasonalityDetected (base name: "seasonality_detected")', function() {
      // uncomment below and update the code to test the property seasonalityDetected
      //var instance = new ForecastAPI.AnalysisResponseResultCharacteristics();
      //expect(instance).to.be();
    });

  });

}));
