/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ForecastAPI);
  }
}(this, function(expect, ForecastAPI) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ForecastAPI.AnomalyDetectionResponseResultAnomaliesInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AnomalyDetectionResponseResultAnomaliesInner', function() {
    it('should create an instance of AnomalyDetectionResponseResultAnomaliesInner', function() {
      // uncomment below and update the code to test AnomalyDetectionResponseResultAnomaliesInner
      //var instance = new ForecastAPI.AnomalyDetectionResponseResultAnomaliesInner();
      //expect(instance).to.be.a(ForecastAPI.AnomalyDetectionResponseResultAnomaliesInner);
    });

    it('should have the property index (base name: "index")', function() {
      // uncomment below and update the code to test the property index
      //var instance = new ForecastAPI.AnomalyDetectionResponseResultAnomaliesInner();
      //expect(instance).to.be();
    });

    it('should have the property date (base name: "date")', function() {
      // uncomment below and update the code to test the property date
      //var instance = new ForecastAPI.AnomalyDetectionResponseResultAnomaliesInner();
      //expect(instance).to.be();
    });

    it('should have the property value (base name: "value")', function() {
      // uncomment below and update the code to test the property value
      //var instance = new ForecastAPI.AnomalyDetectionResponseResultAnomaliesInner();
      //expect(instance).to.be();
    });

    it('should have the property expectedRange (base name: "expected_range")', function() {
      // uncomment below and update the code to test the property expectedRange
      //var instance = new ForecastAPI.AnomalyDetectionResponseResultAnomaliesInner();
      //expect(instance).to.be();
    });

    it('should have the property severity (base name: "severity")', function() {
      // uncomment below and update the code to test the property severity
      //var instance = new ForecastAPI.AnomalyDetectionResponseResultAnomaliesInner();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new ForecastAPI.AnomalyDetectionResponseResultAnomaliesInner();
      //expect(instance).to.be();
    });

  });

}));
