/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.4
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ForecastAPI);
  }
}(this, function(expect, ForecastAPI) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ForecastAPI.AnomalyDetectionRequestAllOfAnomalySettings();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AnomalyDetectionRequestAllOfAnomalySettings', function() {
    it('should create an instance of AnomalyDetectionRequestAllOfAnomalySettings', function() {
      // uncomment below and update the code to test AnomalyDetectionRequestAllOfAnomalySettings
      //var instance = new ForecastAPI.AnomalyDetectionRequestAllOfAnomalySettings();
      //expect(instance).to.be.a(ForecastAPI.AnomalyDetectionRequestAllOfAnomalySettings);
    });

    it('should have the property method (base name: "method")', function() {
      // uncomment below and update the code to test the property method
      //var instance = new ForecastAPI.AnomalyDetectionRequestAllOfAnomalySettings();
      //expect(instance).to.be();
    });

    it('should have the property threshold (base name: "threshold")', function() {
      // uncomment below and update the code to test the property threshold
      //var instance = new ForecastAPI.AnomalyDetectionRequestAllOfAnomalySettings();
      //expect(instance).to.be();
    });

    it('should have the property multiplier (base name: "multiplier")', function() {
      // uncomment below and update the code to test the property multiplier
      //var instance = new ForecastAPI.AnomalyDetectionRequestAllOfAnomalySettings();
      //expect(instance).to.be();
    });

    it('should have the property seasonalPeriod (base name: "seasonal_period")', function() {
      // uncomment below and update the code to test the property seasonalPeriod
      //var instance = new ForecastAPI.AnomalyDetectionRequestAllOfAnomalySettings();
      //expect(instance).to.be();
    });

    it('should have the property minimumPeriods (base name: "minimum_periods")', function() {
      // uncomment below and update the code to test the property minimumPeriods
      //var instance = new ForecastAPI.AnomalyDetectionRequestAllOfAnomalySettings();
      //expect(instance).to.be();
    });

  });

}));
