/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ForecastAPI);
  }
}(this, function(expect, ForecastAPI) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ForecastAPI.CreateTrafficForecast500Response();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreateTrafficForecast500Response', function() {
    it('should create an instance of CreateTrafficForecast500Response', function() {
      // uncomment below and update the code to test CreateTrafficForecast500Response
      //var instance = new ForecastAPI.CreateTrafficForecast500Response();
      //expect(instance).to.be.a(ForecastAPI.CreateTrafficForecast500Response);
    });

    it('should have the property error (base name: "error")', function() {
      // uncomment below and update the code to test the property error
      //var instance = new ForecastAPI.CreateTrafficForecast500Response();
      //expect(instance).to.be();
    });

    it('should have the property timeTakenMs (base name: "time_taken_ms")', function() {
      // uncomment below and update the code to test the property timeTakenMs
      //var instance = new ForecastAPI.CreateTrafficForecast500Response();
      //expect(instance).to.be();
    });

  });

}));
