/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ForecastAPI);
  }
}(this, function(expect, ForecastAPI) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ForecastAPI.GroupedForecastRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GroupedForecastRequest', function() {
    it('should create an instance of GroupedForecastRequest', function() {
      // uncomment below and update the code to test GroupedForecastRequest
      //var instance = new ForecastAPI.GroupedForecastRequest();
      //expect(instance).to.be.a(ForecastAPI.GroupedForecastRequest);
    });

    it('should have the property identifier (base name: "identifier")', function() {
      // uncomment below and update the code to test the property identifier
      //var instance = new ForecastAPI.GroupedForecastRequest();
      //expect(instance).to.be();
    });

    it('should have the property tenantContext (base name: "tenant_context")', function() {
      // uncomment below and update the code to test the property tenantContext
      //var instance = new ForecastAPI.GroupedForecastRequest();
      //expect(instance).to.be();
    });

    it('should have the property hierarchy (base name: "hierarchy")', function() {
      // uncomment below and update the code to test the property hierarchy
      //var instance = new ForecastAPI.GroupedForecastRequest();
      //expect(instance).to.be();
    });

    it('should have the property reconciliation (base name: "reconciliation")', function() {
      // uncomment below and update the code to test the property reconciliation
      //var instance = new ForecastAPI.GroupedForecastRequest();
      //expect(instance).to.be();
    });

    it('should have the property correlation (base name: "correlation")', function() {
      // uncomment below and update the code to test the property correlation
      //var instance = new ForecastAPI.GroupedForecastRequest();
      //expect(instance).to.be();
    });

    it('should have the property frequency (base name: "frequency")', function() {
      // uncomment below and update the code to test the property frequency
      //var instance = new ForecastAPI.GroupedForecastRequest();
      //expect(instance).to.be();
    });

    it('should have the property periods (base name: "periods")', function() {
      // uncomment below and update the code to test the property periods
      //var instance = new ForecastAPI.GroupedForecastRequest();
      //expect(instance).to.be();
    });

    it('should have the property dataType (base name: "data_type")', function() {
      // uncomment below and update the code to test the property dataType
      //var instance = new ForecastAPI.GroupedForecastRequest();
      //expect(instance).to.be();
    });

    it('should have the property model (base name: "model")', function() {
      // uncomment below and update the code to test the property model
      //var instance = new ForecastAPI.GroupedForecastRequest();
      //expect(instance).to.be();
    });

    it('should have the property confidence (base name: "confidence")', function() {
      // uncomment below and update the code to test the property confidence
      //var instance = new ForecastAPI.GroupedForecastRequest();
      //expect(instance).to.be();
    });

    it('should have the property confidenceLevel (base name: "confidence_level")', function() {
      // uncomment below and update the code to test the property confidenceLevel
      //var instance = new ForecastAPI.GroupedForecastRequest();
      //expect(instance).to.be();
    });

    it('should have the property series (base name: "series")', function() {
      // uncomment below and update the code to test the property series
      //var instance = new ForecastAPI.GroupedForecastRequest();
      //expect(instance).to.be();
    });

  });

}));
