/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ForecastAPI);
  }
}(this, function(expect, ForecastAPI) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ForecastAPI.ProductInsightsRequestPurchasesInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProductInsightsRequestPurchasesInner', function() {
    it('should create an instance of ProductInsightsRequestPurchasesInner', function() {
      // uncomment below and update the code to test ProductInsightsRequestPurchasesInner
      //var instance = new ForecastAPI.ProductInsightsRequestPurchasesInner();
      //expect(instance).to.be.a(ForecastAPI.ProductInsightsRequestPurchasesInner);
    });

    it('should have the property date (base name: "date")', function() {
      // uncomment below and update the code to test the property date
      //var instance = new ForecastAPI.ProductInsightsRequestPurchasesInner();
      //expect(instance).to.be();
    });

    it('should have the property quantityPurchased (base name: "quantity_purchased")', function() {
      // uncomment below and update the code to test the property quantityPurchased
      //var instance = new ForecastAPI.ProductInsightsRequestPurchasesInner();
      //expect(instance).to.be();
    });

    it('should have the property costPrice (base name: "cost_price")', function() {
      // uncomment below and update the code to test the property costPrice
      //var instance = new ForecastAPI.ProductInsightsRequestPurchasesInner();
      //expect(instance).to.be();
    });

    it('should have the property costPriceConverted (base name: "cost_price_converted")', function() {
      // uncomment below and update the code to test the property costPriceConverted
      //var instance = new ForecastAPI.ProductInsightsRequestPurchasesInner();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instance = new ForecastAPI.ProductInsightsRequestPurchasesInner();
      //expect(instance).to.be();
    });

    it('should have the property supplierId (base name: "supplier_id")', function() {
      // uncomment below and update the code to test the property supplierId
      //var instance = new ForecastAPI.ProductInsightsRequestPurchasesInner();
      //expect(instance).to.be();
    });

    it('should have the property purchaseOrderDate (base name: "purchase_order_date")', function() {
      // uncomment below and update the code to test the property purchaseOrderDate
      //var instance = new ForecastAPI.ProductInsightsRequestPurchasesInner();
      //expect(instance).to.be();
    });

    it('should have the property expectedDeliveryDate (base name: "expected_delivery_date")', function() {
      // uncomment below and update the code to test the property expectedDeliveryDate
      //var instance = new ForecastAPI.ProductInsightsRequestPurchasesInner();
      //expect(instance).to.be();
    });

    it('should have the property actualDeliveryDate (base name: "actual_delivery_date")', function() {
      // uncomment below and update the code to test the property actualDeliveryDate
      //var instance = new ForecastAPI.ProductInsightsRequestPurchasesInner();
      //expect(instance).to.be();
    });

  });

}));
