/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ForecastAPI);
  }
}(this, function(expect, ForecastAPI) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ForecastAPI.ProductInsightsResponseResult();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProductInsightsResponseResult', function() {
    it('should create an instance of ProductInsightsResponseResult', function() {
      // uncomment below and update the code to test ProductInsightsResponseResult
      //var instance = new ForecastAPI.ProductInsightsResponseResult();
      //expect(instance).to.be.a(ForecastAPI.ProductInsightsResponseResult);
    });

    it('should have the property identifier (base name: "identifier")', function() {
      // uncomment below and update the code to test the property identifier
      //var instance = new ForecastAPI.ProductInsightsResponseResult();
      //expect(instance).to.be();
    });

    it('should have the property tenantContext (base name: "tenant_context")', function() {
      // uncomment below and update the code to test the property tenantContext
      //var instance = new ForecastAPI.ProductInsightsResponseResult();
      //expect(instance).to.be();
    });

    it('should have the property productInfo (base name: "product_info")', function() {
      // uncomment below and update the code to test the property productInfo
      //var instance = new ForecastAPI.ProductInsightsResponseResult();
      //expect(instance).to.be();
    });

    it('should have the property baseCurrency (base name: "base_currency")', function() {
      // uncomment below and update the code to test the property baseCurrency
      //var instance = new ForecastAPI.ProductInsightsResponseResult();
      //expect(instance).to.be();
    });

    it('should have the property insights (base name: "insights")', function() {
      // uncomment below and update the code to test the property insights
      //var instance = new ForecastAPI.ProductInsightsResponseResult();
      //expect(instance).to.be();
    });

    it('should have the property summary (base name: "summary")', function() {
      // uncomment below and update the code to test the property summary
      //var instance = new ForecastAPI.ProductInsightsResponseResult();
      //expect(instance).to.be();
    });

    it('should have the property comparison (base name: "comparison")', function() {
      // uncomment below and update the code to test the property comparison
      //var instance = new ForecastAPI.ProductInsightsResponseResult();
      //expect(instance).to.be();
    });

  });

}));
