/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ForecastAPI);
  }
}(this, function(expect, ForecastAPI) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ForecastAPI.ProductInsightsRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProductInsightsRequest', function() {
    it('should create an instance of ProductInsightsRequest', function() {
      // uncomment below and update the code to test ProductInsightsRequest
      //var instance = new ForecastAPI.ProductInsightsRequest();
      //expect(instance).to.be.a(ForecastAPI.ProductInsightsRequest);
    });

    it('should have the property identifier (base name: "identifier")', function() {
      // uncomment below and update the code to test the property identifier
      //var instance = new ForecastAPI.ProductInsightsRequest();
      //expect(instance).to.be();
    });

    it('should have the property tenantContext (base name: "tenant_context")', function() {
      // uncomment below and update the code to test the property tenantContext
      //var instance = new ForecastAPI.ProductInsightsRequest();
      //expect(instance).to.be();
    });

    it('should have the property productName (base name: "product_name")', function() {
      // uncomment below and update the code to test the property productName
      //var instance = new ForecastAPI.ProductInsightsRequest();
      //expect(instance).to.be();
    });

    it('should have the property productGroupId (base name: "product_group_id")', function() {
      // uncomment below and update the code to test the property productGroupId
      //var instance = new ForecastAPI.ProductInsightsRequest();
      //expect(instance).to.be();
    });

    it('should have the property baseCurrency (base name: "base_currency")', function() {
      // uncomment below and update the code to test the property baseCurrency
      //var instance = new ForecastAPI.ProductInsightsRequest();
      //expect(instance).to.be();
    });

    it('should have the property baselinePeriodDays (base name: "baseline_period_days")', function() {
      // uncomment below and update the code to test the property baselinePeriodDays
      //var instance = new ForecastAPI.ProductInsightsRequest();
      //expect(instance).to.be();
    });

    it('should have the property locale (base name: "locale")', function() {
      // uncomment below and update the code to test the property locale
      //var instance = new ForecastAPI.ProductInsightsRequest();
      //expect(instance).to.be();
    });

    it('should have the property sales (base name: "sales")', function() {
      // uncomment below and update the code to test the property sales
      //var instance = new ForecastAPI.ProductInsightsRequest();
      //expect(instance).to.be();
    });

    it('should have the property purchases (base name: "purchases")', function() {
      // uncomment below and update the code to test the property purchases
      //var instance = new ForecastAPI.ProductInsightsRequest();
      //expect(instance).to.be();
    });

    it('should have the property costHistory (base name: "cost_history")', function() {
      // uncomment below and update the code to test the property costHistory
      //var instance = new ForecastAPI.ProductInsightsRequest();
      //expect(instance).to.be();
    });

    it('should have the property insightSettings (base name: "insight_settings")', function() {
      // uncomment below and update the code to test the property insightSettings
      //var instance = new ForecastAPI.ProductInsightsRequest();
      //expect(instance).to.be();
    });

  });

}));
