/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ForecastAPI);
  }
}(this, function(expect, ForecastAPI) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ForecastAPI.TrafficForecastingResponseResultForecastDataInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TrafficForecastingResponseResultForecastDataInner', function() {
    it('should create an instance of TrafficForecastingResponseResultForecastDataInner', function() {
      // uncomment below and update the code to test TrafficForecastingResponseResultForecastDataInner
      //var instance = new ForecastAPI.TrafficForecastingResponseResultForecastDataInner();
      //expect(instance).to.be.a(ForecastAPI.TrafficForecastingResponseResultForecastDataInner);
    });

    it('should have the property period (base name: "period")', function() {
      // uncomment below and update the code to test the property period
      //var instance = new ForecastAPI.TrafficForecastingResponseResultForecastDataInner();
      //expect(instance).to.be();
    });

    it('should have the property date (base name: "date")', function() {
      // uncomment below and update the code to test the property date
      //var instance = new ForecastAPI.TrafficForecastingResponseResultForecastDataInner();
      //expect(instance).to.be();
    });

    it('should have the property forecast (base name: "forecast")', function() {
      // uncomment below and update the code to test the property forecast
      //var instance = new ForecastAPI.TrafficForecastingResponseResultForecastDataInner();
      //expect(instance).to.be();
    });

    it('should have the property lower (base name: "lower")', function() {
      // uncomment below and update the code to test the property lower
      //var instance = new ForecastAPI.TrafficForecastingResponseResultForecastDataInner();
      //expect(instance).to.be();
    });

    it('should have the property upper (base name: "upper")', function() {
      // uncomment below and update the code to test the property upper
      //var instance = new ForecastAPI.TrafficForecastingResponseResultForecastDataInner();
      //expect(instance).to.be();
    });

  });

}));
