/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.4
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ForecastAPI);
  }
}(this, function(expect, ForecastAPI) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ForecastAPI.TrafficForecastingRequestTrafficSettings();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TrafficForecastingRequestTrafficSettings', function() {
    it('should create an instance of TrafficForecastingRequestTrafficSettings', function() {
      // uncomment below and update the code to test TrafficForecastingRequestTrafficSettings
      //var instance = new ForecastAPI.TrafficForecastingRequestTrafficSettings();
      //expect(instance).to.be.a(ForecastAPI.TrafficForecastingRequestTrafficSettings);
    });

    it('should have the property currentCapacity (base name: "current_capacity")', function() {
      // uncomment below and update the code to test the property currentCapacity
      //var instance = new ForecastAPI.TrafficForecastingRequestTrafficSettings();
      //expect(instance).to.be();
    });

    it('should have the property baselineTraffic (base name: "baseline_traffic")', function() {
      // uncomment below and update the code to test the property baselineTraffic
      //var instance = new ForecastAPI.TrafficForecastingRequestTrafficSettings();
      //expect(instance).to.be();
    });

    it('should have the property scalingBuffer (base name: "scaling_buffer")', function() {
      // uncomment below and update the code to test the property scalingBuffer
      //var instance = new ForecastAPI.TrafficForecastingRequestTrafficSettings();
      //expect(instance).to.be();
    });

    it('should have the property scaleUpThreshold (base name: "scale_up_threshold")', function() {
      // uncomment below and update the code to test the property scaleUpThreshold
      //var instance = new ForecastAPI.TrafficForecastingRequestTrafficSettings();
      //expect(instance).to.be();
    });

    it('should have the property scaleDownThreshold (base name: "scale_down_threshold")', function() {
      // uncomment below and update the code to test the property scaleDownThreshold
      //var instance = new ForecastAPI.TrafficForecastingRequestTrafficSettings();
      //expect(instance).to.be();
    });

    it('should have the property alertThreshold (base name: "alert_threshold")', function() {
      // uncomment below and update the code to test the property alertThreshold
      //var instance = new ForecastAPI.TrafficForecastingRequestTrafficSettings();
      //expect(instance).to.be();
    });

    it('should have the property anomalyThreshold (base name: "anomaly_threshold")', function() {
      // uncomment below and update the code to test the property anomalyThreshold
      //var instance = new ForecastAPI.TrafficForecastingRequestTrafficSettings();
      //expect(instance).to.be();
    });

    it('should have the property costPerUnit (base name: "cost_per_unit")', function() {
      // uncomment below and update the code to test the property costPerUnit
      //var instance = new ForecastAPI.TrafficForecastingRequestTrafficSettings();
      //expect(instance).to.be();
    });

    it('should have the property fixedCostPerCapacity (base name: "fixed_cost_per_capacity")', function() {
      // uncomment below and update the code to test the property fixedCostPerCapacity
      //var instance = new ForecastAPI.TrafficForecastingRequestTrafficSettings();
      //expect(instance).to.be();
    });

    it('should have the property baseScalingTime (base name: "base_scaling_time")', function() {
      // uncomment below and update the code to test the property baseScalingTime
      //var instance = new ForecastAPI.TrafficForecastingRequestTrafficSettings();
      //expect(instance).to.be();
    });

    it('should have the property enableAutoScaling (base name: "enable_auto_scaling")', function() {
      // uncomment below and update the code to test the property enableAutoScaling
      //var instance = new ForecastAPI.TrafficForecastingRequestTrafficSettings();
      //expect(instance).to.be();
    });

  });

}));
