/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.2
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AccumulateOptions from './model/AccumulateOptions';
import AccumulatedForecast from './model/AccumulatedForecast';
import AccumulatedForecastAssumptions from './model/AccumulatedForecastAssumptions';
import AccumulatedForecastByPeriodInner from './model/AccumulatedForecastByPeriodInner';
import AdjustedForecast from './model/AdjustedForecast';
import AdjustedForecastAdjustmentsAppliedInner from './model/AdjustedForecastAdjustmentsAppliedInner';
import AdjustmentsInner from './model/AdjustmentsInner';
import AnalysisResponse from './model/AnalysisResponse';
import AnalysisResponseMeta from './model/AnalysisResponseMeta';
import AnalysisResponseMetaTiming from './model/AnalysisResponseMetaTiming';
import AnalysisResponseResult from './model/AnalysisResponseResult';
import AnalysisResponseResultCharacteristics from './model/AnalysisResponseResultCharacteristics';
import AnomalyDetectionRequest from './model/AnomalyDetectionRequest';
import AnomalyDetectionRequestAllOfAnomalySettings from './model/AnomalyDetectionRequestAllOfAnomalySettings';
import AnomalyDetectionResponse from './model/AnomalyDetectionResponse';
import AnomalyDetectionResponseMeta from './model/AnomalyDetectionResponseMeta';
import AnomalyDetectionResponseMetaTiming from './model/AnomalyDetectionResponseMetaTiming';
import AnomalyDetectionResponseResult from './model/AnomalyDetectionResponseResult';
import AnomalyDetectionResponseResultAnalysis from './model/AnomalyDetectionResponseResultAnalysis';
import AnomalyDetectionResponseResultAnalysisDetectionSummary from './model/AnomalyDetectionResponseResultAnalysisDetectionSummary';
import AnomalyDetectionResponseResultAnomaliesInner from './model/AnomalyDetectionResponseResultAnomaliesInner';
import BatchForecastAccepted from './model/BatchForecastAccepted';
import BatchForecastRequest from './model/BatchForecastRequest';
import BatchForecastSeries from './model/BatchForecastSeries';
import BatchForecastSeriesDataInner from './model/BatchForecastSeriesDataInner';
import BatchForecastStatusResponse from './model/BatchForecastStatusResponse';
import BatchForecastStatusResponsePartsInner from './model/BatchForecastStatusResponsePartsInner';
import BatchForecastStatusResponseResults from './model/BatchForecastStatusResponseResults';
import BatchForecastStatusResponseResultsSummary from './model/BatchForecastStatusResponseResultsSummary';
import BatchPresignResponse from './model/BatchPresignResponse';
import BatchSeriesResult from './model/BatchSeriesResult';
import CreateBatchProductInsights422Response from './model/CreateBatchProductInsights422Response';
import CreateBatchProductInsights500Response from './model/CreateBatchProductInsights500Response';
import CreateForecast400Response from './model/CreateForecast400Response';
import CreateForecast502Response from './model/CreateForecast502Response';
import CreateInventoryPlan400Response from './model/CreateInventoryPlan400Response';
import CreateInventoryPlan500Response from './model/CreateInventoryPlan500Response';
import CreateProductInsights400Response from './model/CreateProductInsights400Response';
import CreateTrafficForecast500Response from './model/CreateTrafficForecast500Response';
import DetectAnomalies422Response from './model/DetectAnomalies422Response';
import DetectAnomalies422ResponseOneOf from './model/DetectAnomalies422ResponseOneOf';
import DetectAnomalies500Response from './model/DetectAnomalies500Response';
import ErrorResponse from './model/ErrorResponse';
import ForecastPeriod from './model/ForecastPeriod';
import ForecastRequest from './model/ForecastRequest';
import ForecastRequestDataInner from './model/ForecastRequestDataInner';
import ForecastResponse from './model/ForecastResponse';
import ForecastResponseMeta from './model/ForecastResponseMeta';
import ForecastResponseMetaTiming from './model/ForecastResponseMetaTiming';
import ForecastResponseResult from './model/ForecastResponseResult';
import GetApiRoot200Response from './model/GetApiRoot200Response';
import GetGroupedForecast404Response from './model/GetGroupedForecast404Response';
import GroupedForecastAccepted from './model/GroupedForecastAccepted';
import GroupedForecastNode from './model/GroupedForecastNode';
import GroupedForecastRequest from './model/GroupedForecastRequest';
import GroupedForecastResults from './model/GroupedForecastResults';
import GroupedForecastResultsReconciliation from './model/GroupedForecastResultsReconciliation';
import GroupedForecastSeries from './model/GroupedForecastSeries';
import GroupedForecastSeriesDataInner from './model/GroupedForecastSeriesDataInner';
import GroupedForecastStatusResponse from './model/GroupedForecastStatusResponse';
import HealthCheck200Response from './model/HealthCheck200Response';
import InventoryPlanningRequest from './model/InventoryPlanningRequest';
import InventoryPlanningRequestDataInner from './model/InventoryPlanningRequestDataInner';
import InventoryPlanningRequestInventorySettings from './model/InventoryPlanningRequestInventorySettings';
import InventoryPlanningRequestInventorySettingsSuppliersInner from './model/InventoryPlanningRequestInventorySettingsSuppliersInner';
import InventoryPlanningResponse from './model/InventoryPlanningResponse';
import InventoryPlanningResponseMeta from './model/InventoryPlanningResponseMeta';
import InventoryPlanningResponseMetaTiming from './model/InventoryPlanningResponseMetaTiming';
import InventoryPlanningResponseResult from './model/InventoryPlanningResponseResult';
import InventoryPlanningResponseResultForecastDataInner from './model/InventoryPlanningResponseResultForecastDataInner';
import InventoryPlanningResponseResultStockAnalysis from './model/InventoryPlanningResponseResultStockAnalysis';
import InventoryPlanningResponseResultSuppliersInner from './model/InventoryPlanningResponseResultSuppliersInner';
import ProductInsight from './model/ProductInsight';
import ProductInsightRecommendation from './model/ProductInsightRecommendation';
import ProductInsightsBatchRequest from './model/ProductInsightsBatchRequest';
import ProductInsightsBatchStatusResponse from './model/ProductInsightsBatchStatusResponse';
import ProductInsightsRequest from './model/ProductInsightsRequest';
import ProductInsightsRequestBaselinePeriodDays from './model/ProductInsightsRequestBaselinePeriodDays';
import ProductInsightsRequestCostHistoryInner from './model/ProductInsightsRequestCostHistoryInner';
import ProductInsightsRequestInsightSettings from './model/ProductInsightsRequestInsightSettings';
import ProductInsightsRequestPurchasesInner from './model/ProductInsightsRequestPurchasesInner';
import ProductInsightsRequestSalesInner from './model/ProductInsightsRequestSalesInner';
import ProductInsightsResponse from './model/ProductInsightsResponse';
import ProductInsightsResponseMeta from './model/ProductInsightsResponseMeta';
import ProductInsightsResponseMetaDataQuality from './model/ProductInsightsResponseMetaDataQuality';
import ProductInsightsResponseMetaTiming from './model/ProductInsightsResponseMetaTiming';
import ProductInsightsResponseResult from './model/ProductInsightsResponseResult';
import ProductInsightsResponseResultComparison from './model/ProductInsightsResponseResultComparison';
import ProductInsightsResponseResultComparisonDevelopments from './model/ProductInsightsResponseResultComparisonDevelopments';
import ProductInsightsResponseResultProductInfo from './model/ProductInsightsResponseResultProductInfo';
import ProductInsightsResponseResultSummary from './model/ProductInsightsResponseResultSummary';
import ProductInsightsResponseResultSummaryAnalysisPeriod from './model/ProductInsightsResponseResultSummaryAnalysisPeriod';
import TrafficForecastingRequest from './model/TrafficForecastingRequest';
import TrafficForecastingRequestDataInner from './model/TrafficForecastingRequestDataInner';
import TrafficForecastingRequestTrafficSettings from './model/TrafficForecastingRequestTrafficSettings';
import TrafficForecastingResponse from './model/TrafficForecastingResponse';
import TrafficForecastingResponseMeta from './model/TrafficForecastingResponseMeta';
import TrafficForecastingResponseMetaTiming from './model/TrafficForecastingResponseMetaTiming';
import TrafficForecastingResponseResult from './model/TrafficForecastingResponseResult';
import TrafficForecastingResponseResultCapacityAnalysis from './model/TrafficForecastingResponseResultCapacityAnalysis';
import TrafficForecastingResponseResultCapacityAnalysisUtilizationPeriodsInner from './model/TrafficForecastingResponseResultCapacityAnalysisUtilizationPeriodsInner';
import TrafficForecastingResponseResultCostOptimization from './model/TrafficForecastingResponseResultCostOptimization';
import TrafficForecastingResponseResultCostOptimizationCostBreakdown from './model/TrafficForecastingResponseResultCostOptimizationCostBreakdown';
import TrafficForecastingResponseResultCostOptimizationRecommendationsInner from './model/TrafficForecastingResponseResultCostOptimizationRecommendationsInner';
import TrafficForecastingResponseResultForecastDataInner from './model/TrafficForecastingResponseResultForecastDataInner';
import TrafficForecastingResponseResultScalingRecommendations from './model/TrafficForecastingResponseResultScalingRecommendations';
import TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner from './model/TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner';
import TrafficForecastingResponseResultTrafficAlerts from './model/TrafficForecastingResponseResultTrafficAlerts';
import TrafficForecastingResponseResultTrafficAlertsAlertsInner from './model/TrafficForecastingResponseResultTrafficAlertsAlertsInner';
import ValidationErrorResponse from './model/ValidationErrorResponse';
import ValidationFailedResponse from './model/ValidationFailedResponse';
import ValueBounds from './model/ValueBounds';
import AnalysisApi from './api/AnalysisApi';
import AnomalyDetectionApi from './api/AnomalyDetectionApi';
import BatchForecastingApi from './api/BatchForecastingApi';
import ForecastingApi from './api/ForecastingApi';
import GroupedForecastingApi from './api/GroupedForecastingApi';
import HealthApi from './api/HealthApi';
import InventoryPlanningApi from './api/InventoryPlanningApi';
import ProductInsightsApi from './api/ProductInsightsApi';
import TrafficForecastingApi from './api/TrafficForecastingApi';


/**
* Time series forecasting service with multiple algorithms and automatic method selection.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ForecastAPI = require('index'); // See note below*.
* var xxxSvc = new ForecastAPI.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ForecastAPI.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ForecastAPI.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ForecastAPI.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 2.0.2
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AccumulateOptions model constructor.
     * @property {module:model/AccumulateOptions}
     */
    AccumulateOptions,

    /**
     * The AccumulatedForecast model constructor.
     * @property {module:model/AccumulatedForecast}
     */
    AccumulatedForecast,

    /**
     * The AccumulatedForecastAssumptions model constructor.
     * @property {module:model/AccumulatedForecastAssumptions}
     */
    AccumulatedForecastAssumptions,

    /**
     * The AccumulatedForecastByPeriodInner model constructor.
     * @property {module:model/AccumulatedForecastByPeriodInner}
     */
    AccumulatedForecastByPeriodInner,

    /**
     * The AdjustedForecast model constructor.
     * @property {module:model/AdjustedForecast}
     */
    AdjustedForecast,

    /**
     * The AdjustedForecastAdjustmentsAppliedInner model constructor.
     * @property {module:model/AdjustedForecastAdjustmentsAppliedInner}
     */
    AdjustedForecastAdjustmentsAppliedInner,

    /**
     * The AdjustmentsInner model constructor.
     * @property {module:model/AdjustmentsInner}
     */
    AdjustmentsInner,

    /**
     * The AnalysisResponse model constructor.
     * @property {module:model/AnalysisResponse}
     */
    AnalysisResponse,

    /**
     * The AnalysisResponseMeta model constructor.
     * @property {module:model/AnalysisResponseMeta}
     */
    AnalysisResponseMeta,

    /**
     * The AnalysisResponseMetaTiming model constructor.
     * @property {module:model/AnalysisResponseMetaTiming}
     */
    AnalysisResponseMetaTiming,

    /**
     * The AnalysisResponseResult model constructor.
     * @property {module:model/AnalysisResponseResult}
     */
    AnalysisResponseResult,

    /**
     * The AnalysisResponseResultCharacteristics model constructor.
     * @property {module:model/AnalysisResponseResultCharacteristics}
     */
    AnalysisResponseResultCharacteristics,

    /**
     * The AnomalyDetectionRequest model constructor.
     * @property {module:model/AnomalyDetectionRequest}
     */
    AnomalyDetectionRequest,

    /**
     * The AnomalyDetectionRequestAllOfAnomalySettings model constructor.
     * @property {module:model/AnomalyDetectionRequestAllOfAnomalySettings}
     */
    AnomalyDetectionRequestAllOfAnomalySettings,

    /**
     * The AnomalyDetectionResponse model constructor.
     * @property {module:model/AnomalyDetectionResponse}
     */
    AnomalyDetectionResponse,

    /**
     * The AnomalyDetectionResponseMeta model constructor.
     * @property {module:model/AnomalyDetectionResponseMeta}
     */
    AnomalyDetectionResponseMeta,

    /**
     * The AnomalyDetectionResponseMetaTiming model constructor.
     * @property {module:model/AnomalyDetectionResponseMetaTiming}
     */
    AnomalyDetectionResponseMetaTiming,

    /**
     * The AnomalyDetectionResponseResult model constructor.
     * @property {module:model/AnomalyDetectionResponseResult}
     */
    AnomalyDetectionResponseResult,

    /**
     * The AnomalyDetectionResponseResultAnalysis model constructor.
     * @property {module:model/AnomalyDetectionResponseResultAnalysis}
     */
    AnomalyDetectionResponseResultAnalysis,

    /**
     * The AnomalyDetectionResponseResultAnalysisDetectionSummary model constructor.
     * @property {module:model/AnomalyDetectionResponseResultAnalysisDetectionSummary}
     */
    AnomalyDetectionResponseResultAnalysisDetectionSummary,

    /**
     * The AnomalyDetectionResponseResultAnomaliesInner model constructor.
     * @property {module:model/AnomalyDetectionResponseResultAnomaliesInner}
     */
    AnomalyDetectionResponseResultAnomaliesInner,

    /**
     * The BatchForecastAccepted model constructor.
     * @property {module:model/BatchForecastAccepted}
     */
    BatchForecastAccepted,

    /**
     * The BatchForecastRequest model constructor.
     * @property {module:model/BatchForecastRequest}
     */
    BatchForecastRequest,

    /**
     * The BatchForecastSeries model constructor.
     * @property {module:model/BatchForecastSeries}
     */
    BatchForecastSeries,

    /**
     * The BatchForecastSeriesDataInner model constructor.
     * @property {module:model/BatchForecastSeriesDataInner}
     */
    BatchForecastSeriesDataInner,

    /**
     * The BatchForecastStatusResponse model constructor.
     * @property {module:model/BatchForecastStatusResponse}
     */
    BatchForecastStatusResponse,

    /**
     * The BatchForecastStatusResponsePartsInner model constructor.
     * @property {module:model/BatchForecastStatusResponsePartsInner}
     */
    BatchForecastStatusResponsePartsInner,

    /**
     * The BatchForecastStatusResponseResults model constructor.
     * @property {module:model/BatchForecastStatusResponseResults}
     */
    BatchForecastStatusResponseResults,

    /**
     * The BatchForecastStatusResponseResultsSummary model constructor.
     * @property {module:model/BatchForecastStatusResponseResultsSummary}
     */
    BatchForecastStatusResponseResultsSummary,

    /**
     * The BatchPresignResponse model constructor.
     * @property {module:model/BatchPresignResponse}
     */
    BatchPresignResponse,

    /**
     * The BatchSeriesResult model constructor.
     * @property {module:model/BatchSeriesResult}
     */
    BatchSeriesResult,

    /**
     * The CreateBatchProductInsights422Response model constructor.
     * @property {module:model/CreateBatchProductInsights422Response}
     */
    CreateBatchProductInsights422Response,

    /**
     * The CreateBatchProductInsights500Response model constructor.
     * @property {module:model/CreateBatchProductInsights500Response}
     */
    CreateBatchProductInsights500Response,

    /**
     * The CreateForecast400Response model constructor.
     * @property {module:model/CreateForecast400Response}
     */
    CreateForecast400Response,

    /**
     * The CreateForecast502Response model constructor.
     * @property {module:model/CreateForecast502Response}
     */
    CreateForecast502Response,

    /**
     * The CreateInventoryPlan400Response model constructor.
     * @property {module:model/CreateInventoryPlan400Response}
     */
    CreateInventoryPlan400Response,

    /**
     * The CreateInventoryPlan500Response model constructor.
     * @property {module:model/CreateInventoryPlan500Response}
     */
    CreateInventoryPlan500Response,

    /**
     * The CreateProductInsights400Response model constructor.
     * @property {module:model/CreateProductInsights400Response}
     */
    CreateProductInsights400Response,

    /**
     * The CreateTrafficForecast500Response model constructor.
     * @property {module:model/CreateTrafficForecast500Response}
     */
    CreateTrafficForecast500Response,

    /**
     * The DetectAnomalies422Response model constructor.
     * @property {module:model/DetectAnomalies422Response}
     */
    DetectAnomalies422Response,

    /**
     * The DetectAnomalies422ResponseOneOf model constructor.
     * @property {module:model/DetectAnomalies422ResponseOneOf}
     */
    DetectAnomalies422ResponseOneOf,

    /**
     * The DetectAnomalies500Response model constructor.
     * @property {module:model/DetectAnomalies500Response}
     */
    DetectAnomalies500Response,

    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse,

    /**
     * The ForecastPeriod model constructor.
     * @property {module:model/ForecastPeriod}
     */
    ForecastPeriod,

    /**
     * The ForecastRequest model constructor.
     * @property {module:model/ForecastRequest}
     */
    ForecastRequest,

    /**
     * The ForecastRequestDataInner model constructor.
     * @property {module:model/ForecastRequestDataInner}
     */
    ForecastRequestDataInner,

    /**
     * The ForecastResponse model constructor.
     * @property {module:model/ForecastResponse}
     */
    ForecastResponse,

    /**
     * The ForecastResponseMeta model constructor.
     * @property {module:model/ForecastResponseMeta}
     */
    ForecastResponseMeta,

    /**
     * The ForecastResponseMetaTiming model constructor.
     * @property {module:model/ForecastResponseMetaTiming}
     */
    ForecastResponseMetaTiming,

    /**
     * The ForecastResponseResult model constructor.
     * @property {module:model/ForecastResponseResult}
     */
    ForecastResponseResult,

    /**
     * The GetApiRoot200Response model constructor.
     * @property {module:model/GetApiRoot200Response}
     */
    GetApiRoot200Response,

    /**
     * The GetGroupedForecast404Response model constructor.
     * @property {module:model/GetGroupedForecast404Response}
     */
    GetGroupedForecast404Response,

    /**
     * The GroupedForecastAccepted model constructor.
     * @property {module:model/GroupedForecastAccepted}
     */
    GroupedForecastAccepted,

    /**
     * The GroupedForecastNode model constructor.
     * @property {module:model/GroupedForecastNode}
     */
    GroupedForecastNode,

    /**
     * The GroupedForecastRequest model constructor.
     * @property {module:model/GroupedForecastRequest}
     */
    GroupedForecastRequest,

    /**
     * The GroupedForecastResults model constructor.
     * @property {module:model/GroupedForecastResults}
     */
    GroupedForecastResults,

    /**
     * The GroupedForecastResultsReconciliation model constructor.
     * @property {module:model/GroupedForecastResultsReconciliation}
     */
    GroupedForecastResultsReconciliation,

    /**
     * The GroupedForecastSeries model constructor.
     * @property {module:model/GroupedForecastSeries}
     */
    GroupedForecastSeries,

    /**
     * The GroupedForecastSeriesDataInner model constructor.
     * @property {module:model/GroupedForecastSeriesDataInner}
     */
    GroupedForecastSeriesDataInner,

    /**
     * The GroupedForecastStatusResponse model constructor.
     * @property {module:model/GroupedForecastStatusResponse}
     */
    GroupedForecastStatusResponse,

    /**
     * The HealthCheck200Response model constructor.
     * @property {module:model/HealthCheck200Response}
     */
    HealthCheck200Response,

    /**
     * The InventoryPlanningRequest model constructor.
     * @property {module:model/InventoryPlanningRequest}
     */
    InventoryPlanningRequest,

    /**
     * The InventoryPlanningRequestDataInner model constructor.
     * @property {module:model/InventoryPlanningRequestDataInner}
     */
    InventoryPlanningRequestDataInner,

    /**
     * The InventoryPlanningRequestInventorySettings model constructor.
     * @property {module:model/InventoryPlanningRequestInventorySettings}
     */
    InventoryPlanningRequestInventorySettings,

    /**
     * The InventoryPlanningRequestInventorySettingsSuppliersInner model constructor.
     * @property {module:model/InventoryPlanningRequestInventorySettingsSuppliersInner}
     */
    InventoryPlanningRequestInventorySettingsSuppliersInner,

    /**
     * The InventoryPlanningResponse model constructor.
     * @property {module:model/InventoryPlanningResponse}
     */
    InventoryPlanningResponse,

    /**
     * The InventoryPlanningResponseMeta model constructor.
     * @property {module:model/InventoryPlanningResponseMeta}
     */
    InventoryPlanningResponseMeta,

    /**
     * The InventoryPlanningResponseMetaTiming model constructor.
     * @property {module:model/InventoryPlanningResponseMetaTiming}
     */
    InventoryPlanningResponseMetaTiming,

    /**
     * The InventoryPlanningResponseResult model constructor.
     * @property {module:model/InventoryPlanningResponseResult}
     */
    InventoryPlanningResponseResult,

    /**
     * The InventoryPlanningResponseResultForecastDataInner model constructor.
     * @property {module:model/InventoryPlanningResponseResultForecastDataInner}
     */
    InventoryPlanningResponseResultForecastDataInner,

    /**
     * The InventoryPlanningResponseResultStockAnalysis model constructor.
     * @property {module:model/InventoryPlanningResponseResultStockAnalysis}
     */
    InventoryPlanningResponseResultStockAnalysis,

    /**
     * The InventoryPlanningResponseResultSuppliersInner model constructor.
     * @property {module:model/InventoryPlanningResponseResultSuppliersInner}
     */
    InventoryPlanningResponseResultSuppliersInner,

    /**
     * The ProductInsight model constructor.
     * @property {module:model/ProductInsight}
     */
    ProductInsight,

    /**
     * The ProductInsightRecommendation model constructor.
     * @property {module:model/ProductInsightRecommendation}
     */
    ProductInsightRecommendation,

    /**
     * The ProductInsightsBatchRequest model constructor.
     * @property {module:model/ProductInsightsBatchRequest}
     */
    ProductInsightsBatchRequest,

    /**
     * The ProductInsightsBatchStatusResponse model constructor.
     * @property {module:model/ProductInsightsBatchStatusResponse}
     */
    ProductInsightsBatchStatusResponse,

    /**
     * The ProductInsightsRequest model constructor.
     * @property {module:model/ProductInsightsRequest}
     */
    ProductInsightsRequest,

    /**
     * The ProductInsightsRequestBaselinePeriodDays model constructor.
     * @property {module:model/ProductInsightsRequestBaselinePeriodDays}
     */
    ProductInsightsRequestBaselinePeriodDays,

    /**
     * The ProductInsightsRequestCostHistoryInner model constructor.
     * @property {module:model/ProductInsightsRequestCostHistoryInner}
     */
    ProductInsightsRequestCostHistoryInner,

    /**
     * The ProductInsightsRequestInsightSettings model constructor.
     * @property {module:model/ProductInsightsRequestInsightSettings}
     */
    ProductInsightsRequestInsightSettings,

    /**
     * The ProductInsightsRequestPurchasesInner model constructor.
     * @property {module:model/ProductInsightsRequestPurchasesInner}
     */
    ProductInsightsRequestPurchasesInner,

    /**
     * The ProductInsightsRequestSalesInner model constructor.
     * @property {module:model/ProductInsightsRequestSalesInner}
     */
    ProductInsightsRequestSalesInner,

    /**
     * The ProductInsightsResponse model constructor.
     * @property {module:model/ProductInsightsResponse}
     */
    ProductInsightsResponse,

    /**
     * The ProductInsightsResponseMeta model constructor.
     * @property {module:model/ProductInsightsResponseMeta}
     */
    ProductInsightsResponseMeta,

    /**
     * The ProductInsightsResponseMetaDataQuality model constructor.
     * @property {module:model/ProductInsightsResponseMetaDataQuality}
     */
    ProductInsightsResponseMetaDataQuality,

    /**
     * The ProductInsightsResponseMetaTiming model constructor.
     * @property {module:model/ProductInsightsResponseMetaTiming}
     */
    ProductInsightsResponseMetaTiming,

    /**
     * The ProductInsightsResponseResult model constructor.
     * @property {module:model/ProductInsightsResponseResult}
     */
    ProductInsightsResponseResult,

    /**
     * The ProductInsightsResponseResultComparison model constructor.
     * @property {module:model/ProductInsightsResponseResultComparison}
     */
    ProductInsightsResponseResultComparison,

    /**
     * The ProductInsightsResponseResultComparisonDevelopments model constructor.
     * @property {module:model/ProductInsightsResponseResultComparisonDevelopments}
     */
    ProductInsightsResponseResultComparisonDevelopments,

    /**
     * The ProductInsightsResponseResultProductInfo model constructor.
     * @property {module:model/ProductInsightsResponseResultProductInfo}
     */
    ProductInsightsResponseResultProductInfo,

    /**
     * The ProductInsightsResponseResultSummary model constructor.
     * @property {module:model/ProductInsightsResponseResultSummary}
     */
    ProductInsightsResponseResultSummary,

    /**
     * The ProductInsightsResponseResultSummaryAnalysisPeriod model constructor.
     * @property {module:model/ProductInsightsResponseResultSummaryAnalysisPeriod}
     */
    ProductInsightsResponseResultSummaryAnalysisPeriod,

    /**
     * The TrafficForecastingRequest model constructor.
     * @property {module:model/TrafficForecastingRequest}
     */
    TrafficForecastingRequest,

    /**
     * The TrafficForecastingRequestDataInner model constructor.
     * @property {module:model/TrafficForecastingRequestDataInner}
     */
    TrafficForecastingRequestDataInner,

    /**
     * The TrafficForecastingRequestTrafficSettings model constructor.
     * @property {module:model/TrafficForecastingRequestTrafficSettings}
     */
    TrafficForecastingRequestTrafficSettings,

    /**
     * The TrafficForecastingResponse model constructor.
     * @property {module:model/TrafficForecastingResponse}
     */
    TrafficForecastingResponse,

    /**
     * The TrafficForecastingResponseMeta model constructor.
     * @property {module:model/TrafficForecastingResponseMeta}
     */
    TrafficForecastingResponseMeta,

    /**
     * The TrafficForecastingResponseMetaTiming model constructor.
     * @property {module:model/TrafficForecastingResponseMetaTiming}
     */
    TrafficForecastingResponseMetaTiming,

    /**
     * The TrafficForecastingResponseResult model constructor.
     * @property {module:model/TrafficForecastingResponseResult}
     */
    TrafficForecastingResponseResult,

    /**
     * The TrafficForecastingResponseResultCapacityAnalysis model constructor.
     * @property {module:model/TrafficForecastingResponseResultCapacityAnalysis}
     */
    TrafficForecastingResponseResultCapacityAnalysis,

    /**
     * The TrafficForecastingResponseResultCapacityAnalysisUtilizationPeriodsInner model constructor.
     * @property {module:model/TrafficForecastingResponseResultCapacityAnalysisUtilizationPeriodsInner}
     */
    TrafficForecastingResponseResultCapacityAnalysisUtilizationPeriodsInner,

    /**
     * The TrafficForecastingResponseResultCostOptimization model constructor.
     * @property {module:model/TrafficForecastingResponseResultCostOptimization}
     */
    TrafficForecastingResponseResultCostOptimization,

    /**
     * The TrafficForecastingResponseResultCostOptimizationCostBreakdown model constructor.
     * @property {module:model/TrafficForecastingResponseResultCostOptimizationCostBreakdown}
     */
    TrafficForecastingResponseResultCostOptimizationCostBreakdown,

    /**
     * The TrafficForecastingResponseResultCostOptimizationRecommendationsInner model constructor.
     * @property {module:model/TrafficForecastingResponseResultCostOptimizationRecommendationsInner}
     */
    TrafficForecastingResponseResultCostOptimizationRecommendationsInner,

    /**
     * The TrafficForecastingResponseResultForecastDataInner model constructor.
     * @property {module:model/TrafficForecastingResponseResultForecastDataInner}
     */
    TrafficForecastingResponseResultForecastDataInner,

    /**
     * The TrafficForecastingResponseResultScalingRecommendations model constructor.
     * @property {module:model/TrafficForecastingResponseResultScalingRecommendations}
     */
    TrafficForecastingResponseResultScalingRecommendations,

    /**
     * The TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner model constructor.
     * @property {module:model/TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner}
     */
    TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner,

    /**
     * The TrafficForecastingResponseResultTrafficAlerts model constructor.
     * @property {module:model/TrafficForecastingResponseResultTrafficAlerts}
     */
    TrafficForecastingResponseResultTrafficAlerts,

    /**
     * The TrafficForecastingResponseResultTrafficAlertsAlertsInner model constructor.
     * @property {module:model/TrafficForecastingResponseResultTrafficAlertsAlertsInner}
     */
    TrafficForecastingResponseResultTrafficAlertsAlertsInner,

    /**
     * The ValidationErrorResponse model constructor.
     * @property {module:model/ValidationErrorResponse}
     */
    ValidationErrorResponse,

    /**
     * The ValidationFailedResponse model constructor.
     * @property {module:model/ValidationFailedResponse}
     */
    ValidationFailedResponse,

    /**
     * The ValueBounds model constructor.
     * @property {module:model/ValueBounds}
     */
    ValueBounds,

    /**
    * The AnalysisApi service constructor.
    * @property {module:api/AnalysisApi}
    */
    AnalysisApi,

    /**
    * The AnomalyDetectionApi service constructor.
    * @property {module:api/AnomalyDetectionApi}
    */
    AnomalyDetectionApi,

    /**
    * The BatchForecastingApi service constructor.
    * @property {module:api/BatchForecastingApi}
    */
    BatchForecastingApi,

    /**
    * The ForecastingApi service constructor.
    * @property {module:api/ForecastingApi}
    */
    ForecastingApi,

    /**
    * The GroupedForecastingApi service constructor.
    * @property {module:api/GroupedForecastingApi}
    */
    GroupedForecastingApi,

    /**
    * The HealthApi service constructor.
    * @property {module:api/HealthApi}
    */
    HealthApi,

    /**
    * The InventoryPlanningApi service constructor.
    * @property {module:api/InventoryPlanningApi}
    */
    InventoryPlanningApi,

    /**
    * The ProductInsightsApi service constructor.
    * @property {module:api/ProductInsightsApi}
    */
    ProductInsightsApi,

    /**
    * The TrafficForecastingApi service constructor.
    * @property {module:api/TrafficForecastingApi}
    */
    TrafficForecastingApi
};
