/**
 * ForecastAPI
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@forecastapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../model/ErrorResponse';
import TrafficForecastingRequest from '../model/TrafficForecastingRequest';
import TrafficForecastingResponse from '../model/TrafficForecastingResponse';
import V2InventoryPlanningPost400Response from '../model/V2InventoryPlanningPost400Response';
import V2TrafficForecastingPost500Response from '../model/V2TrafficForecastingPost500Response';
import ValidationErrorResponse from '../model/ValidationErrorResponse';

/**
* TrafficForecasting service.
* @module ForecastAPI\ForecastSDK/api/TrafficForecastingApi
* @version 2.0.0
*/
export default class TrafficForecastingApi {

    /**
    * Constructs a new TrafficForecastingApi. 
    * @alias module:ForecastAPI\ForecastSDK/api/TrafficForecastingApi
    * @class
    * @param {module:ForecastAPI\ForecastSDK/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ForecastAPI\ForecastSDK/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the v2TrafficForecastingPost operation.
     * @callback module:ForecastAPI\ForecastSDK/api/TrafficForecastingApi~v2TrafficForecastingPostCallback
     * @param {String} error Error message, if any.
     * @param {module:ForecastAPI\ForecastSDK/model/TrafficForecastingResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Generate traffic forecasting with infrastructure scaling recommendations
     * Generate comprehensive traffic forecasts with infrastructure scaling recommendations, capacity analysis, cost optimization, and traffic anomaly alerts. This endpoint is designed for web applications, APIs, and infrastructure teams to predict traffic patterns and optimize resource allocation.  **Key Features:** - Intelligent traffic pattern forecasting with multiple algorithms - Infrastructure scaling recommendations (scale up/down/maintain) - Real-time capacity utilization analysis - Traffic spike and anomaly detection alerts - Cost optimization recommendations with potential savings - Auto-scaling benefit analysis - Support for various time frequencies (minute, hourly, daily, etc.) 
     * @param {module:ForecastAPI\ForecastSDK/model/TrafficForecastingRequest} trafficForecastingRequest 
     * @param {module:ForecastAPI\ForecastSDK/api/TrafficForecastingApi~v2TrafficForecastingPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:ForecastAPI\ForecastSDK/model/TrafficForecastingResponse}
     */
    v2TrafficForecastingPost(trafficForecastingRequest, callback) {
      let postBody = trafficForecastingRequest;
      // verify the required parameter 'trafficForecastingRequest' is set
      if (trafficForecastingRequest === undefined || trafficForecastingRequest === null) {
        throw new Error("Missing the required parameter 'trafficForecastingRequest' when calling v2TrafficForecastingPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TrafficForecastingResponse;
      return this.apiClient.callApi(
        '/v2/traffic-forecasting', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
